(()=>{'use strict';
const $=id=>document.getElementById(id);
let bpm=100,bars=4,countIn=true,cleanRecord=true,headphoneMode=false,quantDivision=16,quantStrength=1;
let ctx=null,masterGain=null,compressor=null,micStream=null,micSource=null,analyser=null,processor=null,silentGain=null;
let tracks=[],transportRunning=false,epoch=0,recording=false,armed=false,captureStart=0,captureTarget=0,captureIndex=0,captureData=null,meterSmooth=0,lastBeat=-1,cleanMuted=false,trackSeq=1;
const loopDur=()=>bars*4*60/bpm, beatDur=()=>60/bpm, qKey=()=>quantDivision+'@'+quantStrength.toFixed(3);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function setState(c,t){$('state').className=c||'';$('stateT').textContent=t}
function badge(live){$('badge').className='badge '+(live?'live':'ready');$('badge').textContent=live?'MIC AKTIV':'MIC AUS'}
function renderBars(){let el=$('barsSeg');el.innerHTML='';[1,2,4,8].forEach(n=>{let b=document.createElement('button');b.textContent=n;b.className=n===bars?'on':'';b.onclick=()=>{if(tracks.length||recording||armed)return toast('Spuren zuerst löschen');bars=n;$('barsV').textContent=n;renderBars();renderBeats()};el.appendChild(b)})}
function renderQ(){let el=$('quantSeg');el.innerHTML='';[4,8,16].forEach(n=>{let b=document.createElement('button');b.textContent='1/'+n;b.className=n===quantDivision?'on':'';b.onclick=async()=>{if(n===quantDivision)return;quantDivision=n;renderQ();updateQStatus();await reprocessEnabled()};el.appendChild(b)})}
function updateQStatus(){$('quantStatus').textContent='1/'+quantDivision+' · '+Math.round(quantStrength*100)+'%';$('strengthV').textContent=Math.round(quantStrength*100)+'%'}
function renderBeats(){let el=$('beats');el.innerHTML='';for(let r=0;r<bars;r++){let row=document.createElement('div');row.className='bar';let no=document.createElement('div');no.className='barN';no.textContent=r+1;row.appendChild(no);for(let j=0;j<4;j++){let c=document.createElement('div');c.className='beat';row.appendChild(c)}el.appendChild(row)}}
async function init(){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();masterGain=ctx.createGain();masterGain.gain.value=1.45;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-5;compressor.knee.value=8;compressor.ratio.value=6;compressor.attack.value=.003;compressor.release.value=.18;masterGain.connect(compressor);compressor.connect(ctx.destination);$('ov').classList.add('hide');badge(false);requestAnimationFrame(frame)}
function buttons(){let has=tracks.length>0;$('rec').disabled=has||recording||armed;$('newTrack').disabled=!has||recording||armed;$('play').disabled=!has||recording||armed;$('clear').disabled=!has&&!recording&&!armed;$('save').disabled=!has;$('playT').textContent=transportRunning?'STOP':'PLAY';$('playI').textContent=transportRunning?'■':'▶'}
function stopTrackSource(t){if(t.source){try{t.source.stop()}catch(e){}try{t.source.disconnect()}catch(e){}t.source=null}}
function activeBuffer(t){return t.quantEnabled&&t.quantBuffer?t.quantBuffer:t.originalBuffer}
function phase(){if(!transportRunning||!tracks.length)return 0;let d=loopDur(),p=(ctx.currentTime-epoch)%d;return p<0?p+d:p}
function startTrack(t,when,off=0){stopTrackSource(t);let s=ctx.createBufferSource();s.buffer=activeBuffer(t);s.loop=true;let g=t.gainNode||(t.gainNode=ctx.createGain());g.gain.value=t.muted?0:t.volume;s.connect(g);if(!g._connected){g.connect(masterGain);g._connected=true}s.start(when,off);t.source=s}
function startAll(when,off=0){tracks.forEach(t=>startTrack(t,when,off));epoch=when-off;transportRunning=true;setState('playState','Loop läuft');buttons()}
function stopAll(){tracks.forEach(stopTrackSource);transportRunning=false;setState('','Gestoppt');buttons()}
function restartOne(t){if(!transportRunning)return;let p=phase(),w=ctx.currentTime+.025;startTrack(t,w,p)}
function setCleanMute(on){if(!masterGain)return;cleanMuted=on;let v=on?0:(+$('master').value/100);masterGain.gain.cancelScheduledValues(ctx.currentTime);masterGain.gain.setTargetAtTime(v,ctx.currentTime,.015)}
async function openMic(){micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:!headphoneMode,noiseSuppression:false,autoGainControl:false,channelCount:1}});micSource=ctx.createMediaStreamSource(micStream);analyser=ctx.createAnalyser();analyser.fftSize=1024;micSource.connect(analyser);processor=ctx.createScriptProcessor(1024,1,1);silentGain=ctx.createGain();silentGain.gain.value=0;micSource.connect(processor);processor.connect(silentGain);silentGain.connect(ctx.destination);processor.onaudioprocess=onAudio;badge(true)}
function closeMic(){if(processor){processor.onaudioprocess=null;try{processor.disconnect()}catch(e){}}if(micSource){try{micSource.disconnect()}catch(e){}}if(silentGain){try{silentGain.disconnect()}catch(e){}}if(micStream){micStream.getTracks().forEach(t=>t.stop())}micStream=micSource=analyser=processor=silentGain=null;badge(false);$('db').textContent='MIC AUS';$('fill').style.width='0%'}
function onAudio(e){if(!recording||!captureData)return;let a=e.inputBuffer.getChannelData(0),sr=e.inputBuffer.sampleRate,t=e.playbackTime||ctx.currentTime;for(let i=0;i<a.length&&captureIndex<captureTarget;i++){if(t+i/sr<captureStart)continue;captureData[captureIndex++]=a[i]}if(captureIndex>=captureTarget){recording=false;armed=false;let d=captureData;captureData=null;setTimeout(()=>finishRecording(d),0)}}
function click(t,strong){let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=strong?1180:820;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(strong?.19:.11,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.05);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.06)}
function nextBoundaryAfter(t){let d=loopDur(),n=epoch;if(!transportRunning)return t;while(n<t)n+=d;return n}
async function armRecord(first){if(recording||armed)return;armed=true;buttons();try{await openMic()}catch(e){armed=false;buttons();closeMic();return toast('Mikrofon nicht verfügbar')}
 let pre=countIn?4*beatDur():0,now=ctx.currentTime+.12;
 if(first){captureStart=now+pre;if(countIn)for(let i=0;i<4;i++)click(now+i*beatDur(),i===0)}
 else if(transportRunning){captureStart=nextBoundaryAfter(ctx.currentTime+pre+.12);if(countIn){let c=captureStart-4*beatDur();for(let i=0;i<4;i++)click(c+i*beatDur(),i===0)}}
 else{captureStart=now+pre;if(countIn)for(let i=0;i<4;i++)click(now+i*beatDur(),i===0);startAll(captureStart,0)}
 captureTarget=Math.round(loopDur()*ctx.sampleRate);captureIndex=0;captureData=new Float32Array(captureTarget);
 if(cleanRecord&&!headphoneMode&&tracks.length){let ms=Math.max(0,(captureStart-ctx.currentTime)*1000);setTimeout(()=>setCleanMute(true),ms)}
 setState('armState',countIn?'Count-in…':'Aufnahme bereit…');
 let wait=Math.max(0,(captureStart-ctx.currentTime)*1000);setTimeout(()=>{if(!armed)return;recording=true;setState('recState','Aufnahme');buttons()},wait)
}
function normalizeBuffer(data){let peak=0;for(let v of data)peak=Math.max(peak,Math.abs(v));let boost=peak>0?Math.min(5,.88/peak):1;if(boost>1.03)for(let i=0;i<data.length;i++)data[i]*=boost;return boost}
function makeBuffer(data){normalizeBuffer(data);let b=ctx.createBuffer(1,data.length,ctx.sampleRate);b.copyToChannel(data,0);return b}
function finishRecording(data){closeMic();if(cleanMuted)setCleanMute(false);let b=makeBuffer(data),t={id:'t'+Date.now()+Math.random(),name:'Spur '+trackSeq++,originalBuffer:b,quantBuffer:null,quantEnabled:false,quantKey:null,analysisOnsets:null,processing:false,progress:0,eventCount:0,muted:false,volume:1,gainNode:null,source:null};tracks.push(t);
 if(!transportRunning)startAll(ctx.currentTime+.05,0);else startTrack(t,ctx.currentTime+.025,phase());
 setState('playState','Loop läuft');renderTracks();buttons();toast(t.name+' aufgenommen · Original unverändert')}
function waveform(buf){let a=buf.getChannelData(0),n=48,step=Math.max(1,Math.floor(a.length/n)),s='';for(let k=0;k<n;k++){let p=0,end=Math.min(a.length,(k+1)*step);for(let i=k*step;i<end;i++)p=Math.max(p,Math.abs(a[i]));s+='<i style="height:'+Math.max(3,Math.round(p*27))+'px"></i>'}return s}
function renderTracks(){let el=$('tracks');$('trackCount').textContent=tracks.length+' '+(tracks.length===1?'Spur':'Spuren');if(!tracks.length){el.innerHTML='<div class="tracksEmpty">Noch keine Aufnahme</div>';return}el.innerHTML='';
 tracks.forEach(t=>{let d=document.createElement('div');d.className='track';let qtxt=t.processing?'Analyse läuft…':t.quantEnabled?(t.eventCount+' Einsätze · 1/'+quantDivision+' · '+Math.round(quantStrength*100)+'%'):'Originalaufnahme aktiv';
 d.innerHTML='<div class="trackTop"><div><div class="trackName">'+t.name+'</div><div class="trackMeta">'+(t.quantEnabled?'TIMING FIX AKTIV':'ORIGINAL')+'</div></div><button class="tiny '+(!t.muted?'playing':'')+'" data-act="mute">'+(t.muted?'▶':'Ⅱ')+'</button><button class="tiny del" data-act="del">×</button></div><div class="wave">'+waveform(activeBuffer(t))+'</div><div class="volRow"><span>LAUTST.</span><input class="range" data-act="vol" type="range" min="0" max="150" value="'+Math.round(t.volume*100)+'"><span>'+Math.round(t.volume*100)+'%</span></div><div class="qrow"><button class="qbtn '+(t.quantEnabled?'on':'')+'" data-act="quant">'+(t.quantEnabled?'TIMING FIX AN':'TIMING FIX AUS')+'</button><div class="qinfo">'+qtxt+'</div></div>'+(t.processing?'<div class="progress"><span style="width:'+Math.round(t.progress*100)+'%"></span></div><div class="progressText">'+Math.round(t.progress*100)+'%</div>':'');
 d.querySelector('[data-act=mute]').onclick=()=>{t.muted=!t.muted;if(t.gainNode)t.gainNode.gain.setTargetAtTime(t.muted?0:t.volume,ctx.currentTime,.01);renderTracks()};
 d.querySelector('[data-act=del]').onclick=()=>{stopTrackSource(t);tracks=tracks.filter(x=>x!==t);if(!tracks.length)stopAll();renderTracks();buttons()};
 let vr=d.querySelector('[data-act=vol]');vr.oninput=e=>{t.volume=+e.target.value/100;if(t.gainNode&&!t.muted)t.gainNode.gain.setTargetAtTime(t.volume,ctx.currentTime,.01);e.target.nextElementSibling.textContent=Math.round(t.volume*100)+'%'};
 d.querySelector('[data-act=quant]').onclick=()=>toggleQuant(t);el.appendChild(d)})}
async function toggleQuant(t){if(t.processing)return;if(t.quantEnabled){t.quantEnabled=false;restartOne(t);renderTracks();return}
 if(t.quantBuffer&&t.quantKey===qKey()){t.quantEnabled=true;restartOne(t);renderTracks();return}
 await processTrack(t);if(t.quantBuffer){t.quantEnabled=true;restartOne(t)}renderTracks()}
async function reprocessEnabled(){let enabled=tracks.filter(t=>t.quantEnabled);if(!enabled.length)return;for(let t of enabled){t.quantEnabled=false;await processTrack(t);if(t.quantBuffer)t.quantEnabled=true;restartOne(t)}renderTracks()}
function percentile(arr,p){if(!arr.length)return 0;let c=Array.from(arr).sort((a,b)=>a-b),i=Math.min(c.length-1,Math.floor((c.length-1)*p));return c[i]}
function nearestZero(a,pos,rad){let best=Math.max(0,Math.min(a.length-1,pos)),bv=Math.abs(a[best]);for(let i=Math.max(1,pos-rad);i<Math.min(a.length-1,pos+rad);i++){let v=Math.abs(a[i]);if(v<bv){bv=v;best=i}if(a[i]===0||a[i-1]*a[i]<=0)return i}return best}
async function detectOnsets(a,sr,t){let hop=Math.max(64,Math.round(sr*.008)),frames=Math.ceil(a.length/hop),env=new Float32Array(frames),hf=new Float32Array(frames);for(let f=0;f<frames;f++){let se=0,sh=0,st=f*hop,en=Math.min(a.length,st+hop),prev=st>0?a[st-1]:0;for(let i=st;i<en;i++){let v=a[i],d=v-prev;se+=v*v;sh+=d*d;prev=v}env[f]=Math.sqrt(se/Math.max(1,en-st));hf[f]=Math.sqrt(sh/Math.max(1,en-st));if((f&127)===0){t.progress=.06+.22*f/frames;renderTracks();await sleep(0)}}let sm=new Float32Array(frames),hm=new Float32Array(frames);for(let i=0;i<frames;i++){let se=0,sh=0,c=0;for(let j=-2;j<=2;j++){let k=i+j;if(k>=0&&k<frames){se+=env[k];sh+=hf[k];c++}}sm[i]=se/c;hm[i]=sh/c}
 let score=new Float32Array(frames);for(let i=4;i<frames;i++){let eb=(sm[i-1]+sm[i-2]+sm[i-3]+sm[i-4])/4,hb=(hm[i-1]+hm[i-2]+hm[i-3]+hm[i-4])/4;score[i]=Math.max(0,sm[i]-eb)+.32*Math.max(0,hm[i]-hb)}
 let floor=percentile(sm,.28),q78=percentile(score,.78),mx=0;for(let v of score)mx=Math.max(mx,v);let thr=Math.max(q78*.58,mx*.055,.0012),gridSec=(60/bpm)*(4/quantDivision),minGap=Math.round(Math.max(.045,gridSec*.22)*sr),raw=[];
 for(let i=3;i<frames-3;i++){let attack=score[i]>=thr&&score[i]>=score[i-1]&&score[i]>=score[i+1]&&sm[i]>Math.max(.0035,floor*1.55);let gate=sm[i]>Math.max(.006,floor*2.1)&&sm[i-1]<=Math.max(.005,floor*1.7);if(attack||gate)raw.push({p:i*hop,s:score[i]+(gate?.02:0)})}
 raw.sort((x,y)=>x.p-y.p);let cand=[];for(let c of raw){if(!cand.length||c.p-cand[cand.length-1].p>=minGap)cand.push(c);else if(c.s>cand[cand.length-1].s)cand[cand.length-1]=c}
 if(cand.length<2){let gate=Math.max(.006,floor*1.9);for(let i=2;i<frames-2;i++){if(sm[i]>gate&&sm[i]>sm[i-1]*1.08&&sm[i]>=sm[i+1]){let p=i*hop;if(!cand.some(c=>Math.abs(c.p-p)<minGap))cand.push({p,s:score[i]})}}cand.sort((x,y)=>x.p-y.p)}
 t.progress=.43;renderTracks();await sleep(0);return cand.slice(0,512).map(x=>x.p)}
async function quantizeSlices(a,sr,onsets,t){let out=new Float32Array(a.length);if(!onsets.length)return new Float32Array(a);let grid=sr*(60/bpm)*(4/quantDivision),fade=Math.max(16,Math.round(sr*.006)),pre=Math.round(sr*.010),starts=onsets.map(p=>Math.max(0,p-pre));starts[0]=Math.min(starts[0],onsets[0]);if(starts[0]>0)out.set(a.subarray(0,starts[0]),0);
 for(let e=0;e<onsets.length;e++){let onset=onsets[e],st=starts[e],en=e+1<onsets.length?starts[e+1]:a.length,target=Math.round(onset/grid)*grid,shift=Math.round((target-onset)*quantStrength),dst=st+shift,len=en-st;if(len<=0)continue;let zst=nearestZero(a,st,Math.round(sr*.003)),adjust=zst-st;st=zst;dst+=adjust;len=en-st;
  for(let j=0;j<len;j++){let si=st+j,di=dst+j;if(di<0||di>=out.length||si>=a.length)continue;let w=1;if(j<fade)w=j/fade;else if(len-j<fade)w=(len-j)/fade;out[di]+=a[si]*Math.max(0,Math.min(1,w))}
  if((e&7)===0){t.progress=.48+.45*(e+1)/onsets.length;renderTracks();await sleep(0)}
 }
 let pk=0;for(let v of out)pk=Math.max(pk,Math.abs(v));if(pk>.98){let sc=.98/pk;for(let i=0;i<out.length;i++)out[i]*=sc}return out}
async function processTrack(t){t.processing=true;t.progress=.02;renderTracks();await sleep(20);let a=t.originalBuffer.getChannelData(0),sr=t.originalBuffer.sampleRate,on=t.analysisOnsets;if(!on){on=await detectOnsets(a,sr,t);t.analysisOnsets=on;t.eventCount=on.length}else{t.progress=.46;renderTracks();await sleep(0)}let q=await quantizeSlices(a,sr,on,t);let b=ctx.createBuffer(1,q.length,sr);b.copyToChannel(q,0);t.quantBuffer=b;t.quantKey=qKey();t.eventCount=on.length;t.progress=1;renderTracks();await sleep(100);t.processing=false;renderTracks();toast(t.name+': '+on.length+' Einsätze korrigiert')}
function clearAll(){closeMic();tracks.forEach(stopTrackSource);tracks=[];transportRunning=false;recording=armed=false;captureData=null;setCleanMute(false);setState('','Bereit');$('timer').textContent='00:00.0';$('pos').textContent='—';renderTracks();buttons();document.querySelectorAll('.beat').forEach(x=>x.className='beat')}
function meter(){if(!analyser){meterSmooth*=.8;$('fill').style.width=meterSmooth+'%';return}let a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);let s=0;for(let v of a)s+=v*v;let rms=Math.sqrt(s/a.length),db=rms?20*Math.log10(rms):-100,p=Math.max(0,Math.min(100,(db+60)/60*100));meterSmooth=meterSmooth*.75+p*.25;$('fill').style.width=meterSmooth+'%';$('db').textContent=db<-60?'−∞ dB':db.toFixed(1)+' dB'}
function visuals(){if(!ctx)return;let p=recording?Math.max(0,ctx.currentTime-captureStart):(transportRunning?phase():-1);if(p<0)return;let mi=Math.floor(p/60),se=Math.floor(p%60),te=Math.floor(p%1*10);$('timer').textContent=String(mi).padStart(2,'0')+':'+String(se).padStart(2,'0')+'.'+te;let bi=Math.min(bars*4-1,Math.floor((p%loopDur())/beatDur())),ba=Math.floor(bi/4),bb=bi%4;$('pos').textContent='Takt '+(ba+1)+'/'+bars+' · Beat '+(bb+1)+'/4';if(bi!==lastBeat){lastBeat=bi;document.querySelectorAll('.beat').forEach((x,i)=>{x.classList.toggle('past',i<=bi);x.classList.toggle('now',i===bi)})}}
function frame(){meter();visuals();requestAnimationFrame(frame)}
function wavBlob(){let rate=44100,n=Math.round(loopDur()*rate),mix=new Float32Array(n),active=tracks.filter(t=>!t.muted);for(let t of active){let b=activeBuffer(t),a=b.getChannelData(0),r=b.sampleRate/rate;for(let i=0;i<n;i++){let p=i*r,j=Math.floor(p),f=p-j,v=(a[j]||0)*(1-f)+(a[Math.min(j+1,a.length-1)]||0)*f;mix[i]+=v*t.volume}}let m=+$('master').value/100,pk=0;for(let i=0;i<n;i++){mix[i]*=m;pk=Math.max(pk,Math.abs(mix[i]))}if(pk>.98){let s=.98/pk;for(let i=0;i<n;i++)mix[i]*=s}let ab=new ArrayBuffer(44+n*4),v=new DataView(ab),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+n*4,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,rate,true);v.setUint32(28,rate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,n*4,true);let o=44;for(let i=0;i<n;i++){let s=Math.max(-1,Math.min(1,mix[i])),q=s<0?s*32768:s*32767;v.setInt16(o,q,true);v.setInt16(o+2,q,true);o+=4}return new Blob([v],{type:'audio/wav'})}
async function save(){let blob=wavBlob(),file=new File([blob],`TouchLoop_${bpm}BPM_${bars}bars.wav`,{type:'audio/wav'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return await navigator.share({title:'TouchLoop 5',files:[file]})}catch(e){if(e.name==='AbortError')return}let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
$('start').onclick=init;$('rec').onclick=()=>armRecord(true);$('newTrack').onclick=()=>armRecord(false);$('play').onclick=()=>transportRunning?stopAll():startAll(ctx.currentTime+.04,0);$('clear').onclick=clearAll;$('save').onclick=save;
$('bpm').oninput=e=>{if(tracks.length){e.target.value=bpm;return toast('Spuren zuerst löschen')}bpm=+e.target.value;$('bpmV').textContent=bpm};$('minus').onclick=()=>{if(!tracks.length&&bpm>50){bpm--;$('bpm').value=bpm;$('bpmV').textContent=bpm}};$('plus').onclick=()=>{if(!tracks.length&&bpm<180){bpm++;$('bpm').value=bpm;$('bpmV').textContent=bpm}};
$('count').onclick=()=>{countIn=!countIn;$('count').classList.toggle('on',countIn);$('count').textContent=countIn?'1 Takt Count-in':'Count-in aus'};$('clean').onclick=()=>{cleanRecord=!cleanRecord;$('clean').classList.toggle('on',cleanRecord);$('clean').textContent=cleanRecord?'✓ Clean Record':'Clean Record aus'};$('phones').onclick=()=>{headphoneMode=!headphoneMode;$('phones').classList.toggle('on',headphoneMode);$('phones').textContent=headphoneMode?'✓ Kopfhörer-Modus':'Kopfhörer-Modus'};
$('master').oninput=e=>{let v=+e.target.value/100;$('masterV').textContent=Math.round(v*100)+'%';if(masterGain&&!cleanMuted)masterGain.gain.setTargetAtTime(v,ctx.currentTime,.01)};
$('quantStrength').oninput=e=>{quantStrength=+e.target.value/100;updateQStatus()};$('quantStrength').onchange=()=>reprocessEnabled();
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&ctx&&ctx.state==='suspended')try{await ctx.resume()}catch(e){}});
renderBars();renderQ();renderBeats();renderTracks();updateQStatus();buttons();
})();