(()=>{
'use strict';
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d',{alpha:false});
const W=canvas.width,H=canvas.height,N=72,GEN_TICKS=1400;
let fieldFood=new Float32Array(N*N),fieldToxin=new Float32Array(N*N),fieldSignal=new Float32Array(N*N),walls=new Uint8Array(N*N);
let colonies=[],generation=1,tick=0,running=true,speed=1,tool='feed',selected=null,history=[];
const colors=['#7ddf9a','#72b7ff','#d8c9a3','#ffad71','#d58cff','#b9d9d0'];
const $=id=>document.getElementById(id); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const rnd=(a=1,b=0)=>Math.random()*(a-b)+b;
function idx(x,y){return clamp(x|0,0,N-1)+clamp(y|0,0,N-1)*N}
function genome(base){const g=base?JSON.parse(JSON.stringify(base)):{metab:rnd(.024,.011),adhesion:rnd(1.35,.72),division:rnd(1.45,.92),toxinRes:rnd(.82,.15),signalSense:rnd(1.3,.3),motility:rnd(1.3,.2),sporeCost:rnd(1.35,.78),bias:[rnd(1.2,.5),rnd(1.2,.5),rnd(1.2,.5),rnd(1.2,.5),rnd(1.2,.5),rnd(1.2,.5)],thresholds:[rnd(.8,.2),rnd(.8,.2),rnd(.8,.2)]};if(base){g.metab*=Math.exp(rnd(.06,-.06));g.adhesion*=Math.exp(rnd(.08,-.08));g.division*=Math.exp(rnd(.08,-.08));g.toxinRes=clamp(g.toxinRes+rnd(.06,-.06),.05,1.4);g.signalSense=clamp(g.signalSense+rnd(.09,-.09),.1,1.8);g.motility=clamp(g.motility+rnd(.12,-.12),.05,1.8);g.sporeCost*=Math.exp(rnd(.07,-.07));for(let i=0;i<6;i++)g.bias[i]=clamp(g.bias[i]*Math.exp(rnd(.12,-.12)),.2,2);for(let i=0;i<3;i++)g.thresholds[i]=clamp(g.thresholds[i]+rnd(.08,-.08),.05,.95)}return g}
function makeColony(id,x,y,g,parent=0){return{id,parent,gen:g,cells:[{x,y,vx:0,vy:0,e:1.1,type:5,age:0}],spores:0,born:generation,hue:(id*71)%360,fitness:0,name:`Line ${String.fromCharCode(65+(id%26))}${generation}`}}
function seedInitial(){colonies=[];for(let i=0;i<10;i++){const a=i/10*Math.PI*2,r=235;colonies.push(makeColony(i,W/2+Math.cos(a)*r,H/2+Math.sin(a)*r,genome()))}selected=null}
function resetFields(){fieldFood.fill(.17);fieldToxin.fill(0);fieldSignal.fill(0);walls.fill(0);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const d=Math.hypot(x-N/2,y-N/2);fieldFood[idx(x,y)]+=Math.max(0,.22-d*.0025)+Math.random()*.04}}
function sample(arr,x,y){return arr[idx(x/W*N,y/H*N)]}
function addField(arr,x,y,amount,radius){const gx=x/W*N,gy=y/H*N,rr=radius/W*N;for(let yy=Math.max(0,(gy-rr)|0);yy<Math.min(N,(gy+rr)|0);yy++)for(let xx=Math.max(0,(gx-rr)|0);xx<Math.min(N,(gx+rr)|0);xx++){const d=Math.hypot(xx-gx,yy-gy);if(d<rr)arr[idx(xx,yy)]=clamp(arr[idx(xx,yy)]+amount*(1-d/rr),0,1.5)}}
function differentiate(c,col){const food=sample(fieldFood,c.x,c.y),tox=sample(fieldToxin,c.x,c.y),sig=sample(fieldSignal,c.x,c.y),g=col.gen;let score=[g.bias[0]*(food<g.thresholds[0]?1.5:.8),g.bias[1]*(sig*g.signalSense>.35?1.6:.7),g.bias[2]*(tox>.25?1.45:.8),g.bias[3]*(food<.16?1.45:.7),g.bias[4]*(c.e>1.4&&c.age>90?1.7:.6),g.bias[5]*.75],best=0;for(let i=1;i<6;i++)if(score[i]>score[best])best=i;c.type=best}
function nearestFoodForce(c){let gx=c.x/W*N,gy=c.y/H*N,best=0,bx=0,by=0;for(let k=0;k<8;k++){let a=k/8*Math.PI*2,xx=gx+Math.cos(a)*3,yy=gy+Math.sin(a)*3,v=fieldFood[idx(xx,yy)]-fieldToxin[idx(xx,yy)]*.6;if(v>best){best=v;bx=Math.cos(a);by=Math.sin(a)}}return[bx,by]}
function stepColony(col){const cells=col.cells,g=col.gen;for(let i=cells.length-1;i>=0;i--){const c=cells[i];c.age++;let food=sample(fieldFood,c.x,c.y),tox=sample(fieldToxin,c.x,c.y),uptake=(c.type===0?.014:.006)*(1+food*2);c.e+=uptake-g.metab*(c.type===3?1.6:1)*(1+tox*(1.4-g.toxinRes));fieldFood[idx(c.x/W*N,c.y/H*N)]=Math.max(0,food-uptake*.32);if(c.type===1)addField(fieldSignal,c.x,c.y,.004,26);if(c.age%85===0)differentiate(c,col);if(c.type===3){const [fx,fy]=nearestFoodForce(c);c.vx+=fx*.05*g.motility;c.vy+=fy*.05*g.motility}c.vx*=.91;c.vy*=.91;c.x=clamp(c.x+c.vx,10,W-10);c.y=clamp(c.y+c.vy,10,H-10);const wi=idx(c.x/W*N,c.y/H*N);if(walls[wi]){c.vx*=-.9;c.vy*=-.9;c.x+=c.vx*2;c.y+=c.vy*2}if(c.e<=0||tox>1.1+g.toxinRes*.3){cells.splice(i,1);continue}if(c.type===4&&c.e>g.sporeCost+1&&c.age>130){col.spores++;col.fitness+=1;c.e-=g.sporeCost;c.type=5}if(c.e>g.division+1&&cells.length<85){c.e*=.53;const a=Math.random()*Math.PI*2,d=8,n={x:clamp(c.x+Math.cos(a)*d,5,W-5),y:clamp(c.y+Math.sin(a)*d,5,H-5),vx:Math.cos(a)*.3,vy:Math.sin(a)*.3,e:c.e,type:5,age:0};cells.push(n)}}for(let i=0;i<cells.length;i++){let a=cells[i];for(let j=i+1;j<Math.min(cells.length,i+18);j++){let b=cells[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;if(d<18){let f=(18-d)*.018;a.vx-=dx/d*f;a.vy-=dy/d*f;b.vx+=dx/d*f;b.vy+=dy/d*f}else if(d<42&&g.adhesion>.9){let f=(d-26)*.0008*g.adhesion;a.vx+=dx/d*f;a.vy+=dy/d*f;b.vx-=dx/d*f;b.vy-=dy/d*f}}}}
function diffuse(){for(let y=1;y<N-1;y++)for(let x=1;x<N-1;x++){let i=idx(x,y);fieldFood[i]=clamp(fieldFood[i]*.9993+.00008,0,1.5);fieldToxin[i]*=.9982;fieldSignal[i]*=.992}}
function nextGeneration(){let totalSpores=colonies.reduce((s,c)=>s+c.spores,0),pool=[];for(const c of colonies)for(let k=0;k<Math.max(0,c.spores);k++)pool.push(c);history.push(totalSpores);if(history.length>24)history.shift();generation++;tick=0;resetFields();const next=[];if(pool.length===0){for(let i=0;i<10;i++)next.push(makeColony(i,rnd(W-160,80),rnd(H-160,80),genome()))}else{for(let i=0;i<10;i++){let p=pool[(Math.random()*pool.length)|0],a=i/10*Math.PI*2,r=220;next.push(makeColony(i,W/2+Math.cos(a)*r,H/2+Math.sin(a)*r,genome(p.gen),p.id))}}colonies=next;selected=null;$('message').textContent=`Generation ${generation} seeded from ${totalSpores} viable spores. Regulatory programs mutated through selection.`;updateInspector()}
function simStep(){tick++;diffuse();for(const c of colonies)stepColony(c);if(tick>=GEN_TICKS)nextGeneration()}
function render(){ctx.fillStyle='#06100d';ctx.fillRect(0,0,W,H);const s=W/N;for(let y=0;y<N;y+=2)for(let x=0;x<N;x+=2){let i=idx(x,y),f=fieldFood[i],t=fieldToxin[i],q=fieldSignal[i];if(f+t+q>.04){ctx.fillStyle=`rgba(${Math.floor(40+t*150)},${Math.floor(70+f*85)},${Math.floor(58+q*120)},${clamp((f+t+q)*.14,.02,.18)})`;ctx.fillRect(x*s,y*s,s*2+1,s*2+1)}if(walls[i]){ctx.fillStyle='#d5dfda44';ctx.fillRect(x*s,y*s,s*2+1,s*2+1)}}for(const col of colonies){for(const c of col.cells){ctx.beginPath();ctx.arc(c.x,c.y,c.type===2?6.6:5.2,0,Math.PI*2);ctx.fillStyle=colors[c.type];ctx.globalAlpha=.86;ctx.fill();ctx.globalAlpha=1;if(selected===col){ctx.strokeStyle='#fff7';ctx.lineWidth=1;ctx.stroke()}}if(selected===col&&col.cells.length){let cx=col.cells.reduce((s,c)=>s+c.x,0)/col.cells.length,cy=col.cells.reduce((s,c)=>s+c.y,0)/col.cells.length;ctx.beginPath();ctx.arc(cx,cy,38,0,Math.PI*2);ctx.strokeStyle='#8ad6ff';ctx.lineWidth=2;ctx.stroke()}}}
function updateUI(){$('gen').textContent=generation;$('cycle').textContent=tick;$('cols').textContent=colonies.length;$('cells').textContent=colonies.reduce((s,c)=>s+c.cells.length,0);$('phase').textContent=tick<1050?'development':'sporulation';$('selectedName').textContent=selected?selected.name:'none'}
function updateInspector(){if(!selected){$('lineage').textContent='Select a colony to view its inherited developmental program.';$('traits').innerHTML=''}else{let g=selected.gen;$('lineage').textContent=`${selected.name} · ${selected.cells.length} cells · ${selected.spores} spores · born generation ${selected.born}`;let data=[['Division',2-g.division/1.2],['Adhesion',g.adhesion/1.5],['Toxin resist',g.toxinRes/1.4],['Signal sense',g.signalSense/1.8],['Motility',g.motility/1.8],['Metabolic thrift',1-g.metab/.03]];$('traits').innerHTML=data.map(([n,v])=>`<div class="trait"><span>${n}</span><span class="bar"><i style="width:${clamp(v,0,1)*100}%"></i></span><b>${Math.round(clamp(v,0,1)*100)}</b></div>`).join('')}const max=Math.max(1,...history);$('history').innerHTML=history.map(v=>`<i style="height:${8+54*v/max}px" title="${v}"></i>`).join('')}
function pointerPos(e){const r=canvas.getBoundingClientRect();return[(e.clientX-r.left)/r.width*W,(e.clientY-r.top)/r.height*H]}
function applyTool(x,y){if(tool==='feed')addField(fieldFood,x,y,.38,70);else if(tool==='toxin')addField(fieldToxin,x,y,.3,62);else if(tool==='signal')addField(fieldSignal,x,y,.45,72);else if(tool==='wall'){const gx=x/W*N,gy=y/H*N;for(let yy=gy-2;yy<=gy+2;yy++)for(let xx=gx-2;xx<=gx+2;xx++)walls[idx(xx,yy)]=1}else{let best=null,bd=70;for(const c of colonies)for(const cell of c.cells){let d=Math.hypot(cell.x-x,cell.y-y);if(d<bd){bd=d;best=c}}selected=best;updateInspector()}}
let painting=false;canvas.addEventListener('pointerdown',e=>{painting=true;canvas.setPointerCapture(e.pointerId);let [x,y]=pointerPos(e);applyTool(x,y)});canvas.addEventListener('pointermove',e=>{if(!painting||tool==='inspect')return;let [x,y]=pointerPos(e);applyTool(x,y)});canvas.addEventListener('pointerup',()=>painting=false);document.querySelectorAll('.tool').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool}));document.querySelectorAll('.speed').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.speed').forEach(x=>x.classList.remove('active'));b.classList.add('active');speed=+b.dataset.speed}));$('pause').addEventListener('click',()=>{running=!running;$('pause').textContent=running?'Pause':'Resume'});$('pulse').addEventListener('click',()=>{let kind=Math.random()<.5?'toxin':'feed';for(let i=0;i<5;i++)addField(kind==='toxin'?fieldToxin:fieldFood,rnd(W),rnd(H),kind==='toxin'?.25:.34,90);$('message').textContent=kind==='toxin'?'A toxic climate pulse created new local selection pressure.':'A nutrient bloom reshaped competition and developmental payoffs.'});$('reset').addEventListener('click',()=>{generation=1;tick=0;history=[];resetFields();seedInitial();updateInspector();$('message').textContent='New experiment started with ten unrelated zygote lineages.'});
resetFields();seedInitial();updateInspector();let last=0;function loop(t){if(t-last>16){last=t;if(running)for(let i=0;i<speed;i++)simStep();render();updateUI();if(t%500<18)updateInspector()}requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();