(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sim=$('#sim'), ctx=sim.getContext('2d'), preview=$('#preview'), pctx=preview.getContext('2d'), chart=$('#chart'), cctx=chart.getContext('2d');
const ui={gen:$('#genOut'),pop:$('#popOut'),best:$('#bestOut'),time:$('#timeOut'),name:$('#creatureName'),genes:$('#genes'),dist:$('#distOut'),energy:$('#energyOut'),child:$('#childOut'),fit:$('#fitOut'),tool:$('#toolLabel'),pin:$('#pinBtn'),note:$('#chartNote'),toast:$('#toast')};
const rand=(a=1,b=0)=>b+Math.random()*(a-b), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
let DPR=Math.min(devicePixelRatio||1,2), W=360,H=420, running=true,speed=1,tool='raise',sound=true,last=performance.now(),acc=0,simTime=0,generation=1,selected=0,pinned=null,beaconX=0.88;
let history=[],lineage=[],food=[],particles=[];
const terrainN=90, terrain=new Float32Array(terrainN);
function initTerrain(){for(let i=0;i<terrainN;i++){const t=i/(terrainN-1);terrain[i]=0.78+Math.sin(t*9)*.025+Math.sin(t*23)*.012;}terrain[0]=terrain[1]=.79;food=[.25,.46,.67].map(x=>({x,y:terrainAt(x)-.035,energy:55,active:true}));}
function terrainAt(nx){const x=clamp(nx,0,1)*(terrainN-1),i=Math.floor(x),f=x-i;return lerp(terrain[i],terrain[Math.min(i+1,terrainN-1)],f);}
function terrainSlope(nx){const e=.008;return (terrainAt(nx+e)-terrainAt(nx-e))/(2*e);}
function resize(){const r=sim.getBoundingClientRect();W=r.width;H=r.height;sim.width=Math.round(W*DPR);sim.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);const pr=preview.getBoundingClientRect();preview.width=Math.round(pr.width*DPR);preview.height=Math.round(pr.height*DPR);pctx.setTransform(DPR,0,0,DPR,0,0);const cr=chart.getBoundingClientRect();chart.width=Math.round(cr.width*DPR);chart.height=Math.round(cr.height*DPR);cctx.setTransform(DPR,0,0,DPR,0,0);drawChart();}
function genomeRandom(){return {body:rand(.50,.95),legA:rand(.45,1.1),legB:rand(.45,1.1),foot:rand(.35,1.0),muscle:rand(.45,1.15),spring:rand(.35,1.0),friction:rand(.35,1.15),metabolism:rand(.55,1.05),sense:rand(.35,1.0),freq:rand(.6,1.7),phase:rand(-1,1),balance:rand(-.8,.8)};}
const geneKeys=['body','legA','legB','foot','muscle','spring','friction','metabolism','sense','freq','phase','balance'];
function mixGenome(a,b){const g={};for(const k of geneKeys){let v=Math.random()<.5?a[k]:b[k];if(Math.random()<.35)v+=rand(.12,-.12);if(k==='phase'||k==='balance')v=clamp(v,-1.2,1.2);else v=clamp(v,.2,1.8);g[k]=v;}return g;}
function creature(genome,id,parentA=null,parentB=null){const x=.055+rand(.018),y=terrainAt(.06)-.09;return {id,genome,parentA,parentB,x,y,vx:0,vy:0,angle:0,av:0,energy:100,alive:true,age:0,dist:0,fitness:0,children:0,contacts:[false,false],joint:[0,Math.PI],line:Math.floor(rand(0,9999)),bestX:x};}
let pop=[];
function initPop(){pop=Array.from({length:18},(_,i)=>creature(genomeRandom(),i));selected=0;pinned=null;simTime=0;generation=1;history=[];lineage=[];initTerrain();syncUI();}
function bodyDims(c){return {r:9+9*c.genome.body,l1:13+15*c.genome.legA,l2:12+15*c.genome.legB,foot:5+8*c.genome.foot};}
function neural(c,leg){const g=c.genome,t=c.age*g.freq*4.5;const target=beaconX-c.x;const slope=terrainSlope(c.x);const contact=c.contacts[leg]?1:-1;const osc=Math.sin(t+leg*Math.PI+g.phase*1.7);const sensor=Math.tanh(target*g.sense*1.4-slope*4*g.balance+contact*.3);return clamp(osc*.78+sensor*.52,-1,1);}
function stepCreature(c,dt){if(!c.alive)return;c.age+=dt;const g=c.genome,d=bodyDims(c);const slope=terrainSlope(c.x);const left=neural(c,0),right=neural(c,1);const drive=(left-right)*g.muscle;const sync=(left+right)*.5;const contactGround=c.y+d.r/H>terrainAt(c.x)-.015;c.contacts[0]=contactGround&&left<.4;c.contacts[1]=contactGround&&right<.4;const traction=(Number(c.contacts[0])+Number(c.contacts[1]))*.5*g.friction;c.vx+=(drive*.17*traction-slope*.22-c.vx*.26)*dt;c.vy+=(.44-traction*.16*Math.max(0,sync))*dt;c.av+=((right-left)*.18*g.spring-c.angle*.42*g.balance-c.av*.32)*dt;c.angle+=c.av*dt;c.x+=c.vx*dt;c.y+=c.vy*dt;const floor=terrainAt(c.x)-d.r/H*.72;if(c.y>floor){c.y=floor;c.vy*=-.12;c.vx*=clamp(.88+.05*g.friction,.8,.97);c.angle*=.96;}c.x=clamp(c.x,.025,.97);c.energy-=dt*(1.4*g.metabolism+.95*Math.abs(drive)*g.muscle+.24*Math.abs(c.av));for(const f of food){if(f.active&&Math.abs(c.x-f.x)<.018&&Math.abs(c.y-f.y)<.045){f.active=false;c.energy=Math.min(120,c.energy+f.energy);burst(f.x*W,f.y*H,'#8af0a5');beep(680,.04,.025);}}if(c.energy<=0||Math.abs(c.angle)>2.0){c.alive=false;c.energy=Math.max(0,c.energy);}c.bestX=Math.max(c.bestX,c.x);c.dist=Math.max(0,(c.bestX-.055)*100);c.fitness=c.dist+c.energy*.035-Math.abs(c.angle)*1.6+(c.x>=beaconX-.025?20:0);}
function physics(dt){for(const c of pop)stepCreature(c,dt);simTime+=dt;if(simTime>=30||pop.every(c=>!c.alive))evolve();}
function evolve(){const sorted=[...pop].sort((a,b)=>b.fitness-a.fitness),best=sorted[0],avg=pop.reduce((s,c)=>s+c.dist,0)/pop.length;history.push({gen:generation,best:best.dist,avg});if(history.length>24)history.shift();const elite=sorted.slice(0,Math.max(4,Math.floor(pop.length*.34)));if(pinned!=null){const pc=pop.find(c=>c.id===pinned);if(pc&&!elite.includes(pc))elite[elite.length-1]=pc;}const children=[];for(let i=0;i<18;i++){const a=elite[Math.floor(Math.random()*elite.length)],b=elite[Math.floor(Math.random()*elite.length)];a.children++;b.children++;const child=creature(mixGenome(a.genome,b.genome),i,a.line,b.line);child.line=Math.random()<.5?a.line:b.line;if(Math.random()<.08)child.line=Math.floor(rand(0,9999));children.push(child);lineage.push({gen:generation+1,line:child.line,a:a.line,b:b.line,fit:(a.fitness+b.fitness)/2});}pop=children;generation++;simTime=0;selected=0;pinned=null;food=[.25,.46,.67].map(x=>({x,y:terrainAt(x)-.035,energy:55,active:true}));burst(W*beaconX,H*(terrainAt(beaconX)-.08),'#ffd166');beep(260,.08,.035);setTimeout(()=>beep(420,.08,.03),80);toast(`Generation ${generation}: beste Linie ${best.dist.toFixed(1)} m`);syncUI();drawChart();}
function burst(x,y,color){for(let i=0;i<14;i++)particles.push({x,y,vx:rand(45,-45),vy:rand(-15,-70),life:1,color});}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;p.life-=dt*1.8;}particles=particles.filter(p=>p.life>0);}
function draw(){ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#071c2d');grad.addColorStop(.55,'#092235');grad.addColorStop(1,'#06111b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(88,174,205,.08)';ctx.lineWidth=1;for(let x=0;x<W;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.fillStyle='#0a2630';ctx.beginPath();ctx.moveTo(0,H);for(let i=0;i<terrainN;i++)ctx.lineTo(i/(terrainN-1)*W,terrain[i]*H);ctx.lineTo(W,H);ctx.closePath();ctx.fill();ctx.strokeStyle='#2c6b70';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<terrainN;i++){const x=i/(terrainN-1)*W,y=terrain[i]*H;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();for(const f of food){if(!f.active)continue;const x=f.x*W,y=f.y*H;ctx.fillStyle='#8af0a5';ctx.beginPath();ctx.arc(x,y,4+Math.sin(performance.now()/160)*1.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(138,240,165,.35)';ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.stroke();}const bx=beaconX*W,by=(terrainAt(beaconX)-.08)*H;ctx.strokeStyle='#ffd166';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(bx,by,10+Math.sin(performance.now()/300)*2,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffd166';ctx.beginPath();ctx.arc(bx,by,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,209,102,.7)';ctx.font='8px system-ui';ctx.fillText('ZIEL',bx-9,by-15);const order=[...pop].sort((a,b)=>a.id===selected?1:b.id===selected?-1:0);for(const c of order)drawCreature(ctx,c,c.id===selected,c.id===pinned);for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);}ctx.globalAlpha=1;}
function jointPoint(c,leg,phaseOffset=0){const d=bodyDims(c),side=leg?1:-1,baseX=c.x*W+side*d.r*.45,baseY=c.y*H+d.r*.1;const act=neural(c,leg);const a=c.angle+side*(.62+act*.48)+phaseOffset;const knee={x:baseX+Math.sin(a)*d.l1,y:baseY+Math.cos(a)*d.l1};const b=a+side*(.55-c.genome.spring*.25)+act*.25;const foot={x:knee.x+Math.sin(b)*d.l2,y:knee.y+Math.cos(b)*d.l2};return {base:{x:baseX,y:baseY},knee,foot};}
function drawCreature(g,c,sel,pin){const d=bodyDims(c),cx=c.x*W,cy=c.y*H;g.save();g.lineCap='round';const col=!c.alive?'#ff6b6b':pin?'#ffd166':'#5ce1e6';for(let leg=0;leg<2;leg++){const j=jointPoint(c,leg);g.strokeStyle=col;g.lineWidth=3.2;g.beginPath();g.moveTo(j.base.x,j.base.y);g.lineTo(j.knee.x,j.knee.y);g.lineTo(j.foot.x,j.foot.y);g.stroke();g.strokeStyle='#b9d4df';g.lineWidth=1.6;g.beginPath();g.moveTo(j.foot.x-d.foot,j.foot.y);g.lineTo(j.foot.x+d.foot,j.foot.y);g.stroke();g.fillStyle='#d9f8ff';for(const q of [j.knee,j.foot]){g.beginPath();g.arc(q.x,q.y,2.4,0,Math.PI*2);g.fill();}}g.translate(cx,cy);g.rotate(c.angle);g.fillStyle=sel?'#173f55':'#102b3c';g.strokeStyle=col;g.lineWidth=sel?3:1.5;g.beginPath();g.ellipse(0,0,d.r*1.2,d.r*.72,0,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=col;g.beginPath();g.arc(d.r*.45,-2,2.4,0,Math.PI*2);g.fill();g.restore();if(sel){g.strokeStyle='rgba(255,255,255,.35)';g.setLineDash([3,4]);g.beginPath();g.arc(cx,cy,d.r*1.7,0,Math.PI*2);g.stroke();g.setLineDash([]);}}
function syncUI(){const c=pop[selected]||pop[0];ui.gen.textContent=generation;ui.pop.textContent=pop.filter(c=>c.alive).length+'/'+pop.length;const best=Math.max(...pop.map(c=>c.dist));ui.best.textContent=best.toFixed(1)+' m';ui.time.textContent=Math.max(0,30-simTime).toFixed(1)+' s';ui.name.textContent=`Linie ${String(c.line).padStart(4,'0')} · #${c.id+1}`;ui.dist.textContent=c.dist.toFixed(1)+' m';ui.energy.textContent=Math.round(c.energy)+'%';ui.child.textContent=c.children;ui.fit.textContent=c.fitness.toFixed(1);ui.pin.classList.toggle('pinned',pinned===c.id);ui.pin.textContent=pinned===c.id?'★ Zuchtfavorit':'☆ Zuchtfavorit';renderGenes(c);drawPreview(c);}
function renderGenes(c){const labels={body:'Körpermasse',legA:'Oberschenkel',legB:'Unterschenkel',foot:'Fußbreite',muscle:'Muskelkraft',spring:'Gelenkfeder',friction:'Fußreibung',metabolism:'Stoffwechsel',sense:'Zielsinn',freq:'Rhythmus',phase:'Phasenbias',balance:'Balance'};ui.genes.innerHTML=['body','legA','muscle','friction','sense','freq'].map(k=>{const v=c.genome[k],pct=clamp((k==='freq'?v/1.8:v/1.4)*100,4,100);return `<div class="gene"><span>${labels[k]}</span><strong>${v.toFixed(2)}</strong><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('');}
function drawPreview(c){const w=preview.clientWidth,h=preview.clientHeight;pctx.clearRect(0,0,w,h);const tx=c.x,ty=c.y;c.x=.5;c.y=.45;drawCreature(pctx,c,true,pinned===c.id);c.x=tx;c.y=ty;}
function drawChart(){const w=chart.clientWidth,h=chart.clientHeight;if(!w)return;cctx.clearRect(0,0,w,h);cctx.strokeStyle='#19394e';cctx.lineWidth=1;for(let i=1;i<4;i++){const y=i*h/4;cctx.beginPath();cctx.moveTo(0,y);cctx.lineTo(w,y);cctx.stroke();}const mode=$('.tab.active')?.dataset.chart||'fitness';if(mode==='fitness'){const vals=history.length?history:[{gen:1,best:0,avg:0}],max=Math.max(10,...vals.map(v=>v.best))*1.15;line(vals.map(v=>v.avg),'#5ce1e6',max);line(vals.map(v=>v.best),'#ffd166',max);ui.note.textContent='Türkis: Populationsmittel · Gold: beste Linie je Generation.';}else if(mode==='traits'){const keys=['body','legA','legB','muscle','friction','sense'];const cols=['#5ce1e6','#ffd166','#8af0a5','#ff8fab','#9b8cff','#f3a65a'];keys.forEach((k,idx)=>{const avg=pop.reduce((s,c)=>s+c.genome[k],0)/pop.length;const x=(idx+.5)*w/keys.length,bh=clamp(avg/1.6,0,1)*(h-30);cctx.fillStyle=cols[idx];cctx.fillRect(x-10,h-bh-17,20,bh);cctx.fillStyle='#9fb5c4';cctx.font='8px system-ui';cctx.textAlign='center';cctx.fillText(k,x,h-4);});ui.note.textContent='Aktuelle mittlere Genwerte; Veränderungen entstehen nur aus Selektion und Vererbung.';}else{const recent=lineage.slice(-36);const gens=[...new Set(recent.map(n=>n.gen))];for(const n of recent){const gx=gens.indexOf(n.gen),x=(gx+.5)*w/Math.max(gens.length,1),y=12+(n.line%13)/13*(h-24);cctx.fillStyle='#5ce1e6';cctx.beginPath();cctx.arc(x,y,2.2,0,Math.PI*2);cctx.fill();}ui.note.textContent='Punkte zeigen jüngste Abstammungslinien über mehrere Generationen.';}}
function line(values,color,max){const w=chart.clientWidth,h=chart.clientHeight;cctx.strokeStyle=color;cctx.lineWidth=2;cctx.beginPath();values.forEach((v,i)=>{const x=values.length===1?0:i/(values.length-1)*w,y=h-12-clamp(v/max,0,1)*(h-24);i?cctx.lineTo(x,y):cctx.moveTo(x,y)});cctx.stroke();}
let audioCtx=null;function beep(freq,dur,vol){if(!sound)return;try{audioCtx=audioCtx||new (AudioContext||webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur);}catch{}}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),1600);}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running&&speed>0){acc+=dt*speed;const fixed=1/60;let n=0;while(acc>=fixed&&n<12){physics(fixed);updateParticles(fixed);acc-=fixed;n++;}}draw();if((now|0)%8===0)syncUI();requestAnimationFrame(frame);}
function canvasPos(e){const r=sim.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)};}
let dragging=false;function interact(e){const p=canvasPos(e);if(tool==='raise'||tool==='lower'){const ci=Math.round(p.x*(terrainN-1)),dir=tool==='raise'?-1:1;for(let j=-4;j<=4;j++){const i=ci+j;if(i<2||i>=terrainN-2)continue;const fall=(1-Math.abs(j)/5);terrain[i]=clamp(terrain[i]+dir*.008*fall,.48,.9);}for(const f of food)f.y=terrainAt(f.x)-.035;}else if(tool==='food'){food.push({x:p.x,y:terrainAt(p.x)-.035,energy:55,active:true});if(food.length>8)food.shift();beep(520,.04,.02);}else if(tool==='beacon'){beaconX=clamp(p.x,.2,.95);beep(380,.05,.02);}else if(tool==='inspect'){let best=Infinity,idx=0;pop.forEach((c,i)=>{const dx=c.x-p.x,dy=c.y-p.y,d=dx*dx+dy*dy;if(d<best){best=d;idx=i;}});selected=idx;syncUI();}}
sim.addEventListener('pointerdown',e=>{dragging=true;sim.setPointerCapture(e.pointerId);interact(e);});sim.addEventListener('pointermove',e=>{if(dragging&&(tool==='raise'||tool==='lower'||tool==='inspect'))interact(e);});sim.addEventListener('pointerup',()=>dragging=false);sim.addEventListener('pointercancel',()=>dragging=false);
$$('.tool').forEach(b=>b.addEventListener('click',()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;ui.tool.textContent={raise:'Terrain anheben',lower:'Terrain absenken',food:'Energiekapsel setzen',beacon:'Ziel versetzen',inspect:'Kreatur auswählen'}[tool];beep(220,.03,.015);}));
$$('.speedBtn').forEach(b=>b.addEventListener('click',()=>{$$('.speedBtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const s=Number(b.dataset.speed);if(s===0){running=!running;b.textContent=running?'Ⅱ':'▶';speed=running?1:0;}else{running=true;speed=s;$$('.speedBtn')[0].textContent='Ⅱ';}}));
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawChart();}));
ui.pin.addEventListener('click',()=>{const c=pop[selected];pinned=pinned===c.id?null:c.id;syncUI();toast(pinned==null?'Zuchtfavorit entfernt':'Linie erhält bei Selektion eine Chance');});
$('#nextGen').addEventListener('click',evolve);$('#resetBtn').addEventListener('click',()=>{if(confirm('Evolution, Terrain und Statistik vollständig neu starten?'))initPop();});$('#soundBtn').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=sound?'🔊':'🔇';if(sound)beep(440,.04,.02);});
addEventListener('resize',resize,{passive:true});initTerrain();initPop();resize();requestAnimationFrame(frame);
})();