'use strict';
const $=id=>document.getElementById(id);
let bpm=100,bars=4,countIn=true,cleanRecord=true,headphoneMode=false,quantDivision=16,quantMode='grid',quantStrength=1;
let ctx=null,masterGain=null,compressor=null,micStream=null,micSource=null,analyser=null,processor=null,silentGain=null;
let tracks=[],transportRunning=false,epoch=0,recording=false,armed=false,captureStart=0,captureTarget=0,captureIndex=0,captureData=null,meterSmooth=0,lastBeat=-1,cleanMuted=false,trackSeq=1;
const loopDur=()=>bars*4*60/bpm, beatDur=()=>60/bpm, qKey=()=>(quantMode==='center'?'center':'grid'+quantDivision)+'@'+quantStrength.toFixed(3);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function setState(c,t){$('state').className=c||'';$('stateT').textContent=t}
function badge(live){$('badge').className='badge '+(live?'live':'ready');$('badge').textContent=live?'MIC AKTIV':'MIC AUS'}
function renderBars(){let el=$('barsSeg');el.innerHTML='';[1,2,4,8].forEach(n=>{let b=document.createElement('button');b.textContent=n;b.className=n===bars?'on':'';b.onclick=()=>{if(tracks.length||recording||armed)return toast('Spuren zuerst löschen');bars=n;$('barsV').textContent=n;renderBars();renderBeats()};el.appendChild(b)})}
function renderQ(){let el=$('quantSeg');el.innerHTML='';[4,8,16,'center'].forEach(n=>{let b=document.createElement('button');let isC=n==='center';b.textContent=isC?'ZENTRIEREN':'1/'+n;b.className=(isC?quantMode==='center':quantMode==='grid'&&n===quantDivision)?'on':'';b.onclick=async()=>{if(isC){if(quantMode==='center')return;quantMode='center'}else{if(quantMode==='grid'&&n===quantDivision)return;quantMode='grid';quantDivision=n}renderQ();updateQStatus();await reprocessEnabled()};el.appendChild(b)})}
function updateQStatus(){$('quantStatus').textContent=(quantMode==='center'?'ZENTRIEREN':'1/'+quantDivision)+' · '+Math.round(quantStrength*100)+'%';$('strengthV').textContent=Math.round(quantStrength*100)+'%'}
function renderBeats(){let el=$('beats');el.innerHTML='';for(let r=0;r<bars;r++){let row=document.createElement('div');row.className='bar';let no=document.createElement('div');no.className='barN';no.textContent=r+1;row.appendChild(no);for(let j=0;j<4;j++){let c=document.createElement('div');c.className='beat';row.appendChild(c)}el.appendChild(row)}}
async function init(){ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();masterGain=ctx.createGain();masterGain.gain.value=1.45;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-5;compressor.knee.value=8;compressor.ratio.value=6;compressor.attack.value=.003;compressor.release.value=.18;masterGain.connect(compressor);compressor.connect(ctx.destination);$('ov').classList.add('hide');badge(false);requestAnimationFrame(frame)}
function buttons(){let has=tracks.length>0;$('rec').disabled=has||recording||armed;$('newTrack').disabled=!has||recording||armed;$('play').disabled=!has||recording||armed;$('clear').disabled=!has&&!recording&&!armed;$('save').disabled=!has;$('playT').textContent=transportRunning?'STOP':'PLAY';$('playI').textContent=transportRunning?'■':'▶'}
function stopTrackSource(t){if(t.source){try{t.source.stop()}catch(e){}try{t.source.disconnect()}catch(e){}t.source=null}}
function activeBuffer(t){return t.quantEnabled&&t.quantBuffer?t.quantBuffer:t.originalBuffer}
function phase(){if(!transportRunning||!tracks.length)return 0;let d=loopDur(),p=(ctx.currentTime-epoch)%d;return p<0?p+d:p}
function startTrack(t,when,off=0){stopTrackSource(t);let s=ctx.createBufferSource();s.buffer=activeBuffer(t);s.loop=true;let g=t.gainNode||(t.gainNode=ctx.createGain());g.gain.value=t.muted?0:t.volume;s.connect(g);if(!g._connected){g.connect(masterGain);g._connected=true}s.start(when,off);t.source=s}
function startAll(when,off=0){tracks.forEach(t=>startTrack(t,when,off));epoch=when-off;transportRunning=true;setState('playState','Loop läuft');buttons()}
function stopAll(){tracks.forEach(stopTrackSource);transportRunning=false;setState('','Gestoppt');buttons()}
function restartOne(t){if(!transportRunning)return;let p=phase(),w=ctx.currentTime+.025;startTrack(t,w,p)}
function setCleanMute(on){if(!masterGain)return;cleanMuted=on;let v=on?0:(+$('master').value/100);masterGain.gain.cancelScheduledValues(ctx.currentTime);masterGain.gain.setTargetAtTime(v,ctx.currentTime,.015)}
async function openMic(){micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:!headphoneMode,noiseSuppression:false,autoGainControl:false,channelCount:1}});micSource=ctx.createMediaStreamSource(micStream);analyser=ctx.createAnalyser();analyser.fftSize=1024;micSource.connect(analyser);processor=ctx.createScriptProcessor(1024,1,1);silentGain=ctx.createGain();silentGain.gain.value=0;micSource.connect(processor);processor.connect(silentGain);silentGain.connect(ctx.destination);processor.onaudioprocess=onAudio;badge(true)}
function closeMic(){if(processor){processor.onaudioprocess=null;try{processor.disconnect()}catch(e){}}if(micSource){try{micSource.disconnect()}catch(e){}}if(silentGain){try{silentGain.disconnect()}catch(e){}}if(micStream){micStream.getTracks().forEach(t=>t.stop())}micStream=micSource=analyser=processor=silentGain=null;badge(false);$('db').textContent='MIC AUS';$('fill').style.width='0%'}
function onAudio(e){if(!recording||!captureData)return;let a=e.inputBuffer.getChannelData(0),sr=e.inputBuffer.sampleRate,t=e.playbackTime||ctx.currentTime;for(let i=0;i<a.length&&captureIndex<captureTarget;i++){if(t+i/sr<captureStart)continue;captureData[captureIndex++]=a[i]}if(captureIndex>=captureTarget){recording=false;armed=false;let d=captureData;captureData=null;setTimeout(()=>finishRecording(d),0)}}
function click(t,strong){let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=strong?1180:820;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(strong?.19:.11,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.05);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.06)}
function nextBoundaryAfter(t){let d=loopDur(),n=epoch;if(!transportRunning)return t;while(n<t)n+=d;return n}
