function clearAll(){closeMic();tracks.forEach(stopTrackSource);tracks=[];transportRunning=false;recording=armed=false;captureData=null;setCleanMute(false);setState('','Bereit');$('timer').textContent='00:00.0';$('pos').textContent='—';renderTracks();buttons();document.querySelectorAll('.beat').forEach(x=>x.className='beat')}
function meter(){if(!analyser){meterSmooth*=.8;$('fill').style.width=meterSmooth+'%';return}let a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);let s=0;for(let v of a)s+=v*v;let rms=Math.sqrt(s/a.length),db=rms?20*Math.log10(rms):-100,p=Math.max(0,Math.min(100,(db+60)/60*100));meterSmooth=meterSmooth*.75+p*.25;$('fill').style.width=meterSmooth+'%';$('db').textContent=db<-60?'−∞ dB':db.toFixed(1)+' dB'}
function visuals(){if(!ctx)return;let p=recording?Math.max(0,ctx.currentTime-captureStart):(transportRunning?phase():-1);if(p<0)return;let mi=Math.floor(p/60),se=Math.floor(p%60),te=Math.floor(p%1*10);$('timer').textContent=String(mi).padStart(2,'0')+':'+String(se).padStart(2,'0')+'.'+te;let bi=Math.min(bars*4-1,Math.floor((p%loopDur())/beatDur())),ba=Math.floor(bi/4),bb=bi%4;$('pos').textContent='Takt '+(ba+1)+'/'+bars+' · Beat '+(bb+1)+'/4';if(bi!==lastBeat){lastBeat=bi;document.querySelectorAll('.beat').forEach((x,i)=>{x.classList.toggle('past',i<=bi);x.classList.toggle('now',i===bi)})}}
function frame(){meter();visuals();requestAnimationFrame(frame)}
function wavBlob(){let rate=44100,n=Math.round(loopDur()*rate),mix=new Float32Array(n),active=tracks.filter(t=>!t.muted);for(let t of active){let b=activeBuffer(t),a=b.getChannelData(0),r=b.sampleRate/rate;for(let i=0;i<n;i++){let p=i*r,j=Math.floor(p),f=p-j,v=(a[j]||0)*(1-f)+(a[Math.min(j+1,a.length-1)]||0)*f;mix[i]+=v*t.volume}}let m=+$('master').value/100,pk=0;for(let i=0;i<n;i++){mix[i]*=m;pk=Math.max(pk,Math.abs(mix[i]))}if(pk>.98){let s=.98/pk;for(let i=0;i<n;i++)mix[i]*=s}let ab=new ArrayBuffer(44+n*4),v=new DataView(ab),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+n*4,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,rate,true);v.setUint32(28,rate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,n*4,true);let o=44;for(let i=0;i<n;i++){let s=Math.max(-1,Math.min(1,mix[i])),q=s<0?s*32768:s*32767;v.setInt16(o,q,true);v.setInt16(o+2,q,true);o+=4}return new Blob([v],{type:'audio/wav'})}
async function save(){let blob=wavBlob(),file=new File([blob],`TouchLoop_${bpm}BPM_${bars}bars.wav`,{type:'audio/wav'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return await navigator.share({title:'TouchLoop 6',files:[file]})}catch(e){if(e.name==='AbortError')return}let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
$('start').onclick=init;$('rec').onclick=()=>armRecord(true);$('newTrack').onclick=()=>armRecord(false);$('play').onclick=()=>transportRunning?stopAll():startAll(ctx.currentTime+.04,0);$('clear').onclick=clearAll;$('save').onclick=save;
$('bpm').oninput=e=>{if(tracks.length){e.target.value=bpm;return toast('Spuren zuerst löschen')}bpm=+e.target.value;$('bpmV').textContent=bpm};$('minus').onclick=()=>{if(!tracks.length&&bpm>50){bpm--;$('bpm').value=bpm;$('bpmV').textContent=bpm}};$('plus').onclick=()=>{if(!tracks.length&&bpm<180){bpm++;$('bpm').value=bpm;$('bpmV').textContent=bpm}};
$('count').onclick=()=>{countIn=!countIn;$('count').classList.toggle('on',countIn);$('count').textContent=countIn?'1 Takt Count-in':'Count-in aus'};$('clean').onclick=()=>{cleanRecord=!cleanRecord;$('clean').classList.toggle('on',cleanRecord);$('clean').textContent=cleanRecord?'✓ Clean Record':'Clean Record aus'};$('phones').onclick=()=>{headphoneMode=!headphoneMode;$('phones').classList.toggle('on',headphoneMode);$('phones').textContent=headphoneMode?'✓ Kopfhörer-Modus':'Kopfhörer-Modus'};
$('master').oninput=e=>{let v=+e.target.value/100;$('masterV').textContent=Math.round(v*100)+'%';if(masterGain&&!cleanMuted)masterGain.gain.setTargetAtTime(v,ctx.currentTime,.01)};
$('quantStrength').oninput=e=>{quantStrength=+e.target.value/100;updateQStatus()};$('quantStrength').onchange=()=>reprocessEnabled();
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&ctx&&ctx.state==='suspended')try{await ctx.resume()}catch(e){}});
renderBars();renderQ();renderBeats();renderTracks();updateQStatus();buttons();
