'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'),ctx=canvas.getContext('2d'),chart=$('#chart'),cctx=chart.getContext('2d');
const W=800,H=800,COLS=['#95f0a9','#f4c86a','#7bd9d8','#ff8b78'];
let running=false,speed=1,tool='inspect',sound=true,audio=null,tick=0,score=0,maxGen=1,selected=null,barriers=[],raindrops=[],predators=[];
let ants=[],eggs=[],foods=[],colonies=[],history=[],popHistory=[],pherA,pherB,gridN=50,cell=W/gridN,lastFrame=performance.now(),acc=0,goalIndex=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a=1,b=0)=>b+Math.random()*(a-b),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const genes=['trailSense','trailDeposit','explore','aggression','nurseBias','memory','metabolism'];
const goals=[
 {title:'Experiment 1: Signalwege',text:'Eine Kolonie soll ≥ 35 Arbeiter und ≥ 220 Nahrungsvorrat erreichen.',test:()=>colonies.some(c=>alive(c.id)>=35&&c.food>220),p:()=>Math.max(...colonies.map(c=>Math.min(1,(alive(c.id)/35+c.food/220)/2)))},
 {title:'Experiment 2: Sozialer Druck',text:'Erzeuge genetische Divergenz von mindestens 28%.',test:()=>divergence()>=.28,p:()=>divergence()/.28},
 {title:'Experiment 3: Neue Linie',text:'Beobachte die Gründung einer Kolonie der Generation 2.',test:()=>maxGen>=2,p:()=>maxGen>=2?1:Math.min(1,Math.max(...colonies.map(c=>c.food))/480)},
 {title:'Experiment 4: Koexistenz',text:'Halte mindestens 3 Kolonien mit je 20 Ameisen gleichzeitig am Leben.',test:()=>colonies.filter(c=>alive(c.id)>=20).length>=3,p:()=>colonies.filter(c=>alive(c.id)>=20).length/3}
];
function genome(base=null,m=.08){const g={};for(const k of genes){const v=base?base[k]:rnd(.75,.25);g[k]=clamp(v+(Math.random()*2-1)*m,0,1)}return g}
function recombine(a,b){const g={};for(const k of genes)g[k]=clamp((Math.random()<.5?a[k]:b[k])+(Math.random()*2-1)*.06,0,1);return g}
function init(){tick=score=0;maxGen=1;selected=null;ants=[];eggs=[];foods=[];colonies=[];history=[];barriers=[];raindrops=[];predators=[];popHistory=[];goalIndex=0;pherA=new Float32Array(gridN*gridN);pherB=new Float32Array(gridN*gridN);const nests=[[150,180],[650,180],[400,650]];nests.forEach((p,i)=>newColony(p[0],p[1],genome(),1,null,i));for(let i=0;i<15;i++)addFood(rnd(730,70),rnd(730,70),rnd(80,40));renderUI()}
function newColony(x,y,g,generation,parent,colorIndex){const id=Date.now()+Math.random();const c={id,x,y,g,generation,parent,food:160,brood:0,born:tick,color:COLS[colorIndex%COLS.length],name:'Linie '+String.fromCharCode(65+history.length%26)+(generation>1?generation:''),father:null};colonies.push(c);history.unshift({id,name:c.name,generation,parent,born:tick,g:{...g},color:c.color});for(let i=0;i<16;i++)spawnAnt(c,i<2?'nurse':'worker');spawnAnt(c,'queen');maxGen=Math.max(maxGen,generation);tone(280+generation*35,.04);return c}
function spawnAnt(c,caste='worker',g=null){const a={id:Math.random(),col:c.id,x:c.x+rnd(18,-18),y:c.y+rnd(18,-18),vx:0,vy:0,ang:rnd(Math.PI*2),energy:rnd(1,.75),age:0,caste,g:g||genome(c.g,.025),carry:0,state:caste==='nurse'?'nurse':'explore',memory:[],target:null};ants.push(a);return a}
function layEgg(c){if(c.food<10||eggs.length>110)return;c.food-=8;eggs.push({col:c.id,x:c.x+rnd(11,-11),y:c.y+rnd(11,-11),age:0,g:genome(c.g,.018)})}
function alive(id){return ants.reduce((n,a)=>n+(a.col===id?1:0),0)}
function addFood(x,y,amt=70){foods.push({x,y,amt,max:amt,r:10+Math.sqrt(amt)*.7})}
function field(arr,x,y){const gx=clamp(Math.floor(x/cell),0,gridN-1),gy=clamp(Math.floor(y/cell),0,gridN-1);return arr[gy*gridN+gx]}
function deposit(arr,x,y,v){const gx=clamp(Math.floor(x/cell),0,gridN-1),gy=clamp(Math.floor(y/cell),0,gridN-1);arr[gy*gridN+gx]=clamp(arr[gy*gridN+gx]+v,0,3)}
function grad(arr,x,y){const e=cell;return{x:field(arr,x+e,y)-field(arr,x-e,y),y:field(arr,x,y+e)-field(arr,x,y-e)}}
function collideBarrier(a){for(const b of barriers){const ax=a.x-b.x1,ay=a.y-b.y1,bx=b.x2-b.x1,by=b.y2-b.y1;const t=clamp((ax*bx+ay*by)/(bx*bx+by*by||1),0,1),px=b.x1+t*bx,py=b.y1+t*by,dx=a.x-px,dy=a.y-py,d=Math.hypot(dx,dy);if(d<10){a.x=px+dx/(d||1)*11;a.y=py+dy/(d||1)*11;a.ang+=Math.PI*.7}}}
function stepAnt(a,dt){const c=colonies.find(c=>c.id===a.col);if(!c){a.energy=0;return}a.age+=dt;a.energy-=dt*(.0012+.0022*a.g.metabolism);if(a.age>1500||a.energy<=0)return;const dxn=c.x-a.x,dyn=c.y-a.y,dn=Math.hypot(dxn,dyn);let turn=(Math.random()-.5)*(.28+.5*a.g.explore);if(a.caste==='queen'){a.x=c.x;a.y=c.y;a.energy=1;return}if(a.state==='nurse'){const nearEgg=eggs.find(e=>e.col===c.id&&Math.hypot(e.x-a.x,e.y-a.y)<70);if(nearEgg){const an=Math.atan2(nearEgg.y-a.y,nearEgg.x-a.x);turn+=angleDiff(a.ang,an)*.18;nearEgg.age+=dt*(.022+.055*a.g.nurseBias)}else if(dn>35)turn+=angleDiff(a.ang,Math.atan2(dyn,dxn))*.22;if(a.age>240&&Math.random()<.002)a.state='explore'}else if(a.carry>0){turn+=angleDiff(a.ang,Math.atan2(dyn,dxn))*(.12+.32*a.g.memory);deposit(pherB,a.x,a.y,.02*a.g.trailDeposit);if(dn<24){c.food+=a.carry;a.carry=0;a.energy=clamp(a.energy+.22,0,1);a.state=Math.random()<a.g.nurseBias*.2?'nurse':'explore';score+=2}}else{let nearest=null,nd=80+150*a.g.trailSense;for(const f of foods){const d=Math.hypot(f.x-a.x,f.y-a.y);if(f.amt>0&&d<nd){nd=d;nearest=f}}if(nearest){turn+=angleDiff(a.ang,Math.atan2(nearest.y-a.y,nearest.x-a.x))*(.09+.25*a.g.trailSense);if(nd<nearest.r+5){const q=Math.min(5,nearest.amt);nearest.amt-=q;a.carry=q;a.state='return';deposit(pherA,a.x,a.y,.16*a.g.trailDeposit);tone(520,.012)}}else{const gr=grad(pherA,a.x,a.y);if(Math.hypot(gr.x,gr.y)>.015)turn+=angleDiff(a.ang,Math.atan2(gr.y,gr.x))*.22*a.g.trailSense;deposit(pherB,a.x,a.y,.008*a.g.trailDeposit)}}for(const o of ants){if(o===a||o.col===a.col||o.energy<=0)continue;const d=Math.hypot(o.x-a.x,o.y-a.y);if(d<38&&a.g.aggression>.48){turn+=angleDiff(a.ang,Math.atan2(o.y-a.y,o.x-a.x))*.2*a.g.aggression;if(d<8&&Math.random()<.02*a.g.aggression){o.energy-=.08*a.g.aggression;a.energy-=.025}}}for(const p of predators){const d=Math.hypot(p.x-a.x,p.y-a.y);if(d<90){turn+=angleDiff(a.ang,Math.atan2(a.y-p.y,a.x-p.x))*.5;if(d<14&&Math.random()<.08)a.energy=0}}a.ang+=turn;const sp=(.7+1.5*a.g.metabolism)*(a.carry?0.82:1);a.vx=Math.cos(a.ang)*sp;a.vy=Math.sin(a.ang)*sp;a.x+=a.vx*dt;a.y+=a.vy*dt;a.x=clamp(a.x,5,W-5);a.y=clamp(a.y,5,H-5);if(a.x===5||a.x===W-5||a.y===5||a.y===H-5)a.ang+=Math.PI*.75;collideBarrier(a)}
function angleDiff(a,b){let d=b-a;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d}
function simStep(dt){tick+=dt;for(let i=0;i<pherA.length;i++){pherA[i]*=.9975;pherB[i]*=.997}for(const r of raindrops){r.life-=dt;for(let y=Math.max(0,Math.floor((r.y-r.r)/cell));y<Math.min(gridN,Math.ceil((r.y+r.r)/cell));y++)for(let x=Math.max(0,Math.floor((r.x-r.r)/cell));x<Math.min(gridN,Math.ceil((r.x+r.r)/cell));x++){const px=(x+.5)*cell,py=(y+.5)*cell;if(Math.hypot(px-r.x,py-r.y)<r.r){pherA[y*gridN+x]*=.90;pherB[y*gridN+x]*=.90}}}raindrops=raindrops.filter(r=>r.life>0);for(const p of predators){p.x+=Math.cos(p.ang)*1.2*dt;p.y+=Math.sin(p.ang)*1.2*dt;if(Math.random()<.03)p.ang+=rnd(1,-1);if(p.x<10||p.x>W-10)p.ang=Math.PI-p.ang;if(p.y<10||p.y>H-10)p.ang=-p.ang;p.life-=dt}predators=predators.filter(p=>p.life>0);ants.forEach(a=>stepAnt(a,dt));ants=ants.filter(a=>a.energy>0);for(const e of eggs)e.age+=dt*.012;for(let i=eggs.length-1;i>=0;i--)if(eggs[i].age>10){const e=eggs.splice(i,1)[0],c=colonies.find(c=>c.id===e.col);if(c)spawnAnt(c,Math.random()<c.g.nurseBias*.22?'nurse':'worker',e.g)}if(Math.floor(tick)%8===0&&Math.floor(tick-dt)%8!==Math.floor(tick)){for(const c of colonies){if(alive(c.id)<70)layEgg(c);if(c.food>500&&alive(c.id)>38&&colonies.length<6&&tick-c.born>260)foundDaughter(c)}}foods=foods.filter(f=>f.amt>.2);if(Math.random()<.002&&foods.length<22)addFood(rnd(750,50),rnd(750,50),rnd(70,30));if(Math.floor(tick)%20===0&&Math.floor(tick-dt)%20!==Math.floor(tick))popHistory.push({t:tick,v:colonies.map(c=>alive(c.id))});if(popHistory.length>90)popHistory.shift();checkGoals();renderUI()}
function foundDaughter(parent){const partner=colonies.filter(c=>c.id!==parent.id&&alive(c.id)>8).sort(()=>Math.random()-.5)[0]||parent;let pt=null;for(let tries=0;tries<20;tries++){const p={x:rnd(710,90),y:rnd(710,90)};if(colonies.every(c=>dist(p,c)>135)){pt=p;break}}if(!pt)return;parent.food-=260;partner.food=Math.max(0,partner.food-40);const g=recombine(parent.g,partner.g);const c=newColony(pt.x,pt.y,g,parent.generation+1,parent.id,history.length);c.father=partner.id;toast('Neue Kolonie gegründet — Genom rekombiniert');score+=150*parent.generation}
function divergence(){if(colonies.length<2)return 0;let sum=0,n=0;for(let i=0;i<colonies.length;i++)for(let j=i+1;j<colonies.length;j++){for(const k of genes)sum+=Math.abs(colonies[i].g[k]-colonies[j].g[k]);n+=genes.length}return n?sum/n:0}
function checkGoals(){if(goalIndex>=goals.length)return;const g=goals[goalIndex];$('#goalBar').style.width=(clamp(g.p(),0,1)*100).toFixed(0)+'%';if(g.test()){score+=300+goalIndex*200;toast('Forschungsziel abgeschlossen +'+(300+goalIndex*200));goalIndex++;if(goalIndex<goals.length){$('#goalTitle').textContent=goals[goalIndex].title;$('#goalText').textContent=goals[goalIndex].text}else{$('#goalTitle').textContent='Freie Forschung';$('#goalText').textContent='Alle Experimente abgeschlossen — beobachte die weitere Koevolution.';$('#goalBar').style.width='100%';localStorage.setItem('signalNestBest',String(Math.max(score,+(localStorage.getItem('signalNestBest')||0))))}}}
function render(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#09140f';ctx.fillRect(0,0,W,H);drawField();for(const b of barriers){ctx.strokeStyle='#728478';ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(b.x1,b.y1);ctx.lineTo(b.x2,b.y2);ctx.stroke()}for(const f of foods){ctx.fillStyle='#d6df79';ctx.globalAlpha=.24;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#e9ee9e';ctx.beginPath();ctx.arc(f.x,f.y,Math.max(3,f.r*Math.sqrt(f.amt/f.max)*.55),0,Math.PI*2);ctx.fill()}for(const c of colonies){ctx.strokeStyle=c.color;ctx.fillStyle='#0a110d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(c.x,c.y,25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=.18;ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(c.x,c.y,40+Math.min(25,alive(c.id)*.35),0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}for(const e of eggs){const c=colonies.find(c=>c.id===e.col);ctx.fillStyle=c?c.color:'#fff';ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(e.x,e.y,2.8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}for(const a of ants){const c=colonies.find(c=>c.id===a.col);if(!c)continue;ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.ang);ctx.fillStyle=c.color;if(a.caste==='queen'){ctx.rotate(Math.PI/4);ctx.fillRect(-5,-5,10,10)}else{ctx.beginPath();ctx.ellipse(0,0,a.carry?4.5:3.5,2.2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6df79';if(a.carry){ctx.beginPath();ctx.arc(5,0,2.2,0,Math.PI*2);ctx.fill()}}ctx.restore()}for(const r of raindrops){ctx.strokeStyle='rgba(123,217,216,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,r.r*(1-r.life/55*.3),0,Math.PI*2);ctx.stroke()}for(const p of predators){ctx.fillStyle='#ff8b78';ctx.beginPath();ctx.moveTo(p.x+10,p.y);ctx.lineTo(p.x-8,p.y-7);ctx.lineTo(p.x-5,p.y+8);ctx.closePath();ctx.fill()}}
function drawField(){ctx.save();ctx.globalCompositeOperation='lighter';for(let y=0;y<gridN;y+=2)for(let x=0;x<gridN;x+=2){const i=y*gridN+x,a=pherA[i],b=pherB[i];if(a>.03){ctx.fillStyle=`rgba(149,240,169,${Math.min(.16,a*.08)})`;ctx.fillRect(x*cell,y*cell,cell*2,cell*2)}if(b>.03){ctx.fillStyle=`rgba(123,217,216,${Math.min(.12,b*.055)})`;ctx.fillRect(x*cell,y*cell,cell*2,cell*2)}}ctx.restore()}
function renderUI(){if(!colonies.length)return;$('#popStat').textContent=ants.length;$('#genStat').textContent=maxGen;$('#divStat').textContent=Math.round(divergence()*100)+'%';$('#scoreStat').textContent=score;$('#colonyCards').innerHTML=colonies.map(c=>`<div class="colCard"><h3><i class="dot" style="background:${c.color}"></i>${c.name} · G${c.generation}</h3><div class="kv"><span>Population</span><b>${alive(c.id)}</b></div><div class="kv"><span>Nahrung</span><b>${Math.round(c.food)}</b></div><div class="kv"><span>Brut</span><b>${eggs.filter(e=>e.col===c.id).length}</b></div><div class="traits">${[['Signal',c.g.trailSense],['Abgabe',c.g.trailDeposit],['Erkundung',c.g.explore],['Aggression',c.g.aggression],['Pflege',c.g.nurseBias]].map(([n,v])=>`<div class="trait"><span>${n}</span><div class="miniBar"><i style="width:${v*100}%;color:${c.color}"></i></div><b>${Math.round(v*100)}</b></div>`).join('')}</div></div>`).join('');$('#lineageHistory').innerHTML=history.slice(0,14).map(h=>`<div class="lineage"><b style="color:${h.color}">${h.name} · Generation ${h.generation}</b><small>${h.parent?'Tochterlinie durch Rekombination':'Gründerlinie'}</small><small>Signal ${Math.round(h.g.trailSense*100)} · Exploration ${Math.round(h.g.explore*100)} · Pflege ${Math.round(h.g.nurseBias*100)}</small></div>`).join('');drawChart()}
function drawChart(){const w=chart.width,h=chart.height;cctx.clearRect(0,0,w,h);cctx.strokeStyle='#20362a';cctx.lineWidth=1;for(let y=25;y<h;y+=30){cctx.beginPath();cctx.moveTo(0,y);cctx.lineTo(w,y);cctx.stroke()}if(popHistory.length<2)return;const max=Math.max(20,...popHistory.flatMap(p=>p.v));for(let ci=0;ci<Math.min(4,colonies.length);ci++){cctx.strokeStyle=colonies[ci].color;cctx.lineWidth=2;cctx.beginPath();popHistory.forEach((p,i)=>{const x=i/(popHistory.length-1)*w,y=h-8-(p.v[ci]||0)/max*(h-18);i?cctx.lineTo(x,y):cctx.moveTo(x,y)});cctx.stroke()}}
function loop(now){const dt=Math.min(40,now-lastFrame);lastFrame=now;if(running){acc+=dt*speed;while(acc>=16){simStep(.6);acc-=16}}render();requestAnimationFrame(loop)}
function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
let dragStart=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);dragStart=canvasPos(e);if(tool!=='barrier')actAt(dragStart)});canvas.addEventListener('pointerup',e=>{if(tool==='barrier'&&dragStart){const p=canvasPos(e);if(Math.hypot(p.x-dragStart.x,p.y-dragStart.y)>20){barriers.push({x1:dragStart.x,y1:dragStart.y,x2:p.x,y2:p.y});tone(180,.04)}else toast('Für eine Barriere über die Welt ziehen.')}dragStart=null});
function actAt(p){if(tool==='food'){addFood(p.x,p.y,110);score=Math.max(0,score-4);tone(440,.03)}else if(tool==='rain'){raindrops.push({x:p.x,y:p.y,r:100,life:55});tone(230,.08)}else if(tool==='predator'){predators.push({x:p.x,y:p.y,ang:rnd(Math.PI*2),life:240});tone(110,.12)}else inspectAt(p)}
function inspectAt(p){let best=null,bd=26;for(const a of ants){const d=Math.hypot(a.x-p.x,a.y-p.y);if(d<bd){best=a;bd=d}}if(best){selected=best;const c=colonies.find(c=>c.id===best.col);$('#inspector').innerHTML=`<strong style="color:${c.color}">${best.caste==='queen'?'Königin':'Ameise'} · ${c.name}</strong><br>Status: ${best.state} · Energie ${Math.round(best.energy*100)}%<br>Signal ${Math.round(best.g.trailSense*100)} · Abgabe ${Math.round(best.g.trailDeposit*100)} · Exploration ${Math.round(best.g.explore*100)} · Aggression ${Math.round(best.g.aggression*100)} · Pflege ${Math.round(best.g.nurseBias*100)}`;return}for(const c of colonies){if(Math.hypot(c.x-p.x,c.y-p.y)<50){$('#inspector').innerHTML=`<strong style="color:${c.color}">${c.name} · Generation ${c.generation}</strong><br>${alive(c.id)} Tiere · ${Math.round(c.food)} Nahrung<br>Koloniegenom: Signal ${Math.round(c.g.trailSense*100)} · Exploration ${Math.round(c.g.explore*100)} · Pflege ${Math.round(c.g.nurseBias*100)}`;return}}$('#inspector').innerHTML='<strong>Kein Organismus gewählt</strong><br>Tippe näher an eine Ameise oder ein Nest.'}
$$('.tool').forEach(b=>b.addEventListener('click',()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;toast(tool==='barrier'?'Ziehe eine Linie für eine Barriere.':'Werkzeug: '+b.textContent.trim())}));
$$('.speed').forEach(b=>b.addEventListener('click',()=>{$$('.speed').forEach(x=>x.classList.remove('active'));b.classList.add('active');speed=+b.dataset.speed}));$('#pauseBtn').addEventListener('click',()=>{running=!running;$('#pauseBtn').textContent=running?'Ⅱ':'▶';tone(320,.03)});$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab+'Panel').classList.add('active')}));$('#resetBtn').addEventListener('click',()=>{init();toast('Experiment zurückgesetzt')});$('#soundBtn').addEventListener('click',()=>{sound=!sound;$('#soundBtn').textContent='Sound: '+(sound?'an':'aus');if(sound)tone(420,.04)});$('#startBtn').addEventListener('click',()=>{$('#intro').classList.remove('show');running=true;ensureAudio();tone(360,.07)});
function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)()}
function tone(freq,dur){if(!sound)return;try{ensureAudio();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch(e){}}
let toastTimer;function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1400)}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
init();requestAnimationFrame(loop);