function renderTracks(){
 let el=$('tracks');$('trackCount').textContent=tracks.length+' '+(tracks.length===1?'Spur':'Spuren');
 if(!tracks.length){el.innerHTML='<div class="tracksEmpty">Noch keine Aufnahme</div>';return}
 el.innerHTML='';
 tracks.forEach(t=>{
  let d=document.createElement('div');d.className='track',analyzed=t.analysisDone?(t.eventCount+' Klangblöcke erkannt'):'Noch nicht analysiert';
  let status=t.processing?'Klangblöcke werden einmalig analysiert…':(t.mode==='original'?'Originalaufnahme aktiv':modeLabel(t.mode)+' · '+Math.round(t.strength*100)+'% · '+analyzed);
  d.innerHTML='<div class="trackTop"><div><div class="trackName">'+t.name+'</div><div class="trackMeta">'+(t.mode==='original'?'ORIGINAL':'TIMING KORRIGIERT')+'</div></div><button class="tiny '+(!t.muted?'playing':'')+'" data-act="mute">'+(t.muted?'▶':'Ⅱ')+'</button><button class="tiny del" data-act="del">×</button></div>'+
  '<div class="wave">'+waveform(activeBuffer(t))+'</div>'+
  '<div class="volRow"><span>LAUTST.</span><input class="range" data-act="vol" type="range" min="0" max="150" value="'+Math.round(t.volume*100)+'"><span>'+Math.round(t.volume*100)+'%</span></div>'+
  '<div class="timingBox"><div class="timingTitle"><b>TIMING DIESER SPUR</b><span class="timingStatus">'+status+'</span></div><div class="modeSeg">'+
  ['original','q4','q8','q16','center'].map(m=>'<button class="modeBtn '+(m==='original'?'original ':'')+(t.mode===m?'on':'')+'" data-mode="'+m+'">'+modeLabel(m).toUpperCase()+'</button>').join('')+
  '</div><div class="strengthRow '+(t.mode==='original'?'disabled':'')+'"><span>STÄRKE</span><input class="range" data-act="strength" type="range" min="0" max="100" value="'+Math.round(t.strength*100)+'" '+(t.mode==='original'?'disabled':'')+'><span>'+Math.round(t.strength*100)+'%</span></div>'+
  '<div class="analysisInfo">'+(t.analysisDone?'Analyse gespeichert · Umschalten benötigt keine neue Klang-Erkennung.':'Beim ersten Korrekturmodus wird diese Spur einmal analysiert. Ganze Wörter/Töne bleiben zusammen.')+'</div>'+
  (t.processing?'<div class="progress"><span style="width:'+Math.round(t.progress*100)+'%"></span></div><div class="progressText">'+Math.round(t.progress*100)+'%</div>':'')+'</div>';
  d.querySelector('[data-act=mute]').onclick=()=>{t.muted=!t.muted;if(t.gainNode)t.gainNode.gain.setTargetAtTime(t.muted?0:t.volume,ctx.currentTime,.01);renderTracks()};
  d.querySelector('[data-act=del]').onclick=()=>{stopTrackSource(t);tracks=tracks.filter(x=>x!==t);if(!tracks.length)stopAll();renderTracks();buttons()};
  let vr=d.querySelector('[data-act=vol]');vr.oninput=e=>{t.volume=+e.target.value/100;if(t.gainNode&&!t.muted)t.gainNode.gain.setTargetAtTime(t.volume,ctx.currentTime,.01);e.target.nextElementSibling.textContent=Math.round(t.volume*100)+'%'};
  d.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setTrackMode(t,b.dataset.mode));
  let sr=d.querySelector('[data-act=strength]');if(sr)sr.oninput=e=>{let v=+e.target.value/100;e.target.nextElementSibling.textContent=Math.round(v*100)+'%';scheduleStrength(t,v)};
  el.appendChild(d)
 })
}
function clearAll(){closeMic();tracks.forEach(stopTrackSource);tracks=[];transportRunning=false;recording=armed=false;captureData=null;setCleanMute(false);setState('','Bereit');$('timer').textContent='00:00.0';$('pos').textContent='—';renderTracks();buttons();document.querySelectorAll('.beat').forEach(x=>x.className='beat')}
function meter(){if(!analyser){meterSmooth*=.8;$('fill').style.width=meterSmooth+'%';return}let a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);let s=0;for(let v of a)s+=v*v;let rms=Math.sqrt(s/a.length),db=rms?20*Math.log10(rms):-100,p=Math.max(0,Math.min(100,(db+60)/60*100));meterSmooth=meterSmooth*.75+p*.25;$('fill').style.width=meterSmooth+'%';$('db').textContent=db<-60?'−∞ dB':db.toFixed(1)+' dB'}
function visuals(){if(!ctx)return;let p=recording?Math.max(0,ctx.currentTime-captureStart):(transportRunning?phase():-1);if(p<0)return;let mi=Math.floor(p/60),se=Math.floor(p%60),te=Math.floor(p%1*10);$('timer').textContent=String(mi).padStart(2,'0')+':'+String(se).padStart(2,'0')+'.'+te;let bi=Math.min(bars*4-1,Math.floor((p%loopDur())/beatDur())),ba=Math.floor(bi/4),bb=bi%4;$('pos').textContent='Takt '+(ba+1)+'/'+bars+' · Beat '+(bb+1)+'/4';if(bi!==lastBeat){lastBeat=bi;document.querySelectorAll('.beat').forEach((x,i)=>{x.classList.toggle('past',i<=bi);x.classList.toggle('now',i===bi)})}}
function frame(){meter();visuals();requestAnimationFrame(frame)}
function wavBlob(){let rate=44100,n=Math.round(loopDur()*rate),mix=new Float32Array(n),active=tracks.filter(t=>!t.muted);for(let t of active){let b=activeBuffer(t),a=b.getChannelData(0),r=b.sampleRate/rate;for(let i=0;i<n;i++){let p=i*r,j=Math.floor(p),f=p-j,v=(a[j]||0)*(1-f)+(a[Math.min(j+1,a.length-1)]||0)*f;mix[i]+=v*t.volume}}let m=+$('master').value/100,pk=0;for(let i=0;i<n;i++){mix[i]*=m;pk=Math.max(pk,Math.abs(mix[i]))}if(pk>.98){let s=.98/pk;for(let i=0;i<n;i++)mix[i]*=s}let ab=new ArrayBuffer(44+n*4),v=new DataView(ab),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+n*4,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,rate,true);v.setUint32(28,rate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,n*4,true);let o=44;for(let i=0;i<n;i++){let s=Math.max(-1,Math.min(1,mix[i])),q=s<0?s*32768:s*32767;v.setInt16(o,q,true);v.setInt16(o+2,q,true);o+=4}return new Blob([v],{type:'audio/wav'})}
async function save(){let blob=wavBlob(),file=new File([blob],`TouchLoop_${bpm}BPM_${bars}bars.wav`,{type:'audio/wav'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return await navigator.share({title:'TouchLoop 7',files:[file]})}catch(e){if(e.name==='AbortError')return}let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
$('start').onclick=init;$('rec').onclick=()=>armRecord(true);$('newTrack').onclick=()=>armRecord(false);$('play').onclick=()=>transportRunning?stopAll():startAll(ctx.currentTime+.04,0);$('clear').onclick=clearAll;$('save').onclick=save;
$('bpm').oninput=e=>{if(tracks.length){e.target.value=bpm;return toast('Spuren zuerst löschen')}bpm=+e.target.value;$('bpmV').textContent=bpm};$('minus').onclick=()=>{if(!tracks.length&&bpm>50){bpm--;$('bpm').value=bpm;$('bpmV').textContent=bpm}};$('plus').onclick=()=>{if(!tracks.length&&bpm<180){bpm++;$('bpm').value=bpm;$('bpmV').textContent=bpm}};
$('count').onclick=()=>{countIn=!countIn;$('count').classList.toggle('on',countIn);$('count').textContent=countIn?'1 Takt Count-in':'Count-in aus'};$('clean').onclick=()=>{cleanRecord=!cleanRecord;$('clean').classList.toggle('on',cleanRecord);$('clean').textContent=cleanRecord?'✓ Clean Record':'Clean Record aus'};$('phones').onclick=()=>{headphoneMode=!headphoneMode;$('phones').classList.toggle('on',headphoneMode);$('phones').textContent=headphoneMode?'✓ Kopfhörer-Modus':'Kopfhörer-Modus'};
$('master').oninput=e=>{let v=+e.target.value/100;$('masterV').textContent=Math.round(v*100)+'%';if(masterGain&&!cleanMuted)masterGain.gain.setTargetAtTime(v,ctx.currentTime,.01)};
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&ctx&&ctx.state==='suspended')try{await ctx.resume()}catch(e){}});
renderBars();renderBeats();renderTracks();buttons();
