(()=>{'use strict';
const C=document.getElementById('world'),x=C.getContext('2d'),W=720;const $=id=>document.getElementById(id);let rng=Math.random,gen=1,stolen=0,paused=false,mode='sneak',running=true,t=0,history=[];
const gate={x:660,y:650,r:34},nests=[{x:115,y:120},{x:580,y:135},{x:370,y:555}],rocks=[{x:260,y:145,r:62},{x:480,y:315,r:74},{x:160,y:410,r:58},{x:350,y:350,r:48}];let player,guards,eggs,trail=[];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function mut(v){return clamp(v+(rng()-.5)*.16,.08,.95)}
function founder(){return{vision:.35+rng()*.2,hearing:.35+rng()*.2,scent:.35+rng()*.2,alarm:.3+rng()*.25,speed:.35+rng()*.25,energy:60+rng()*25,age:0,score:1}}
let genePool=Array.from({length:24},founder);
function breed(a,b){return{vision:mut(rng()<.5?a.vision:b.vision),hearing:mut(rng()<.5?a.hearing:b.hearing),scent:mut(rng()<.5?a.scent:b.scent),alarm:mut(rng()<.5?a.alarm:b.alarm),speed:mut(rng()<.5?a.speed:b.speed),energy:65,age:0,score:1}}
function spawnGuard(g,i){let ang=rng()*6.28,rad=100+rng()*180;return{...g,x:360+Math.cos(ang)*rad,y:350+Math.sin(ang)*rad,vx:0,vy:0,dir:rng()*6.28,state:'forage',tx:rng()*W,ty:rng()*W,alert:0,memory:null,id:i}}
function resetLevel(){player={x:55,y:650,vx:0,vy:0,noise:0,scent:0,alive:true};guards=genePool.map(spawnGuard);eggs=nests.map((n,i)=>({...n,taken:false,i}));stolen=0;trail=[];running=true;updateUI()}
function nextGeneration(success){guards.forEach(g=>{g.score+=g.energy*.015+(g.alert>0?3:0)});let ranked=[...guards].sort((a,b)=>b.score-a.score),surv=ranked.slice(0,Math.max(6,Math.floor(ranked.length*.45)));let old=avgGenes(genePool);let np=[];while(np.length<24){let a=surv[Math.floor(rng()*surv.length)],b=surv[Math.floor(rng()*surv.length)];np.push(breed(a,b))}genePool=np;gen++;let nu=avgGenes(genePool),changes=['vision','hearing','scent','alarm'].map(k=>({k,d:nu[k]-old[k]})).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d));history.push(Math.round((nu.vision+nu.hearing+nu.scent+nu.alarm)*25));if(history.length>30)history.shift();$('report').textContent=`Selection: ${changes[0].k} ${changes[0].d>=0?'↑':'↓'} ${Math.abs(changes[0].d*100).toFixed(1)}% · ${success?'raid escaped':'predator caught'}`;resetLevel();toast('Generation '+gen+' born')}
function avgGenes(arr){let o={vision:0,hearing:0,scent:0,alarm:0};arr.forEach(g=>Object.keys(o).forEach(k=>o[k]+=g[k]/arr.length));return o}
let target={x:55,y:650},drag=false;C.addEventListener('pointerdown',e=>{drag=true;C.setPointerCapture(e.pointerId);setTarget(e)});C.addEventListener('pointermove',e=>{if(drag)setTarget(e)});C.addEventListener('pointerup',()=>drag=false);function setTarget(e){let r=C.getBoundingClientRect();target={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*W}}
function obstaclePush(o){for(const r of rocks){let d=dist(o,r),m=r.r+10;if(d<m){let nx=(o.x-r.x)/(d||1),ny=(o.y-r.y)/(d||1);o.x=r.x+nx*m;o.y=r.y+ny*m}}o.x=clamp(o.x,10,W-10);o.y=clamp(o.y,10,W-10)}
function step(dt){if(paused||!running)return;t+=dt;let dx=target.x-player.x,dy=target.y-player.y,d=Math.hypot(dx,dy)||1;let sp=mode==='dash'?180:mode==='sneak'?70:105;if(d>7){player.vx=dx/d*sp;player.vy=dy/d*sp;player.x+=player.vx*dt;player.y+=player.vy*dt}else player.vx=player.vy=0;player.noise=Math.hypot(player.vx,player.vy)*(mode==='dash'?1.5:mode==='sneak'?.18:.6);player.scent=mode==='scent'?8:Math.min(90,player.scent+dt*12);obstaclePush(player);if(t%0.22<dt)trail.push({x:player.x,y:player.y,s:player.scent,life:7});trail.forEach(q=>q.life-=dt);trail=trail.filter(q=>q.life>0);
for(const e of eggs)if(!e.taken&&dist(player,e)<28){e.taken=true;stolen++;toast('Egg secured');updateUI()}
for(const g of guards){g.age+=dt;g.energy-=dt*(.5+g.speed*.3);let dp=dist(g,player),seen=dp<70+g.vision*190&&angleDiff(Math.atan2(player.y-g.y,player.x-g.x),g.dir)<.35+g.vision*.65;let heard=dp<player.noise*(.35+g.hearing*.9);let scentHit=false,best=null;for(const q of trail){let dd=dist(g,q);if(dd<(25+g.scent*95)*q.life/7){scentHit=true;best=q;break}}if(seen||heard){g.state='chase';g.memory={x:player.x,y:player.y};g.alert=3;g.score+=dt*2.5}else if(scentHit){g.state='track';g.memory={x:best.x,y:best.y};g.score+=dt*.4}else if(g.alert>0)g.alert-=dt;else if(rng()<dt*.35){g.state='forage';g.tx=rng()*W;g.ty=rng()*W}
let tx=g.state==='chase'?player.x:g.memory&&g.state==='track'?g.memory.x:g.tx,ty=g.state==='chase'?player.y:g.memory&&g.state==='track'?g.memory.y:g.ty;let ax=tx-g.x,ay=ty-g.y,ad=Math.hypot(ax,ay)||1,gs=45+g.speed*70+(g.state==='chase'?38:0);g.vx=ax/ad*gs;g.vy=ay/ad*gs;g.x+=g.vx*dt;g.y+=g.vy*dt;g.dir=Math.atan2(g.vy,g.vx);obstaclePush(g);if(dp<18){g.energy+=25;g.score+=12;running=false;toast('CAUGHT — survivors reproduce');setTimeout(()=>nextGeneration(false),900)}}
if(stolen===3&&dist(player,gate)<38&&running){running=false;toast('ESCAPED — selection recorded');setTimeout(()=>nextGeneration(true),900)}updateUI()}
function angleDiff(a,b){return Math.abs(Math.atan2(Math.sin(a-b),Math.cos(a-b)))}
function draw(){x.clearRect(0,0,W,W);x.fillStyle='#c9d5b5';x.fillRect(0,0,W,W);x.strokeStyle='rgba(32,36,31,.09)';x.lineWidth=1;for(let i=0;i<W;i+=36){x.beginPath();x.moveTo(i,0);x.lineTo(i,W);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(W,i);x.stroke()}
for(const r of rocks){x.fillStyle='#8e927e';x.beginPath();x.arc(r.x,r.y,r.r,0,7);x.fill();x.strokeStyle='#20241f';x.lineWidth=3;x.stroke()}
for(const n of nests){x.strokeStyle='#6c5537';x.lineWidth=7;x.beginPath();x.arc(n.x,n.y,27,0,7);x.stroke()}for(const e of eggs)if(!e.taken){x.fillStyle='#f4ecd7';x.beginPath();x.ellipse(e.x,e.y,9,13,0,0,7);x.fill();x.strokeStyle='#20241f';x.lineWidth=2;x.stroke()}
x.fillStyle=stolen===3?'#2f5a3d':'#74756c';x.fillRect(gate.x-28,gate.y-28,56,56);x.fillStyle='#f6f0df';x.font='bold 12px system-ui';x.textAlign='center';x.fillText('EXIT',gate.x,gate.y+4);
for(const q of trail){x.globalAlpha=q.life/7*.18;x.fillStyle='#815c43';x.beginPath();x.arc(q.x,q.y,4+q.s*.06,0,7);x.fill()}x.globalAlpha=1;
for(const g of guards){if(g.state==='chase'){x.fillStyle='rgba(150,70,50,.09)';x.beginPath();x.moveTo(g.x,g.y);x.arc(g.x,g.y,70+g.vision*190,g.dir-(.35+g.vision*.65),g.dir+(.35+g.vision*.65));x.closePath();x.fill()}x.save();x.translate(g.x,g.y);x.rotate(g.dir);x.fillStyle=g.state==='chase'?'#8b3d31':'#343b32';x.beginPath();x.moveTo(14,0);x.lineTo(-10,-8);x.lineTo(-6,0);x.lineTo(-10,8);x.closePath();x.fill();x.restore()}
x.save();x.translate(player.x,player.y);x.rotate(Math.atan2(player.vy,player.vx));x.fillStyle='#f5d65c';x.strokeStyle='#20241f';x.lineWidth=3;x.beginPath();x.arc(0,0,12,0,7);x.fill();x.stroke();x.beginPath();x.moveTo(8,0);x.lineTo(20,0);x.stroke();x.restore();if(stolen<3){x.fillStyle='#20241f';x.font='bold 14px Georgia';x.textAlign='left';x.fillText('STEAL THE EGGS',18,28)}requestAnimationFrame(draw)}
function updateUI(){let av=avgGenes(genePool);$('gen').textContent=gen;$('eggs').textContent=stolen+'/3';$('pop').textContent=guards?guards.length:24;for(const [k,id] of [['vision','v'],['hearing','h'],['scent','s'],['alarm','a']]){$(id).textContent=Math.round(av[k]*100);$('t'+id).style.setProperty('--v',Math.round(av[k]*100)+'%')}$('objective').textContent=stolen<3?'Steal 3 eggs, then reach the gate.':'All eggs secured — reach EXIT.';$('history').innerHTML=history.map(v=>`<span style="height:${Math.max(4,v)}%"></span>`).join('')}
function toast(s){let e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1100)}
$('sneak').onclick=()=>setMode('sneak');$('dash').onclick=()=>setMode('dash');$('scent').onclick=()=>{setMode('scent');toast('Scent masked briefly')};function setMode(m){mode=m;['sneak','dash','scent'].forEach(k=>$(k).classList.toggle('on',k===m))}$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'RESUME':'PAUSE'};$('newrun').onclick=()=>{genePool=Array.from({length:24},founder);gen=1;history=[];resetLevel()};
resetLevel();let last=performance.now();function loop(now){let dt=Math.min(.035,(now-last)/1000);last=now;step(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);requestAnimationFrame(draw);
})();