'use strict';
const cvs=document.getElementById('world'),ctx=cvs.getContext('2d',{alpha:false});
const spectrum=document.getElementById('spectrum'),sx=spectrum.getContext('2d'),historyC=document.getElementById('history'),hx=historyC.getContext('2d');
const pauseB=document.getElementById('pause'),speedB=document.getElementById('speed'),resetB=document.getElementById('reset');
const popEl=document.getElementById('pop'),genEl=document.getElementById('gen'),voiceEl=document.getElementById('voices'),stringsEl=document.getElementById('stringsN'),objBar=document.getElementById('objBar'),objText=document.getElementById('objText'),guide=document.getElementById('guide'),score=document.getElementById('score'),specimen=document.getElementById('specimen'),toast=document.getElementById('toast');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),last=performance.now(),acc=0,paused=false,speed=1,simTime=0,nextId=1,selected=null,gesture=null,scoreY=null,won=false;
let creatures=[],strings=[],pulses=[],dust=[],history=[];
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a=1,b=0)=>b+Math.random()*(a-b),lerp=(a,b,t)=>a+(b-a)*t;
let audio=null;
function audioCtx(){if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A()}if(audio?.state==='suspended')audio.resume();return audio}
function note(freq=.5,vol=.08,dur=.5,type='sine'){const a=audioCtx();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=180+freq*720;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(vol,a.currentTime+.012);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur+.03)}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);cvs.width=W*DPR;cvs.height=H*DPR;cvs.style.width=W+'px';cvs.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);for(const c of [spectrum,historyC]){const r=c.getBoundingClientRect();c.width=Math.max(2,r.width*DPR);c.height=Math.max(2,r.height*DPR);c.getContext('2d').setTransform(DPR,0,0,DPR,0,0)}makeAnchors()}
addEventListener('resize',resize);
let anchors=[];
function makeAnchors(){const m=Math.max(54,Math.min(W,H)*.09),top=Math.max(138,H*.17),bottom=H-Math.max(92,H*.13);anchors=[{x:m,y:top},{x:W*.5,y:top-18},{x:W-m,y:top},{x:W-m,y:bottom},{x:W*.5,y:bottom+10},{x:m,y:bottom}].map((a,i)=>({x:a.x,y:a.y,id:i}));for(const s of strings){s.a=anchors[s.ai];s.b=anchors[s.bi];s.freq=stringFreq(s.a,s.b)}}
function genome(seed=null){const g=seed?seed.slice():[rnd(.75,.25),rnd(.75,.25),rnd(),rnd(.8,.2),rnd(),rnd(.85,.15),rnd()];return g.map(v=>clamp(v,0,1))}
function mutateCross(a,b){const g=[];for(let k=0;k<7;k++){let v=Math.random()<.5?a[k]:b[k];if(Math.random()<.2)v+=rnd(.105,-.105);g[k]=clamp(v,0,1)}return g}
function addCreature(x=rnd(W*.8,W*.1),y=rnd(H*.62,H*.2),g=null,parents=[]){const o={id:nextId++,x,y,vx:rnd(10,-10),vy:rnd(10,-10),g:g||genome(),energy:rnd(1.15,.72),age:0,gen:parents.length?Math.max(...parents.map(p=>p.gen))+1:0,parents:parents.map(p=>p.id),children:0,cool:rnd(3),alive:true,lastPulse:-99};creatures.push(o);return o}
function reset(){simTime=0;nextId=1;selected=null;won=false;strings=[];pulses=[];history=[];dust=[];creatures=[];for(let i=0;i<66;i++)addCreature();for(let i=0;i<38;i++)dust.push({x:rnd(W),y:rnd(H*.72,H*.16),v:rnd(1,.25),phase:rnd(TAU)});toastMsg('The soundboard is alive. Draw a string, then pluck it.');updateAnalysis()}
function stringFreq(a,b){const d=Math.hypot(a.x-b.x,a.y-b.y),diag=Math.hypot(W,H);return clamp(1-d/(diag*.9),.05,.95)}
function nearestAnchor(x,y,rad=30){let best=null,bd=rad;for(const a of anchors){const d=Math.hypot(a.x-x,a.y-y);if(d<bd){best=a;bd=d}}return best}
function distanceToSegment(px,py,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=px-a.x,wy=py-a.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy,t=clamp(c1/c2,0,1),x=a.x+t*vx,y=a.y+t*vy;return {d:Math.hypot(px-x,py-y),t,x,y}}
function pluck(s,t=.5,power=1){const x=lerp(s.a.x,s.b.x,t),y=lerp(s.a.y,s.b.y,t);pulses.push({x,y,r:4,life:1,freq:s.freq,power:clamp(power,.5,1.5),sid:s.id});s.flash=1;s.plucks=(s.plucks||0)+1;note(s.freq,.045+.04*power,.5,'triangle');navigator.vibrate?.(10)}
function addString(a,b){if(!a||!b||a===b)return;const ai=a.id,bi=b.id;if(strings.some(s=>(s.ai===ai&&s.bi===bi)||(s.ai===bi&&s.bi===ai))){const s=strings.find(s=>(s.ai===ai&&s.bi===bi)||(s.ai===bi&&s.bi===ai));pluck(s,.5,1.1);return}if(strings.length>=5)strings.shift();const s={id:Date.now()+Math.random(),ai,bi,a,b,freq:stringFreq(a,b),flash:0,plucks:0};strings.push(s);stringsEl.textContent=strings.length;pluck(s,.5,1.15);guide.style.opacity=0}
function pulseFoodAt(o){let gain=0;for(const p of pulses){const d=Math.hypot(o.x-p.x,o.y-p.y),band=Math.abs(o.g[2]-p.freq),hear=75+o.g[3]*150;if(d<p.r+hear*.25&&band<.18+o.g[3]*.06){const resonance=1-band/.24;gain+=Math.max(0,resonance)*.012*p.power*(.65+o.g[0])}}return gain}
function nearestDust(o){let best=null,bd=150+o.g[3]*120;for(const d of dust){if(d.v<.05)continue;const z=Math.hypot(d.x-o.x,d.y-o.y);if(z<bd){best=d;bd=z}}return {best,bd}}
function step(dt){simTime+=dt;for(const s of strings)s.flash=Math.max(0,s.flash-dt*2.6);for(const p of pulses){p.r+=dt*(80+180*p.power);p.life-=dt*.7}pulses=pulses.filter(p=>p.life>0);for(const d of dust){d.v=clamp(d.v+dt*.018,0,1);d.phase+=dt}const alive=creatures.filter(o=>o.alive);for(const o of alive){o.age+=dt;o.cool-=dt;const body=o.g[0],spd=o.g[1],hear=o.g[3],rhythm=o.g[4],turn=o.g[6];const nd=nearestDust(o);let tx=o.x+Math.cos(o.age*(.8+rhythm*2.2)+o.id)*90,ty=o.y+Math.sin(o.age*(.7+turn*1.8)+o.id)*70;if(nd.best){tx=nd.best.x;ty=nd.best.y}for(const p of pulses){const d=Math.hypot(o.x-p.x,o.y-p.y),band=Math.abs(o.g[2]-p.freq);if(d<120+hear*180&&band<.22){tx=p.x;ty=p.y;break}}const ang=Math.atan2(ty-o.y,tx-o.x)+Math.sin(o.age*(1.1+rhythm*2)+o.id)*(.5+turn*.9);const thrust=11+spd*42;o.vx=o.vx*.9+Math.cos(ang)*thrust*.1;o.vy=o.vy*.9+Math.sin(ang)*thrust*.1;o.x+=o.vx*dt;o.y+=o.vy*dt;if(o.x<18||o.x>W-18){o.vx*=-.85;o.x=clamp(o.x,18,W-18)}if(o.y<125||o.y>H-55){o.vy*=-.85;o.y=clamp(o.y,125,H-55)}if(nd.best&&nd.bd<9+body*6){const bite=Math.min(nd.best.v,.025*dt*(.7+body));nd.best.v-=bite;o.energy+=bite*.8}o.energy+=pulseFoodAt(o)*dt*2.4;const cost=.006+.008*body+.014*spd*spd+.005*hear;o.energy-=cost*dt;o.energy=clamp(o.energy,0,2.1);if(o.energy<=0||o.age>48+rnd(30)){o.alive=false;continue}if(o.energy>1.25&&o.age>4.5&&o.cool<=0&&alive.length<180){let mate=null,md=22+hear*20;for(const m of alive){if(m===o||!m.alive||m.cool>0||m.energy<1.05)continue;const d=Math.hypot(m.x-o.x,m.y-o.y);const pitch=Math.abs(m.g[2]-o.g[2]),beat=Math.abs(m.g[4]-o.g[4]);const threshold=.34-(o.g[5]+m.g[5])*.11;if(d<md&&pitch+beat*.4<threshold){mate=m;md=d}}if(mate){const c=addCreature((o.x+mate.x)/2,(o.y+mate.y)/2,mutateCross(o.g,mate.g),[o,mate]);c.energy=.72;o.energy-=.32;mate.energy-=.24;o.cool=mate.cool=3.4;o.children++;mate.children++;if(Math.random()<.13)note(c.g[2],.018,.2,'sine')}}}creatures=creatures.filter(o=>o.alive||o===selected);if(creatures.filter(o=>o.alive).length<26){const pool=creatures.filter(o=>o.alive).sort((a,b)=>b.energy-a.energy);for(let i=0;i<3&&pool[i];i++)addCreature(pool[i].x+rnd(14,-14),pool[i].y+rnd(14,-14),genome(pool[i].g),[pool[i]])}if(!history.length||simTime-history.at(-1).t>1.5)updateAnalysis()}
function stats(){const a=creatures.filter(o=>o.alive),pitches=a.map(o=>o.g[2]).sort((x,y)=>x-y);let voices=0,last=-9;for(const p of pitches){if(p-last>.14){voices++;last=p}else last=lerp(last,p,.18)}return {a,pop:a.length,maxGen:a.reduce((m,o)=>Math.max(m,o.gen),0),voices,pitches}}
function updateAnalysis(){const s=stats();popEl.textContent=s.pop;genEl.textContent=s.maxGen;voiceEl.textContent=s.voices;stringsEl.textContent=strings.length;history.push({t:simTime,p:s.pop,v:s.voices,g:s.maxGen});if(history.length>100)history.shift();drawSpectrum(s);drawHistory();const progress=clamp((s.voices-1)/2,0,1);objBar.style.width=(progress*100)+'%';if(s.voices>=3&&strings.length>=3){objText.textContent='Three pitch lineages are alive. Keep all three above generation 4 while continuing to pluck.';if(s.maxGen>=4&&!won){won=true;toastMsg('CHORD STABILIZED — your instrument has evolved three living voices.');note(.25,.05,.7);setTimeout(()=>note(.52,.05,.7),120);setTimeout(()=>note(.78,.05,.9),240)}}}
function drawSpectrum(s){const r=spectrum.getBoundingClientRect(),w=r.width,h=r.height;sx.clearRect(0,0,w,h);sx.strokeStyle='#d8ccb5';for(let i=1;i<5;i++){sx.beginPath();sx.moveTo(i*w/5,0);sx.lineTo(i*w/5,h);sx.stroke()}for(const o of s.a){const x=8+o.g[2]*(w-16),y=13+(o.id*17%Math.max(18,h-25));sx.fillStyle=`hsla(${20+o.g[2]*210} 42% 42% / .55)`;sx.beginPath();sx.arc(x,y,1.5+o.g[0]*1.5,0,TAU);sx.fill()}sx.fillStyle='#6f665a';sx.font='9px system-ui';sx.fillText('LOW',8,h-7);sx.fillText('HIGH',w-32,h-7)}
function drawHistory(){const r=historyC.getBoundingClientRect(),w=r.width,h=r.height;hx.clearRect(0,0,w,h);if(history.length<2)return;const maxP=Math.max(80,...history.map(d=>d.p));hx.strokeStyle='#a66047';hx.lineWidth=2;hx.beginPath();history.forEach((d,i)=>{const x=8+i/(history.length-1)*(w-16),y=h-15-d.p/maxP*(h-26);i?hx.lineTo(x,y):hx.moveTo(x,y)});hx.stroke();hx.strokeStyle='#3d5268';hx.lineWidth=1.5;hx.beginPath();history.forEach((d,i)=>{const x=8+i/(history.length-1)*(w-16),y=h-15-clamp(d.v/5,0,1)*(h-26);i?hx.lineTo(x,y):hx.moveTo(x,y)});hx.stroke();hx.fillStyle='#71695e';hx.font='9px system-ui';hx.fillText('population / pitch-lineages',8,11)}
function drawBackground(){ctx.fillStyle='#efe6cf';ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.13;ctx.strokeStyle='#786f61';ctx.lineWidth=1;for(let x=18;x<W;x+=28){ctx.beginPath();ctx.moveTo(x,115);ctx.lineTo(x,H);ctx.stroke()}for(let y=115;y<H;y+=28){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore();ctx.fillStyle='rgba(70,63,54,.06)';ctx.beginPath();ctx.ellipse(W*.5,H*.52,W*.43,H*.29,0,0,TAU);ctx.fill()}
function drawAnchors(){for(const a of anchors){ctx.save();ctx.translate(a.x,a.y);ctx.fillStyle='#d2c2a0';ctx.strokeStyle='#554c40';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,13,0,TAU);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,4,0,TAU);ctx.fillStyle='#554c40';ctx.fill();ctx.restore()}}
function drawString(s){ctx.save();ctx.strokeStyle=s.flash>0?`rgba(166,96,71,${.55+.45*s.flash})`:'#3d5268';ctx.lineWidth=2.2+s.flash*2;ctx.beginPath();ctx.moveTo(s.a.x,s.a.y);const sag=14+Math.sin(simTime*18)*s.flash*8,mx=(s.a.x+s.b.x)/2,my=(s.a.y+s.b.y)/2+sag;ctx.quadraticCurveTo(mx,my,s.b.x,s.b.y);ctx.stroke();ctx.fillStyle='#544b40';ctx.font='8px system-ui';ctx.fillText(`${Math.round(180+s.freq*720)} Hz`,mx-15,my-6);ctx.restore()}
function drawCreature(o){if(!o.alive)return;const r=3.5+o.g[0]*4.6,hue=20+o.g[2]*210;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(Math.atan2(o.vy,o.vx));ctx.fillStyle=`hsl(${hue} 38% ${42+o.g[4]*12}%)`;ctx.strokeStyle=o===selected?'#fffaf0':'rgba(55,48,40,.5)';ctx.lineWidth=o===selected?3:1;ctx.beginPath();ctx.moveTo(r*1.5,0);ctx.quadraticCurveTo(0,-r,r*-1.1,0);ctx.quadraticCurveTo(0,r,r*1.5,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=`hsla(${hue} 45% 35% / .6)`;ctx.beginPath();ctx.moveTo(-r*.4,-r*.65);ctx.lineTo(-r*(1+o.g[3]),-r*(.8+o.g[4]));ctx.moveTo(-r*.4,r*.65);ctx.lineTo(-r*(1+o.g[3]),r*(.8+o.g[4]));ctx.stroke();ctx.restore()}
function render(){drawBackground();for(const d of dust){if(d.v<.05)continue;ctx.fillStyle=`rgba(185,153,74,${.12+d.v*.45})`;ctx.beginPath();ctx.arc(d.x,d.y,1+d.v*2.1,0,TAU);ctx.fill()}for(const s of strings)drawString(s);for(const p of pulses){ctx.strokeStyle=`hsla(${20+p.freq*210} 38% 45% / ${p.life*.32})`;ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.stroke()}drawAnchors();for(const o of creatures)drawCreature(o);if(gesture?.mode==='draw'&&gesture.anchor){ctx.strokeStyle='rgba(61,82,104,.55)';ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(gesture.anchor.x,gesture.anchor.y);ctx.lineTo(gesture.x,gesture.y);ctx.stroke();ctx.setLineDash([])}}
function nearestCreature(x,y){let best=null,bd=18;for(const o of creatures){if(!o.alive)continue;const d=Math.hypot(o.x-x,o.y-y);if(d<bd){best=o;bd=d}}return best}
function inspect(o){selected=o;if(!o){specimen.textContent='Tap a creature to pin its inherited body, speed, pitch, hearing, rhythm and mate preference.';return}specimen.innerHTML=`<b>Voice #${o.id}</b> · generation ${o.gen} · age ${o.age.toFixed(1)} · energy ${o.energy.toFixed(2)}<br>body ${o.g[0].toFixed(2)} · speed ${o.g[1].toFixed(2)} · pitch ${Math.round(180+o.g[2]*720)} Hz · hearing ${o.g[3].toFixed(2)}<br>rhythm ${o.g[4].toFixed(2)} · choosiness ${o.g[5].toFixed(2)} · turning ${o.g[6].toFixed(2)} · offspring ${o.children}`;score.classList.add('open')}
function startTouch(x,y,id){audioCtx();const a=nearestAnchor(x,y,28);gesture={id,startX:x,startY:y,x,y,anchor:a,mode:a?'draw':'probe',moved:false,crossed:null}}
function moveTouch(x,y){if(!gesture)return;gesture.x=x;gesture.y=y;const dist=Math.hypot(x-gesture.startX,y-gesture.startY);if(dist>8)gesture.moved=true;if(gesture.mode==='probe'&&gesture.moved){for(const s of strings){const z=distanceToSegment(x,y,s.a,s.b);if(z.d<14&&gesture.crossed!==s.id){gesture.crossed=s.id;pluck(s,z.t,clamp(dist/60,.7,1.35));guide.style.opacity=0;break}}}}
function endTouch(x,y,cancel=false){if(!gesture)return;const g=gesture;gesture=null;if(cancel)return;if(g.mode==='draw'&&g.anchor){const b=nearestAnchor(x,y,30);if(b&&b!==g.anchor&&g.moved){addString(g.anchor,b);return}}if(!g.moved){const o=nearestCreature(x,y);if(o)inspect(o)}}
function touchPoint(e,id=null){const list=e.touches.length?e.touches:e.changedTouches;for(const t of list)if(id==null||t.identifier===id)return t;return null}
cvs.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;e.preventDefault();const t=e.touches[0];startTouch(t.clientX,t.clientY,t.identifier)},{passive:false});
cvs.addEventListener('touchmove',e=>{if(!gesture)return;const t=touchPoint(e,gesture.id);if(!t)return;e.preventDefault();moveTouch(t.clientX,t.clientY)},{passive:false});
cvs.addEventListener('touchend',e=>{if(!gesture)return;const t=touchPoint(e,gesture.id);e.preventDefault();endTouch(t?.clientX??gesture.x,t?.clientY??gesture.y,false)},{passive:false});
cvs.addEventListener('touchcancel',e=>{e.preventDefault();endTouch(gesture?.x||0,gesture?.y||0,true)},{passive:false});
cvs.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;cvs.setPointerCapture(e.pointerId);startTouch(e.clientX,e.clientY,e.pointerId)});cvs.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!gesture)return;moveTouch(e.clientX,e.clientY)});cvs.addEventListener('pointerup',e=>{if(e.pointerType==='touch')return;endTouch(e.clientX,e.clientY,false)});
score.addEventListener('touchstart',e=>{scoreY=e.touches[0].clientY},{passive:true});score.addEventListener('touchend',e=>{if(scoreY==null)return;const y=e.changedTouches[0].clientY,dy=y-scoreY;if(dy<-28)score.classList.add('open');if(dy>28)score.classList.remove('open');scoreY=null},{passive:true});
pauseB.onclick=()=>{paused=!paused;pauseB.textContent=paused?'▶':'Ⅱ'};speedB.onclick=()=>{speed=speed===1?3:speed===3?7:1;speedB.textContent=speed+'×'};resetB.onclick=()=>reset();
function toastMsg(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)}
function loop(t){const raw=Math.min(.05,(t-last)/1000);last=t;if(!paused){acc+=raw*speed;while(acc>.033){step(.033);acc-=.033}}render();requestAnimationFrame(loop)}
resize();reset();requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.__resonantTest={stats,reset,addString:(a,b)=>addString(anchors[a],anchors[b]),pluck:(i)=>strings[i]&&pluck(strings[i]),step:(n=30)=>{for(let i=0;i<n;i++)step(.033)},state:()=>({strings:strings.length,pulses:pulses.length,pop:stats().pop,maxGen:stats().maxGen,voices:stats().voices})};