import{GameState}from'../game/state.js';import{gradeRun}from'../game/mastery.js';import{MUSEUM}from'../levels/museum.js';import{HELIX}from'../levels/helix.js';import{CanvasRenderer}from'../renderer/canvas-renderer.js';import{WebGLScene}from'../renderer/webgl-scene.js';import{VectorOverlay}from'../renderer/vector-overlay.js';import{GestureController}from'../input/gesture.js';import{VisibilityGuard,visibilityLogicSelfTest}from'../renderer/visibility-guard.js';import{AudioSystem}from'../audio/audio.js';import{UI}from'../ui/ui.js';import{SettingsPanel}from'../ui/settings-panel.js';import{settings}from'../persistence/settings.js';import{save}from'../persistence/save.js';import{selfTest}from'../tests/selftest.js';
const BUILD='v0016',LEVELS={museum:MUSEUM,helix:HELIX},c=document.querySelector('#game'),sc=document.querySelector('#scene'),g=new GameState(),r=new CanvasRenderer(c),wr=new WebGLScene(sc),vo=new VectorOverlay(c),a=new AudioSystem(),u=new UI();let current='museum',l=false,q=false,s='STEALTH',t=performance.now(),diag=0,paused=false,settingsOrigin='menu',backgroundPaused=false,lastMastery=null;
const renderMode=()=>document.documentElement.dataset.renderMode||globalThis.__gravityHeistRenderMode||'hybrid';r.setGpuBackdrop(renderMode()!=='canvas-safe');const visibilityGuard=new VisibilityGuard(c,r,sc);globalThis.__gravityHeistBuild=BUILD;const badge=document.querySelector('#version');if(badge)badge.textContent=BUILD;
const hapticsSupported=typeof navigator.vibrate==='function';let prefs=settings.load();function applyPrefs(v){prefs=v;a.setSettings(v);wr.setSettings(v);document.body.classList.toggle('reduce-motion',v.reducedMotion)}applyPrefs(prefs);const sp=new SettingsPanel({hapticsSupported,onApply:applyPrefs});
function haptic(ms=8){if(prefs.haptics&&hapticsSupported)navigator.vibrate(ms)}
const gestures=new GestureController(c,{onPreview:(x,y,d)=>{if(!paused)r.setPreview(x,y,d)},onSwipe:d=>{if(g.mode!=='play'||paused)return;a.unlock();g.shift(d);r.gravityPulse();a.shift();haptic(7)}});
function refreshContracts(){const p=save.load();for(const card of document.querySelectorAll('[data-contract]')){const id=card.dataset.contract,unlocked=p.unlocked.includes(id),best=p.bestByHeist[id]||0,grade=p.bestGradeByHeist[id],badges=(p.badgesByHeist[id]||[]).length,btn=card.querySelector('button'),stat=card.querySelector('.contract-stat');card.classList.toggle('locked',!unlocked);btn.disabled=!unlocked;btn.textContent=unlocked?(p.completed.includes(id)?'RUN AGAIN':'INFILTRATE'):'LOCKED';stat.textContent=unlocked?(best?`${grade||'C'} · BEST ${best.toLocaleString()} · ${badges} SIG`:'UNPLAYED'):'COMPLETE AURORA MUSEUM'}}
function syncRenderMode(){const safe=renderMode()==='canvas-safe';r.setGpuBackdrop(!safe);if(safe&&sc)sc.style.display='none'}
function start(id=current){if(!LEVELS[id]||!save.isUnlocked(id))return;current=id;a.unlock();g.start(LEVELS[id]);a.setLevel(g.level);r.resetCamera(g.player);syncRenderMode();l=q=false;s='STEALTH';paused=backgroundPaused=false;lastMastery=null;sp.hide();u.showPlay(g)}
function openSettings(origin){settingsOrigin=origin;paused=origin==='play';document.querySelector('#menu').classList.add('hidden');document.querySelector('#result').classList.add('hidden');document.querySelector('#hud').classList.toggle('hidden',origin!=='play');document.querySelector('#settingsBack').textContent=origin==='play'?'RESUME HEIST':'BACK';sp.show()}
function closeSettings(){sp.hide();backgroundPaused=false;if(settingsOrigin==='play'){paused=false;u.showPlay(g);t=performance.now()}else if(settingsOrigin==='result')u.showResult(g.score(),g.elapsed,g.shifts,g.security.multiplier(),g,lastMastery);else{refreshContracts();u.showMenu()}}
document.querySelectorAll('[data-contract] button').forEach(btn=>btn.onclick=()=>start(btn.closest('[data-contract]').dataset.contract));document.querySelector('#retry').onclick=()=>start(current);document.querySelector('#resultMenu').onclick=()=>{refreshContracts();u.showMenu()};document.querySelector('#pauseBtn').onclick=()=>openSettings('play');document.querySelector('#menuSettings').onclick=()=>openSettings('menu');document.querySelector('#resultSettings').onclick=()=>openSettings('result');document.querySelector('#settingsBack').onclick=closeSettings;
function impactMaterial(i){const A=i.a.material||'generic',B=i.b.material||'generic';return B==='armor'||A==='armor'?'armor':B==='metal'||A==='metal'?'metal':B==='glass'||A==='glass'?'glass':B==='stone'||A==='stone'?'stone':A}
function frame(n){const d=Math.min(.033,(n-t)/1000);t=n;if(g.mode==='play'&&!paused){g.update(d);a.ambience();u.update(g);for(const i of g.impactEvents)if(i.strength>62)a.impact(impactMaterial(i),i.strength);if(g.security.state!==s){s=g.security.state;a.alarm(s);if(s==='ALERT'||s==='LOCKDOWN')haptic(s==='LOCKDOWN'?18:10)}if(g.hasLoot&&!l){l=true;a.loot();r.gravityPulse();haptic(12)}if(g.complete&&!q){q=true;const z=g.score();lastMastery=gradeRun(g);save.record(current,z,lastMastery);refreshContracts();a.success();haptic(20);u.showResult(z,g.elapsed,g.shifts,g.security.multiplier(),g,lastMastery)}}r.render(g,d);const view=r.getView();if(renderMode()!=='canvas-safe')wr.render(g,d,view);vo.render(g,view);visibilityGuard.tick(g,view);if(++diag%60===0)globalThis.__gravityHeistDiagnostics={renderer:renderMode()==='canvas-safe'?{mode:'canvas-safe',webglSkipped:true}:wr.getStats(),camera:r.getCameraStats(),visibility:visibilityGuard.getStats(),renderMode:renderMode(),mode:g.mode,paused,backgroundPaused,security:g.security?.state,heist:g.level?.id,audioProfile:a.profile?.id,locks:g.vectorLocks?.map(x=>({id:x.id,open:x.open})),mastery:lastMastery,input:gestures.getStats(),settings:{...prefs,hapticsSupported},version:BUILD};requestAnimationFrame(frame)}
refreshContracts();selfTest();visibilityLogicSelfTest();requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{t=performance.now();if(document.visibilityState==='hidden'&&g.mode==='play'){paused=true;backgroundPaused=true}if(document.visibilityState==='visible'){a.ctx?.resume?.();if(backgroundPaused&&g.mode==='play')openSettings('play')}});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
