(() => {
'use strict';
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d',{alpha:false});
const $=id=>document.getElementById(id);
const ui={pop:$('pop'),div:$('diversity'),era:$('era'),energy:$('energyBar'),gene:$('geneBar'),intro:$('intro'),event:$('eventCard'),hint:$('hint'),lab:$('lab'),labTitle:$('labTitle'),geneStats:$('geneStats'),lineage:$('lineageText'),pause:$('pauseBtn')};
let W=0,H=0,DPR=1,run=false,paused=false,last=0,simTime=0,era=1,tool='food',audio=null,eventTimer=0,nextEvent=34,selected=null,bestDiversity=Number(localStorage.getItem('genesisTide.best')||0);
const creatures=[],resources=[],fields=[],particles=[];
const geneNames=[['speed','Tempo'],['sense','Sinne'],['armor','Panzer'],['eff','Effizienz'],['heat','Hitzetoleranz'],['tox','Toxinresistenz']];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize);resize();
function beep(freq=440,d=.05,type='sine',gain=.035){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function geneColor(g){const h=165+g.speed*45-g.armor*25+g.tox*55;return `hsl(${h} 75% ${48+g.eff*13}%)`}
function baseGenes(){return{speed:rnd(.34,.65),sense:rnd(.3,.7),armor:rnd(.22,.62),eff:rnd(.38,.7),heat:rnd(.25,.65),tox:rnd(.18,.55)}}
let lineageCounter=0;
class Creature{constructor(x,y,genes=baseGenes(),generation=1,parent='Primärlinie'){this.x=x;this.y=y;this.vx=rnd(-1,1);this.vy=rnd(-1,1);this.g={...genes};this.energy=rnd(65,90);this.age=0;this.generation=generation;this.parent=parent;this.id=++lineageCounter;this.cool=rnd(1,3);this.dead=false;this.flash=0} mutate(){const n={...this.g};for(const k in n)if(Math.random()<.42)n[k]=clamp(n[k]+rnd(-.09,.09),.05,.96);return n} update(dt){this.age+=dt;this.cool-=dt;this.flash=Math.max(0,this.flash-dt);let tx=null,score=1e9;const radius=55+this.g.sense*175;for(const r of resources){const d=Math.hypot(r.x-this.x,r.y-this.y);if(d<radius&&d<score){score=d;tx=r}}if(tx){const dx=tx.x-this.x,dy=tx.y-this.y,d=Math.max(1,Math.hypot(dx,dy));this.vx+=dx/d*.018*(.3+this.g.sense);this.vy+=dy/d*.018*(.3+this.g.sense)}else{this.vx+=rnd(-.018,.018);this.vy+=rnd(-.018,.018)}let stress=0;for(const f of fields){const d=Math.hypot(this.x-f.x,this.y-f.y);if(d<f.r){const p=1-d/f.r;if(f.type==='heat')stress+=p*(1-this.g.heat)*9*dt;if(f.type==='toxin')stress+=p*(1-this.g.tox)*12*dt;if(f.type==='current'){const sp=.03+.09*this.g.speed;this.vx+=f.dx*sp*p;this.vy+=f.dy*sp*p}}}const max=.42+this.g.speed*1.25-this.g.armor*.22,s=Math.hypot(this.vx,this.vy);if(s>max){this.vx*=max/s;this.vy*=max/s}this.x+=this.vx*dt*60;this.y+=this.vy*dt*60;this.vx*=.986;this.vy*=.986;const top=88,bottom=H-178;if(this.x<10||this.x>W-10)this.vx*=-1;if(this.y<top||this.y>bottom)this.vy*=-1;this.x=clamp(this.x,10,W-10);this.y=clamp(this.y,top,bottom);const metabolic=(1.05+this.g.speed*1.8+this.g.sense*.55+this.g.armor*.75)*(1.25-this.g.eff*.63);this.energy-=metabolic*dt+stress;for(let i=resources.length-1;i>=0;i--){const r=resources[i],rr=5+this.g.armor*4;if(Math.hypot(r.x-this.x,r.y-this.y)<rr+5){this.energy=Math.min(130,this.energy+24);resources.splice(i,1);burst(this.x,this.y,geneColor(this.g),4);beep(620,.025,'sine',.008);break}}if(this.energy>104&&this.age>6&&this.cool<=0&&creatures.length<155){this.energy*=.53;this.cool=rnd(3.5,6);const child=new Creature(this.x+rnd(-6,6),this.y+rnd(-6,6),this.mutate(),this.generation+1,`Linie ${this.id}`);child.energy=48;creatures.push(child);burst(this.x,this.y,'#86ffd4',8)}if(this.energy<=0||this.age>95+this.g.eff*85){this.dead=true;burst(this.x,this.y,'rgba(160,210,220,.7)',5)}} draw(){const r=3.2+this.g.armor*4.6;ctx.save();ctx.translate(this.x,this.y);ctx.rotate(Math.atan2(this.vy,this.vx));ctx.globalAlpha=.2+.8*clamp(this.energy/70,0,1);ctx.fillStyle=geneColor(this.g);ctx.shadowColor=geneColor(this.g);ctx.shadowBlur=this.flash?18:7;ctx.beginPath();ctx.ellipse(0,0,r*1.35,r,.25,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(235,255,255,.7)';ctx.beginPath();ctx.arc(r*.55,-r*.18,.75+this.g.sense*.9,0,Math.PI*2);ctx.fill();if(this.g.armor>.62){ctx.strokeStyle='rgba(230,255,255,.45)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(-r*.1,0,r*.75,-1.2,1.2);ctx.stroke()}ctx.restore()}}
function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-1.2,1.2),vy:rnd(-1.2,1.2),life:rnd(.3,.8),c})}
function addFood(x,y,n=5){for(let i=0;i<n;i++)resources.push({x:x+rnd(-18,18),y:y+rnd(-18,18),life:rnd(15,34),p:rnd(0,6.2)})}
function addField(type,x,y){if(type==='heat'||type==='toxin')fields.push({type,x,y,r:rnd(45,70),life:13,max:13});else if(type==='current'){const a=Math.random()*Math.PI*2;fields.push({type,x,y,r:72,dx:Math.cos(a),dy:Math.sin(a),life:14,max:14})}}
function apply(x,y){if(y<78||y>H-155)return;if(tool==='food')addFood(x,y,7);else addField(tool,x,y);burst(x,y,tool==='heat'?'#ffb86b':tool==='toxin'?'#dc91ff':tool==='current'?'#77bfff':'#78f5c8',10);beep(tool==='food'?520:tool==='heat'?330:tool==='toxin'?190:260,.06,'triangle',.018)}
function seed(){creatures.length=resources.length=fields.length=particles.length=0;lineageCounter=0;for(let i=0;i<24;i++)creatures.push(new Creature(rnd(25,W-25),rnd(110,H-205)));for(let i=0;i<55;i++)addFood(rnd(20,W-20),rnd(110,H-205),1);simTime=0;era=1;nextEvent=32;eventTimer=0}
function diversity(){if(creatures.length<2)return 0;let v=0;for(const [k] of geneNames){let mean=0;for(const c of creatures)mean+=c.g[k];mean/=creatures.length;let variance=0;for(const c of creatures)variance+=(c.g[k]-mean)**2;v+=Math.sqrt(variance/creatures.length)}return clamp(v/6*5.2,0,1)}
function avg(k){return creatures.length?creatures.reduce((s,c)=>s+c.g[k],0)/creatures.length:0}
function worldEvent(){const options=[['Kälteeinbruch','Die Wassertemperatur fällt. Hitzetoleranz verliert ihren Vorteil.'],['Algenblüte','Ein kurzer Nahrungsüberschuss belohnt effiziente Sammler.'],['Giftstrom','Toxine dringen ins Becken ein. Resistenz wird zum Selektionsvorteil.'],['Springflut','Starke Strömungen begünstigen schnelle und robuste Linien.']];const idx=Math.floor(Math.random()*options.length),[name,text]=options[idx];if(idx===0){for(let i=0;i<5;i++)fields.push({type:'heat',x:rnd(0,W),y:rnd(110,H-210),r:rnd(60,100),life:10,max:10,cold:true})}if(idx===1)for(let i=0;i<65;i++)addFood(rnd(0,W),rnd(100,H-200),1);if(idx===2)for(let i=0;i<5;i++)addField('toxin',rnd(0,W),rnd(100,H-200));if(idx===3)for(let i=0;i<4;i++)addField('current',rnd(0,W),rnd(100,H-200));showEvent(`<b>${name}</b><br>${text}`);beep(180,.18,'sawtooth',.025)}
function showEvent(html){ui.event.innerHTML=html;ui.event.classList.add('show');clearTimeout(showEvent.t);showEvent.t=setTimeout(()=>ui.event.classList.remove('show'),4500)}
function update(dt){if(!run||paused)return;simTime+=dt;eventTimer+=dt;if(resources.length<35&&Math.random()<dt*5)addFood(rnd(10,W-10),rnd(95,H-185),1);for(const r of resources)r.life-=dt;for(let i=resources.length-1;i>=0;i--)if(resources[i].life<=0)resources.splice(i,1);for(const f of fields)f.life-=dt;for(let i=fields.length-1;i>=0;i--)if(fields[i].life<=0)fields.splice(i,1);for(const c of [...creatures])c.update(dt);for(let i=creatures.length-1;i>=0;i--)if(creatures[i].dead)creatures.splice(i,1);if(creatures.length===0){showEvent('<b>Aussterben.</b><br>Das Becken wird aus einem konservierten Genpool neu besiedelt.');for(let i=0;i<10;i++)creatures.push(new Creature(rnd(20,W-20),rnd(100,H-200)));era++;}if(simTime>era*38){era++;showEvent(`<b>Ära ${era}</b><br>Die Umwelt wird instabiler. Mutationen entscheiden schneller über Erfolg.`);for(const c of creatures)if(Math.random()<.2)c.g={...c.mutate()}}if(eventTimer>nextEvent){eventTimer=0;nextEvent=rnd(28,44);worldEvent()}for(const p of particles){p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.life-=dt;p.vx*=.97;p.vy*=.97}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);const d=diversity();bestDiversity=Math.max(bestDiversity,d);localStorage.setItem('genesisTide.best',bestDiversity.toFixed(3));ui.pop.textContent=creatures.length;ui.div.textContent=Math.round(d*100)+'%';ui.era.textContent='Ära '+era;ui.energy.style.width=clamp(resources.length/85*100,4,100)+'%';ui.gene.style.width=Math.max(4,d*100)+'%'}
function drawBackground(t){ctx.fillStyle='#041019';ctx.fillRect(0,0,W,H);const grd=ctx.createRadialGradient(W*.5,H*.38,20,W*.5,H*.42,Math.max(W,H)*.78);grd.addColorStop(0,'#123848');grd.addColorStop(.52,'#08202d');grd.addColorStop(1,'#02070b');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.08;ctx.strokeStyle='#83dddf';ctx.lineWidth=1;for(let y=95;y<H-160;y+=28){ctx.beginPath();for(let x=0;x<=W;x+=20){const yy=y+Math.sin(x*.02+t*.0007+y)*3;ctx.lineTo(x,yy)}ctx.stroke()}ctx.globalAlpha=1}
function draw(){drawBackground(performance.now());for(const f of fields){const a=clamp(f.life/f.max,0,1);const c=f.type==='heat'?(f.cold?'92,180,255':'255,170,92'):f.type==='toxin'?'213,123,255':'92,169,255';const g=ctx.createRadialGradient(f.x,f.y,2,f.x,f.y,f.r);g.addColorStop(0,`rgba(${c},${.22*a})`);g.addColorStop(1,`rgba(${c},0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.fill();if(f.type==='current'){ctx.strokeStyle=`rgba(${c},${.35*a})`;for(let j=-1;j<=1;j++){ctx.beginPath();ctx.moveTo(f.x-f.dx*22+f.dy*j*8,f.y-f.dy*22-f.dx*j*8);ctx.lineTo(f.x+f.dx*22+f.dy*j*8,f.y+f.dy*22-f.dx*j*8);ctx.stroke()}}}for(const r of resources){r.p+=.025;ctx.fillStyle='rgba(121,255,194,.75)';ctx.shadowColor='#75f6bd';ctx.shadowBlur=7;ctx.beginPath();ctx.arc(r.x+Math.sin(r.p)*1.2,r.y,2.1,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;for(const c of creatures)c.draw();for(const p of particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,1.7,1.7)}ctx.globalAlpha=1;if(!run){ctx.fillStyle='rgba(255,255,255,.4)';ctx.font='12px -apple-system';ctx.textAlign='center';ctx.fillText('Gezeitenbecken wartet auf Besiedlung',W/2,H/2)}}
function frame(ts){const dt=Math.min(.033,(ts-last)/1000||.016);last=ts;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function inspectAt(x,y){let near=null,dd=26;for(const c of creatures){const d=Math.hypot(c.x-x,c.y-y);if(d<dd){dd=d;near=c}}if(!near)return false;selected=near;ui.labTitle.textContent=`Linie ${near.id} · Gen ${near.generation}`;ui.geneStats.innerHTML=geneNames.map(([k,n])=>`<div class="geneLine"><header><span>${n}</span><b>${Math.round(near.g[k]*100)}</b></header><div class="bar"><i style="width:${near.g[k]*100}%"></i></div></div>`).join('');ui.lineage.textContent=`Abstammung: ${near.parent}. Alter ${near.age.toFixed(0)} Zyklen · Energie ${near.energy.toFixed(0)}. Tippe außerhalb oder auf × zum Schließen.`;ui.lab.classList.add('show');near.flash=1;beep(760,.04,'sine',.012);return true}
let pointerDown=false,lastApply=0,px=0,py=0;
canvas.addEventListener('pointerdown',e=>{pointerDown=true;px=e.clientX;py=e.clientY;lastApply=performance.now();if(!inspectAt(px,py))apply(px,py)});
canvas.addEventListener('pointermove',e=>{if(!pointerDown)return;px=e.clientX;py=e.clientY;if(performance.now()-lastApply>85){apply(px,py);lastApply=performance.now()}});addEventListener('pointerup',()=>pointerDown=false);addEventListener('pointercancel',()=>pointerDown=false);
document.querySelectorAll('.tool').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;const hints={food:'Tippe oder ziehe, um Nahrung zu verteilen.',heat:'Erzeuge Wärmezonen: nur angepasste Linien bleiben effizient.',toxin:'Setze toxische Zonen: Resistenz wird vererbt und selektiert.',current:'Erzeuge Strömungen: Mobilität und Panzerung werden auf die Probe gestellt.'};ui.hint.textContent=hints[tool];beep(420,.035,'triangle',.012)}));
$('startBtn').addEventListener('click',()=>{audio=new (window.AudioContext||window.webkitAudioContext)();seed();run=true;ui.intro.classList.remove('show');beep(220,.12,'sine',.03);setTimeout(()=>beep(440,.16,'sine',.025),100)});ui.pause.addEventListener('click',()=>{paused=!paused;ui.pause.textContent=paused?'▶':'Ⅱ';if(audio&&audio.state==='suspended')audio.resume()});$('labClose').addEventListener('click',()=>ui.lab.classList.remove('show'));
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();