import{GameState}from'../game/state.js';import{MUSEUM}from'../levels/museum.js';import{HELIX}from'../levels/helix.js';import{CanvasRenderer}from'../renderer/canvas-renderer.js';import{WebGLScene}from'../renderer/webgl-scene.js';import{VectorOverlay}from'../renderer/vector-overlay.js';import{GestureController}from'../input/gesture.js';import{AudioSystem}from'../audio/audio.js';import{UI}from'../ui/ui.js';import{save}from'../persistence/save.js';import{selfTest}from'../tests/selftest.js';
const LEVELS={museum:MUSEUM,helix:HELIX},c=document.querySelector('#game'),sc=document.querySelector('#scene'),g=new GameState(),r=new CanvasRenderer(c),wr=new WebGLScene(sc),vo=new VectorOverlay(c),a=new AudioSystem(),u=new UI();let current='museum',l=false,q=false,s='STEALTH',t=performance.now(),diag=0;
new GestureController(c,{onPreview:(x,y,d)=>r.setPreview(x,y,d),onSwipe:d=>{if(g.mode!=='play')return;a.unlock();g.shift(d);r.gravityPulse();a.shift()}});
function refreshContracts(){const p=save.load();for(const card of document.querySelectorAll('[data-contract]')){const id=card.dataset.contract,unlocked=p.unlocked.includes(id),best=p.bestByHeist[id]||0,btn=card.querySelector('button'),stat=card.querySelector('.contract-stat');card.classList.toggle('locked',!unlocked);btn.disabled=!unlocked;btn.textContent=unlocked?(p.completed.includes(id)?'RUN AGAIN':'INFILTRATE'):'LOCKED';stat.textContent=unlocked?(best?`BEST ${best.toLocaleString()}`:'UNPLAYED'):'COMPLETE AURORA MUSEUM'}}
function start(id=current){if(!LEVELS[id]||!save.isUnlocked(id))return;current=id;a.unlock();g.start(LEVELS[id]);l=q=false;s='STEALTH';u.showPlay(g)}
document.querySelectorAll('[data-contract] button').forEach(btn=>btn.onclick=()=>start(btn.closest('[data-contract]').dataset.contract));document.querySelector('#retry').onclick=()=>start(current);document.querySelector('#resultMenu').onclick=()=>{refreshContracts();u.showMenu()};
function impactMaterial(i){const A=i.a.material||'generic',B=i.b.material||'generic';return B==='armor'||A==='armor'?'armor':B==='metal'||A==='metal'?'metal':B==='glass'||A==='glass'?'glass':B==='stone'||A==='stone'?'stone':A}
function frame(n){const d=Math.min(.033,(n-t)/1000);t=n;if(g.mode==='play'){g.update(d);u.update(g);for(const i of g.impactEvents)if(i.strength>62)a.impact(impactMaterial(i),i.strength);if(g.security.state!==s){s=g.security.state;a.alarm(s)}if(g.hasLoot&&!l){l=true;a.loot();r.gravityPulse()}if(g.complete&&!q){q=true;const z=g.score();save.record(current,z);refreshContracts();a.success();u.showResult(z,g.elapsed,g.shifts,g.security.multiplier(),g)}}wr.render(g,d);r.render(g,d);vo.render(g);if(++diag%60===0)globalThis.__gravityHeistDiagnostics={renderer:wr.getStats(),mode:g.mode,security:g.security?.state,heist:g.level?.id,locks:g.vectorLocks?.map(x=>({id:x.id,open:x.open})),version:'v0007'};requestAnimationFrame(frame)}
refreshContracts();selfTest();requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{t=performance.now();if(document.visibilityState==='visible')a.ctx?.resume?.()});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
