'use strict';
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d',{alpha:false});
const traitsCanvas=document.getElementById('traits'),tctx=traitsCanvas.getContext('2d');
const lineageCanvas=document.getElementById('lineage'),lctx=lineageCanvas.getContext('2d');
const pauseBtn=document.getElementById('pause'),speedBtn=document.getElementById('speed'),resetBtn=document.getElementById('reset');
const missionText=document.getElementById('missionText'),missionMeter=document.getElementById('missionMeter');
const journal=document.getElementById('journal'),specimenEl=document.getElementById('specimen'),hint=document.getElementById('hint'),toast=document.getElementById('toast');
const mPop=document.getElementById('mPop'),mGen=document.getElementById('mGen'),mEco=document.getElementById('mEco'),mBirth=document.getElementById('mBirth');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),paused=false,speed=1,last=performance.now(),acc=0,simTime=0,nextId=1,births=0,selected=null,history=[],won=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const rnd=(a=1,b=0)=>b+Math.random()*(a-b);const TAU=Math.PI*2;
const dirs=Array.from({length:6},(_,i)=>-Math.PI/2+i*Math.PI/3);
let tiles=[],agents=[];
const grid=[[-1,-1],[0,-1],[1,-1],[-1,0],[0,0],[1,0],[-1,1],[0,1],[1,1]];
const tileDefs=[
 {temp:.85,wet:.22,fert:.9,wood:'#a87049',gates:[0,2,3]}, {temp:.65,wet:.38,fert:.72,wood:'#a58a56',gates:[0,1,3]}, {temp:.28,wet:.78,fert:.86,wood:'#718b7f',gates:[0,3,5]},
 {temp:.72,wet:.62,fert:.83,wood:'#8d8455',gates:[1,2,4]}, {temp:.5,wet:.5,fert:.95,wood:'#9b7b57',gates:[0,2,4]}, {temp:.22,wet:.54,fert:.7,wood:'#718a99',gates:[1,3,5]},
 {temp:.58,wet:.3,fert:.68,wood:'#9b7655',gates:[0,2,5]}, {temp:.38,wet:.82,fert:.88,wood:'#6f8f72',gates:[1,3,4]}, {temp:.14,wet:.66,fert:.6,wood:'#8095a2',gates:[0,3,4]}
];
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);[traitsCanvas,lineageCanvas].forEach(c=>{const r=c.getBoundingClientRect();c.width=Math.max(2,r.width*DPR);c.height=Math.max(2,r.height*DPR);c.getContext('2d').setTransform(DPR,0,0,DPR,0,0)});layoutTiles();}
addEventListener('resize',resize);
function layoutTiles(){if(!tiles.length)return;const top=Math.max(118,(parseFloat(getComputedStyle(document.documentElement).fontSize)||16)*6),bottom=72;const availH=H-top-bottom,rad=Math.min(W*.17,availH*.17,82),sx=rad*1.62,sy=rad*1.42,cx=W/2,cy=top+availH/2;tiles.forEach((t,i)=>{const [gx,gy]=grid[i];t.r=rad;t.x=cx+gx*sx+(gy%2?rad*.02:0);t.y=cy+gy*sy;});}
function makeTile(d,i){return {id:i,rot:(Math.random()*6)|0,targetRot:0,temp:d.temp,wet:d.wet,fert:d.fert,color:d.wood,gates:d.gates.slice(),food:Array.from({length:9},()=>({a:rnd(TAU),r:rnd(.58,.15),v:rnd(1,.35)})),x:0,y:0,r:60}}
function mutated(g,scale=.08){return g.map(v=>clamp(v+(Math.random()<.45?rnd(scale,-scale):0),0,1))}
function childGenome(a,b){const g=[];for(let k=0;k<7;k++){let v=Math.random()<.5?a.g[k]:b.g[k];if(Math.random()<.16)v+=rnd(.12,-.12);g[k]=clamp(v,0,1)}return g}
function spawn(tile,g=null,parents=[]){const t=tiles[tile];const o={id:nextId++,tile,ang:rnd(TAU),rad:rnd(.42,.12),g:g||[rnd(.65,.3),rnd(.65,.3),t.temp,t.wet,rnd(.8,.2),rnd(.7,.2),rnd(.8,.2)],energy:rnd(1.35,.98),age:0,gen:parents.length?Math.max(...parents.map(p=>p.gen))+1:0,parents:parents.map(p=>p.id),offspring:0,cool:rnd(4,0),dir:(Math.random()*6)|0,progress:rnd(),alive:true,lastTile:tile};agents.push(o);return o}
function reset(){simTime=0;nextId=1;births=0;selected=null;history=[];won=false;tiles=tileDefs.map(makeTile);layoutTiles();agents=[];for(let i=0;i<tiles.length;i++)for(let n=0;n<7;n++)spawn(i,mutated([.46,.45,tiles[i].temp,tiles[i].wet,.5,.45,.5],.12));updateNetworks();toastMsg('The living board is reset. Twist habitats to rewire migration.');updateJournal(stats());}
function gateWorldDir(tile,gate){return (gate+tile.rot)%6}
function neighborFor(tile,worldDir){const i=tile.id,[gx,gy]=grid[i];let best=null,bd=1e9;const ang=dirs[worldDir],tx=tile.x+Math.cos(ang)*tile.r*1.55,ty=tile.y+Math.sin(ang)*tile.r*1.55;for(const o of tiles){if(o===tile)continue;const d=Math.hypot(o.x-tx,o.y-ty);if(d<bd){bd=d;best=o}}return bd<tile.r*.9?best:null}
function hasGateWorld(tile,worldDir){return tile.gates.some(g=>gateWorldDir(tile,g)===worldDir)}
function connectedNeighbor(tile,worldDir){if(!hasGateWorld(tile,worldDir))return null;const n=neighborFor(tile,worldDir);if(!n)return null;return hasGateWorld(n,(worldDir+3)%6)?n:null}
function updateNetworks(){tiles.forEach(t=>t.links=[]);for(const t of tiles)for(let d=0;d<6;d++){const n=connectedNeighbor(t,d);if(n)t.links.push({dir:d,to:n.id})}}
function fitness(o,t){const climate=clamp(1-Math.abs(o.g[2]-t.temp)*.8-Math.abs(o.g[3]-t.wet)*.72,.05,1);const width=o.g[0],pace=o.g[1];const cost=.0016+.003*width+.004*pace*pace;return {climate,cost}}
function chooseLink(o,t){if(!t.links.length)return null;let best=null,score=-99;for(const l of t.links){const n=tiles[l.to];const climate=1-Math.abs(o.g[2]-n.temp)*.8-Math.abs(o.g[3]-n.wet)*.72;const novelty=(l.to===o.lastTile?-1:1)*o.g[5];const turnDist=Math.min((l.dir-o.dir+6)%6,(o.dir-l.dir+6)%6)/3;const turnPref=(1-turnDist)*(o.g[6]-.5);const memory=o.g[4]*(l.to===o.lastTile?-.35:.15);const s=climate*.8+novelty*.35+turnPref*.3+memory+rnd(.22,-.22);if(s>score){score=s;best=l}}return best}
function step(dt){simTime+=dt;updateNetworks();for(const t of tiles)for(const f of t.food)f.v=clamp(f.v+dt*.06*t.fert,0,1);
 for(const o of agents){if(!o.alive)continue;const t=tiles[o.tile],F=fitness(o,t);o.age+=dt;o.cool-=dt;const pace=.07+.11*o.g[1];o.progress+=dt*pace*(.55+F.climate*.65);o.energy-=F.cost*dt*(1.25-F.climate*.35);
  if(o.progress>=1){o.progress-=1;const link=chooseLink(o,t);if(link&&Math.random()<.3+.55*o.g[5]){o.lastTile=o.tile;o.tile=link.to;o.dir=link.dir;o.energy-=.018+.02*o.g[0]}else{o.dir=(o.dir+(Math.random()<.5?1:5))%6}}
  const nt=tiles[o.tile];let best=null,bd=9;for(const f of nt.food){if(f.v<.08)continue;const d=Math.abs(Math.sin(f.a-o.ang))*f.r;if(d<bd){bd=d;best=f}}if(best&&Math.random()<dt*(2.0+o.g[0]*2.0)){const nf=fitness(o,nt);const bite=Math.min(best.v,.13*dt*(.7+o.g[0]));best.v-=bite;o.energy+=bite*1.05*nf.climate}
  o.ang+=(o.g[6]-.5)*dt*.7+rnd(.08,-.08);o.rad=clamp(o.rad+rnd(.012,-.012),.08,.58);o.energy=clamp(o.energy,0,2.1);
  if(o.energy<=0||o.age>150+rnd(70)){o.alive=false;continue}
  if(o.energy>1.12&&o.age>1.8&&o.cool<=0){let mate=null;for(const m of agents){if(m===o||!m.alive||m.tile!==o.tile||m.energy<1.05||m.cool>0)continue;const signal=Math.abs(m.g[6]-o.g[6]);if(signal<.28){mate=m;break}}if(mate&&agents.filter(a=>a.alive).length<190){const c=spawn(o.tile,childGenome(o,mate),[o,mate]);c.energy=.72;c.ang=(o.ang+mate.ang)/2;c.rad=(o.rad+mate.rad)/2;o.energy-=.27;mate.energy-=.21;o.cool=mate.cool=3.2;o.offspring++;mate.offspring++;births++}}
 }
 agents=agents.filter(a=>a.alive||a===selected);if(history.length===0||simTime-history.at(-1).t>2){const s=stats();history.push({t:simTime,p:s.pop,e:s.ecotypes,g:s.maxGen});if(history.length>100)history.shift();updateJournal(s)}
}
function dist(a,b){let s=0;for(let i=0;i<a.length;i++)s+=Math.abs(a[i]-b[i]);return s/a.length}
function stats(){const alive=agents.filter(a=>a.alive);const means=tiles.map(t=>{const arr=alive.filter(a=>a.tile===t.id);return arr.length?Array.from({length:7},(_,k)=>arr.reduce((s,a)=>s+a.g[k],0)/arr.length):null});let groups=[];for(const m of means){if(!m)continue;let found=groups.find(g=>dist(g,m)<.11);if(found){for(let k=0;k<7;k++)found[k]=(found[k]+m[k])/2}else groups.push(m.slice())}return {pop:alive.length,maxGen:alive.reduce((m,a)=>Math.max(m,a.gen),0),ecotypes:groups.length,means}}
function updateJournal(s){mPop.textContent=s.pop;mGen.textContent=s.maxGen;mEco.textContent=s.ecotypes;mBirth.textContent=births;drawTraits();drawLineage();const p=clamp((s.ecotypes-1)/2,0,1);missionMeter.style.width=(p*100)+'%';if(s.ecotypes>=3){missionText.textContent='Three ecotypes detected. Keep all three alive while opening at least one bridge between each region.';const linked=tiles.reduce((n,t)=>n+t.links.length,0);if(linked>=10&&s.pop>45&&!won){won=true;missionMeter.style.width='100%';toastMsg('FIELD STUDY COMPLETE — topology created divergence, then controlled reconnection preserved it.')}}}
function drawTraits(){const r=traitsCanvas.getBoundingClientRect(),w=r.width,h=r.height;tctx.clearRect(0,0,w,h);const labels=['WIDTH','PACE','HEAT','WET','MEMORY','ROAM','TURN'];const colors=['#9a553a','#67794c','#bd7a42','#4f7f87','#765f91','#8b7a45','#a15f73'];for(let k=0;k<7;k++){const y=11+k*14;tctx.fillStyle='#ddd0b9';tctx.fillRect(58,y,w-70,6);const vals=agents.filter(a=>a.alive).map(a=>a.g[k]);const m=vals.length?vals.reduce((x,y)=>x+y,0)/vals.length:0;tctx.fillStyle=colors[k];tctx.fillRect(58,y,(w-70)*m,6);tctx.fillStyle='#6b6457';tctx.font='8px system-ui';tctx.fillText(labels[k],7,y+6)}}
function drawLineage(){const r=lineageCanvas.getBoundingClientRect(),w=r.width,h=r.height;lctx.clearRect(0,0,w,h);lctx.strokeStyle='#c9bba4';lctx.beginPath();lctx.moveTo(8,h-18);lctx.lineTo(w-8,h-18);lctx.stroke();if(history.length<2)return;const maxP=Math.max(60,...history.map(x=>x.p));lctx.strokeStyle='#8e4d35';lctx.lineWidth=2;lctx.beginPath();history.forEach((d,i)=>{const x=8+i/(history.length-1)*(w-16),y=h-18-d.p/maxP*(h-26);i?lctx.lineTo(x,y):lctx.moveTo(x,y)});lctx.stroke();lctx.fillStyle='#6b6457';lctx.font='8px system-ui';lctx.fillText('POPULATION / GENERATIONAL HISTORY',8,11)}
function showSpecimen(o){if(!o){specimenEl.textContent='Tap a creature to pin its ancestry and current physiological state.';return}specimenEl.innerHTML=`<b>Creature #${o.id}</b> · tile ${o.tile+1}<br>generation ${o.gen} · age ${o.age.toFixed(1)} · energy ${o.energy.toFixed(2)} · offspring ${o.offspring}<br>parents ${o.parents.length?o.parents.join(' + '):'founder'}<br>genome ${o.g.map(v=>v.toFixed(2)).join(' · ')}`}
function hexPath(x,y,r,rot=0){ctx.beginPath();for(let i=0;i<6;i++){const a=-Math.PI/2+i*Math.PI/3+rot,xp=x+Math.cos(a)*r,yp=y+Math.sin(a)*r;i?ctx.lineTo(xp,yp):ctx.moveTo(xp,yp)}ctx.closePath()}
function drawTile(t){ctx.save();ctx.shadowColor='rgba(48,38,24,.18)';ctx.shadowBlur=15;ctx.shadowOffsetY=7;hexPath(t.x,t.y,t.r);ctx.fillStyle=t.color;ctx.fill();ctx.shadowColor='transparent';ctx.lineWidth=3;ctx.strokeStyle='rgba(255,248,231,.7)';ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='rgba(65,55,42,.35)';ctx.stroke();
 for(const g of t.gates){const d=gateWorldDir(t,g),a=dirs[d],x2=t.x+Math.cos(a)*t.r*.93,y2=t.y+Math.sin(a)*t.r*.93;ctx.strokeStyle='rgba(237,225,194,.82)';ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='rgba(85,72,54,.32)';ctx.lineWidth=1.2;ctx.stroke()}
 for(const f of t.food){if(f.v<.06)continue;const x=t.x+Math.cos(f.a)*f.r*t.r*.74,y=t.y+Math.sin(f.a)*f.r*t.r*.74;ctx.fillStyle=`rgba(232,207,111,${.18+f.v*.65})`;ctx.beginPath();ctx.arc(x,y,1.8+f.v*2.4,0,TAU);ctx.fill()}
 ctx.fillStyle='rgba(45,40,32,.68)';ctx.font='700 9px Georgia';ctx.textAlign='center';ctx.fillText(`${Math.round(t.temp*100)}° / ${Math.round(t.wet*100)}%`,t.x,t.y+t.r*.62);ctx.restore()}
function agentPos(o){const t=tiles[o.tile],a=o.ang+o.progress*.5;return {x:t.x+Math.cos(a)*o.rad*t.r*.72,y:t.y+Math.sin(a)*o.rad*t.r*.72}}
function drawAgent(o){if(!o.alive)return;const p=agentPos(o),sz=2.8+o.g[0]*4.2,h=26+o.g[6]*180;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(o.ang);ctx.fillStyle=`hsl(${h} 42% ${37+o.g[2]*20}%)`;ctx.strokeStyle=o===selected?'#fff7df':'rgba(48,40,30,.6)';ctx.lineWidth=o===selected?2.5:1;ctx.beginPath();ctx.roundRect(-sz,-sz*.55,sz*2,sz*1.1,sz*.55);ctx.fill();ctx.stroke();ctx.fillStyle='#fff3d6';ctx.beginPath();ctx.arc(sz*.55,-sz*.12,1,0,TAU);ctx.fill();ctx.restore()}
function render(){ctx.fillStyle='#d9cfb8';ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle='#7d715e';for(let y=0;y<H;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.restore();tiles.forEach(drawTile);agents.forEach(drawAgent);if(gesture?.tile&&gesture.active){const t=gesture.tile;ctx.strokeStyle='rgba(255,248,231,.8)';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.arc(t.x,t.y,t.r*1.05,0,TAU);ctx.stroke();ctx.setLineDash([])}}
function loop(t){const raw=Math.min(.05,(t-last)/1000);last=t;if(!paused){acc+=raw*speed;while(acc>.033){step(.033);acc-=.033}}render();requestAnimationFrame(loop)}
function tileAt(x,y){let best=null,bd=1e9;for(const t of tiles){const d=Math.hypot(x-t.x,y-t.y);if(d<t.r*.92&&d<bd){best=t;bd=d}}return best}
function nearestAgent(x,y){let best=null,bd=18;for(const o of agents){if(!o.alive)continue;const p=agentPos(o),d=Math.hypot(x-p.x,y-p.y);if(d<bd){bd=d;best=o}}return best}
let gesture=null;
function angleAt(t,x,y){return Math.atan2(y-t.y,x-t.x)}
function startGesture(x,y,id,type='touch'){const t=tileAt(x,y);gesture={id,type,tile:t,startX:x,startY:y,lastX:x,lastY:y,startAng:t?angleAt(t,x,y):0,startRot:t?t.rot:0,active:false,moved:false}}
function moveGesture(x,y){if(!gesture)return;gesture.lastX=x;gesture.lastY=y;const d=Math.hypot(x-gesture.startX,y-gesture.startY);if(d>8)gesture.moved=true;if(gesture.tile&&gesture.moved){gesture.active=true;const a=angleAt(gesture.tile,x,y),delta=a-gesture.startAng;const steps=Math.round(delta/(Math.PI/3));gesture.tile.rot=((gesture.startRot+steps)%6+6)%6;updateNetworks();hint.style.opacity=0}}
function endGesture(cancel=false){if(!gesture)return;const g=gesture;gesture=null;if(cancel)return;if(g.tile&&g.moved){navigator.vibrate?.(14);updateNetworks();return}const o=nearestAgent(g.startX,g.startY);if(o){selected=o;showSpecimen(o);journal.classList.add('open');hint.style.opacity=0;navigator.vibrate?.(7)}}
canvas.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;e.preventDefault();const t=e.touches[0];startGesture(t.clientX,t.clientY,t.identifier,'touch')},{passive:false});
canvas.addEventListener('touchmove',e=>{if(!gesture||gesture.type!=='touch')return;let t=null;for(const x of e.touches)if(x.identifier===gesture.id)t=x;if(!t)return;e.preventDefault();moveGesture(t.clientX,t.clientY)},{passive:false});
canvas.addEventListener('touchend',e=>{if(gesture?.type==='touch'){e.preventDefault();endGesture(false)}},{passive:false});canvas.addEventListener('touchcancel',e=>{if(gesture?.type==='touch'){e.preventDefault();endGesture(true)}},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;canvas.setPointerCapture?.(e.pointerId);startGesture(e.clientX,e.clientY,e.pointerId,'pointer')});canvas.addEventListener('pointermove',e=>{if(gesture?.type==='pointer'&&gesture.id===e.pointerId)moveGesture(e.clientX,e.clientY)});canvas.addEventListener('pointerup',e=>{if(gesture?.type==='pointer'&&gesture.id===e.pointerId)endGesture(false)});canvas.addEventListener('pointercancel',e=>{if(gesture?.type==='pointer'&&gesture.id===e.pointerId)endGesture(true)});
let js=null;journal.addEventListener('touchstart',e=>{js=e.touches[0]?.clientY??null},{passive:true});journal.addEventListener('touchend',e=>{if(js==null)return;const y=e.changedTouches[0]?.clientY??js,dy=y-js;if(dy<-30)journal.classList.add('open');if(dy>30)journal.classList.remove('open');js=null},{passive:true});
pauseBtn.onclick=()=>{paused=!paused;pauseBtn.textContent=paused?'▶':'Ⅱ'};speedBtn.onclick=()=>{speed=speed===1?3:speed===3?7:1;speedBtn.textContent=speed+'×'};resetBtn.onclick=reset;
function toastMsg(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)}
resize();reset();requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.__turnwildTest={stats,reset,getTiles:()=>tiles.map(t=>({id:t.id,rot:t.rot,links:t.links.map(x=>x.to)})),getAgents:()=>agents.filter(a=>a.alive).map(a=>({id:a.id,gen:a.gen,tile:a.tile,energy:a.energy})),rotate:(id,steps=1)=>{tiles[id].rot=((tiles[id].rot+steps)%6+6)%6;updateNetworks();},step:(seconds=1)=>{for(let i=0;i<seconds*30;i++)step(1/30);return stats();}};
