import{CFG}from'../config.js';import{PhysicsWorld}from'../physics/world.js';import{SecuritySystem}from'../security/security.js';import{MUSEUM}from'../levels/museum.js';const near=(a,b,d)=>Math.hypot(a.x-b.x,a.y-b.y)<d;
export class GameState{
constructor(level=MUSEUM){this.selectedLevel=level;this.mode='menu';this.reset(level)}
reset(level=this.selectedLevel){this.selectedLevel=level;this.level=level;this.world=new PhysicsWorld();this.vectorLocks=(level.vectorLocks||[]).map(l=>({...l,open:false,door:{...l.door}}));this.rebuildSolids();this.security=new SecuritySystem(level.security);this.player=this.world.add({...level.spawn,r:18,restitution:.12,type:'player',mass:1.1,material:'fabric'});this.loot=this.world.add({...level.loot,r:14,restitution:.35,type:'loot',mass:.65,material:'glass'});this.bonus=level.bonus?this.world.add({...level.bonus,restitution:.42,type:'bonus',mass:.6,material:'glass'}):null;this.props=(level.props||[]).map(p=>this.world.add({...p}));this.security.bindWorld(this.world);this.exit={...level.exit};this.heat=0;this.shifts=0;this.hasLoot=false;this.hasBonus=false;this.elapsed=0;this.complete=false;this.mode='menu';this.alertPulse=0;this.impactPulse=0;this.impactCount=0;this.lockScore=0;this.impactEvents=[]}
rebuildSolids(){const closed=this.vectorLocks.filter(l=>!l.open).map(l=>l.door);this.world.setSolids([...(this.level.solids||[]),...closed]);if(this.security)this.security.refreshSolids(this.world.solids)}
start(level=this.selectedLevel){this.reset(level);this.mode='play'}
select(level){this.selectedLevel=level;this.reset(level)}
shift(d){if(this.mode!=='play')return;this.world.setGravity(d);this.heat=Math.min(CFG.maxHeat,this.heat+CFG.heatPerShift);this.security.trip('GRAVITY',2.2);this.shifts++;for(const l of this.vectorLocks)if(!l.open&&l.dir===d&&near(this.player,l,74)){l.open=true;this.lockScore+=450;this.rebuildSolids();this.security.trip('VECTOR_LOCK',5);this.alertPulse=1}}
update(dt){this.impactEvents=[];if(this.mode!=='play')return;this.elapsed+=dt;const impacts=this.world.step(dt);for(const impact of impacts){this.impactEvents.push(impact);this.security.impact(impact);if(impact.a.type==='player'||impact.b.type==='player'){this.impactPulse=Math.max(this.impactPulse,Math.min(1,impact.strength/260));this.heat=Math.min(100,this.heat+Math.min(4,impact.strength*.008))}if(impact.strength>85)this.impactCount++}const p=this.security.state;this.security.update(dt,this.player,this.heat);if(p!==this.security.state)this.alertPulse=1;this.alertPulse=Math.max(0,this.alertPulse-dt*2);this.impactPulse=Math.max(0,this.impactPulse-dt*3.8);this.heat=Math.min(100,Math.max(0,this.heat-dt*CFG.heatDecay)+dt*this.security.alert*.025);if(this.bonus&&!this.hasBonus&&near(this.player,this.bonus,34)){this.hasBonus=true;this.bonus.dynamic=false;this.bonus.hidden=true;this.heat=Math.min(100,this.heat+10);this.security.trip('BONUS',8)}if(!this.hasLoot&&near(this.player,this.loot,42)){this.hasLoot=true;this.loot.dynamic=false;this.loot.hidden=true;this.security.trip('LOOT',18)}if(this.hasLoot){this.loot.x=this.player.x+24;this.loot.y=this.player.y-24}if(this.hasLoot&&near(this.player,this.exit,44)){this.complete=true;this.mode='result'}}
score(){const bonus=this.hasBonus?1800:0,style=Math.min(900,this.impactCount*45),base=this.level.baseScore||10000;return Math.round((Math.max(1000,base-this.elapsed*55-this.shifts*90-this.heat*5)+bonus+style+this.lockScore)*this.security.multiplier())}
locksOpen(){return this.vectorLocks.filter(l=>l.open).length}
}
