const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class SecuritySystem{
constructor(){this.reset()}
reset(){this.alert=0;this.state='STEALTH';this.lasers=[{x1:300,y1:80,x2:300,y2:245,phase:0},{x1:618,y1:210,x2:850,y2:210,phase:1.7},{x1:740,y1:300,x2:740,y2:485,phase:3.1}];this.guards=[{x:365,y:112,r:17,vx:36,vy:0,axis:'x',min:330,max:560,dir:1,seen:0,patrolSpeed:36},{x:845,y:458,r:17,vx:0,vy:-30,axis:'y',min:300,max:472,dir:-1,seen:0,patrolSpeed:30}];this.bound=false}
bindWorld(world){if(this.bound)return;this.guards=this.guards.map((g,i)=>world.add({...g,type:'guard',mass:1.25,restitution:.16,guardId:i}));this.bound=true}
trip(k,a=18){this.alert=clamp(this.alert+a,0,100)}
update(dt,p,h){this.alert=Math.max(0,this.alert-dt*(h>70?.7:1.45));for(const g of this.guards){const s=this.alert>65?1.65:1,target=g.patrolSpeed*g.dir*s,assist=1-Math.exp(-2.8*dt);if(g.axis==='x'){g.vx+=(target-g.vx)*assist;if(g.x<g.min){g.dir=1;g.vx=Math.max(g.vx,18)}else if(g.x>g.max){g.dir=-1;g.vx=Math.min(g.vx,-18)}}else{g.vy+=(target-g.vy)*assist;if(g.y<g.min){g.dir=1;g.vy=Math.max(g.vy,16)}else if(g.y>g.max){g.dir=-1;g.vy=Math.min(g.vy,-16)}}const d=Math.hypot(p.x-g.x,p.y-g.y);if(d<150){g.seen=Math.min(1,g.seen+dt*1.8);if(g.seen>.72){this.trip('GUARD',dt*25);g.seen=.45}}else g.seen=Math.max(0,g.seen-dt*1.5)}for(const l of this.lasers)if(pointSeg(p.x,p.y,l.x1,l.y1,l.x2,l.y2)<p.r+4&&Math.sin(performance.now()/480+l.phase)>.05)this.trip('LASER',dt*34);this.state=this.alert>82?'LOCKDOWN':this.alert>50?'ALERT':this.alert>20?'SUSPICIOUS':'STEALTH'}
impact(impact){const{a,b,strength}=impact,ga=a.type==='guard',gb=b.type==='guard';if(!ga&&!gb)return;const other=ga?b:a;if(other.type==='player'){this.trip('GUARD_IMPACT',Math.min(24,6+strength*.035));this.alert=Math.max(this.alert,34)}else if(strength>100)this.trip('CHAOS_IMPACT',Math.min(12,strength*.02))}
multiplier(){return 1+Math.min(.75,this.alert/135)}}
function pointSeg(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,c1=wx*vx+wy*vy,c2=vx*vx+vy*vy,t=c2?clamp(c1/c2,0,1):0;return Math.hypot(px-(x1+t*vx),py-(y1+t*vy))}
