const frame=document.querySelector('#appFrame');
const logEl=document.querySelector('#log');
const resultEl=document.querySelector('#result');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const log=(msg,data)=>{const line=document.createElement('div');line.textContent=data===undefined?msg:`${msg} ${JSON.stringify(data)}`;logEl.appendChild(line)};
async function waitFor(fn,timeout=6000,step=50){const end=performance.now()+timeout;while(performance.now()<end){try{const v=fn();if(v)return v}catch{}await sleep(step)}throw Error('timeout waiting for '+(fn.name||'condition'))}
function swipe(win,canvas,dx=150,dy=0){const rect=canvas.getBoundingClientRect(),x=rect.left+rect.width*.45,y=rect.top+rect.height*.56,id=17,base={bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',isPrimary:true,buttons:1,clientX:x,clientY:y};canvas.dispatchEvent(new win.PointerEvent('pointerdown',base));canvas.dispatchEvent(new win.PointerEvent('pointermove',{...base,clientX:x+dx,clientY:y+dy}));canvas.dispatchEvent(new win.PointerEvent('pointerup',{...base,buttons:0,clientX:x+dx,clientY:y+dy}))}
function assert(name,value,details,checks){checks.push({name,ok:!!value,details});if(!value)throw Error(`${name} failed${details?`: ${JSON.stringify(details)}`:''}`);log('PASS '+name,details)}
async function run(){const checks=[];try{await waitFor(()=>frame.contentWindow?.__gravityHeistTestAPI,8000);const win=frame.contentWindow,doc=win.document,api=win.__gravityHeistTestAPI;assert('build-v0017',api.build==='v0017',{build:api.build},checks);api.start('museum');await waitFor(()=>api.game.mode==='play',2500);await sleep(1700);const canvas=api.canvas,scene=api.scene,vis=api.getVisibility(),rect=canvas.getBoundingClientRect(),gs=getComputedStyle(canvas),ss=getComputedStyle(scene);assert('canvas-sized',canvas.width>=640&&canvas.height>=300,{width:canvas.width,height:canvas.height,css:[rect.width,rect.height]},checks);assert('hud-visible',!doc.querySelector('#hud').classList.contains('hidden'),{},checks);assert('menu-hidden',doc.querySelector('#menu').classList.contains('hidden'),{},checks);assert('canvas-safe-mode',api.getRenderMode()==='canvas-safe',{mode:api.getRenderMode()},checks);assert('scene-hidden',ss.display==='none',{display:ss.display},checks);assert('game-above-scene',(parseInt(gs.zIndex)||0)>(parseInt(ss.zIndex)||0),{gameZ:gs.zIndex,sceneZ:ss.zIndex},checks);assert('player-pixel-visible',vis?.ok===true,vis,checks);const before={x:api.game.player.x,y:api.game.player.y,shifts:api.game.shifts};swipe(win,canvas,170,0);await waitFor(()=>api.game.shifts>before.shifts,1800);await sleep(650);const after={x:api.game.player.x,y:api.game.player.y,shifts:api.game.shifts};const moved=Math.hypot(after.x-before.x,after.y-before.y);assert('pointer-swipe-shifted-gravity',after.shifts===before.shifts+1,{before,after},checks);assert('player-moved-after-shift',moved>8,{moved:+moved.toFixed(2),before,after},checks);await sleep(800);const visAfter=api.forceVisibilityCheck();assert('player-still-visible-after-motion',visAfter?.ok===true,visAfter,checks);const result={ok:true,version:'v0017',checks,renderMode:api.getRenderMode(),visibility:visAfter,movement:+moved.toFixed(2)};win.__gravityHeistSmokeResult=result;globalThis.__gravityHeistSmokeResult=result;resultEl.textContent='PASS · gameplay visible and interactive';resultEl.dataset.state='pass';log('SMOKE RESULT',result)}catch(err){const result={ok:false,version:'v0017',error:String(err),checks};globalThis.__gravityHeistSmokeResult=result;resultEl.textContent='FAIL · '+err.message;resultEl.dataset.state='fail';log('SMOKE RESULT',result);console.error(err)}}
frame.addEventListener('load',run,{once:true});
