const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
export function projectWorldPoint(view,x,y){return{x:(view?.ox||0)+x*(view?.s||1),y:(view?.oy||0)+y*(view?.s||1)}}
export function evaluateVisibilityEvidence(e={}){const sizeOk=(e.canvasWidth||0)>=320&&(e.canvasHeight||0)>=180;const playerOk=!!e.playerInside&&(e.playerMaxLum||0)>=135&&(e.playerContrast||0)>=45;const layerOk=!!e.layerSafe;return{ok:sizeOk&&playerOk&&layerOk,sizeOk,playerOk,layerOk}}
function lum(r,g,b){return .2126*r+.7152*g+.0722*b}
function patchStats(ctx,x,y,r=14){const c=ctx.canvas,w=c.width,h=c.height,x0=clamp(Math.floor(x-r),0,w-1),y0=clamp(Math.floor(y-r),0,h-1),x1=clamp(Math.ceil(x+r),x0+1,w),y1=clamp(Math.ceil(y+r),y0+1,h),img=ctx.getImageData(x0,y0,x1-x0,y1-y0).data;let lo=255,hi=0,opaque=0;for(let i=0;i<img.length;i+=4){const a=img[i+3];if(a<20)continue;opaque++;const l=lum(img[i],img[i+1],img[i+2]);if(l<lo)lo=l;if(l>hi)hi=l}if(!opaque)return{maxLum:0,contrast:0,opaque:0};return{maxLum:+hi.toFixed(1),contrast:+(hi-lo).toFixed(1),opaque}}
function layerEvidence(canvas,scene){const gs=getComputedStyle(canvas),ss=scene?getComputedStyle(scene):null,gz=Number.parseInt(gs.zIndex,10)||0,sz=ss?(Number.parseInt(ss.zIndex,10)||0):-1,sceneHidden=!scene||ss.display==='none'||ss.visibility==='hidden';return{safe:sceneHidden||gz>sz,gameZ:gz,sceneZ:sz,sceneHidden,scenePointer:ss?.pointerEvents||null,sceneBlend:ss?.mixBlendMode||null}}
export class VisibilityGuard{
  constructor(canvas,renderer,scene){this.canvas=canvas;this.renderer=renderer;this.scene=scene;this.frames=0;this.checks=0;this.failures=0;this.recoveries=0;this.last=null;this.banner=null;this.lastMode=document.documentElement.dataset.renderMode||'unknown'}
  forceCanvasSafe(reason){document.documentElement.dataset.renderMode='canvas-safe';if(this.scene)this.scene.style.display='none';this.renderer.setGpuBackdrop(false);this.recoveries++;this.lastMode='canvas-safe';globalThis.__gravityHeistVisibilityRecovery={reason,at:performance.now(),recoveries:this.recoveries};console.warn('GRAVITY HEIST visibility recovery -> canvas-safe',reason)}
  showFailure(message){if(this.banner)return;const el=document.createElement('div');el.id='renderFailSafe';el.textContent=message;Object.assign(el.style,{position:'fixed',left:'50%',top:'50%',transform:'translate(-50%,-50%)',zIndex:'9999',padding:'14px 18px',borderRadius:'12px',background:'rgba(45,8,12,.96)',border:'1px solid #ff6b7d',color:'#fff',font:'800 12px -apple-system,sans-serif',letterSpacing:'.08em',textAlign:'center',pointerEvents:'none'});document.body.appendChild(el);this.banner=el}
  inspect(g,view){const ctx=this.canvas.getContext('2d'),p=projectWorldPoint(view,g.player.x,g.player.y),inside=p.x>=0&&p.x<this.canvas.width&&p.y>=0&&p.y<this.canvas.height,patch=patchStats(ctx,p.x,p.y,Math.max(12,Math.min(26,(g.player.r||18)*(view?.s||1)*1.25))),layer=layerEvidence(this.canvas,this.scene),raw={canvasWidth:this.canvas.width,canvasHeight:this.canvas.height,playerInside:inside,playerX:+p.x.toFixed(1),playerY:+p.y.toFixed(1),playerMaxLum:patch.maxLum,playerContrast:patch.contrast,playerOpaque:patch.opaque,layerSafe:layer.safe,...layer,mode:document.documentElement.dataset.renderMode||'unknown'},verdict=evaluateVisibilityEvidence(raw);this.last={...raw,...verdict};this.checks++;globalThis.__gravityHeistVisibility=this.last;return this.last}
  tick(g,view){if(g.mode!=='play'||!view)return this.last;if(++this.frames<45||this.frames%90!==0)return this.last;let result;try{result=this.inspect(g,view)}catch(err){result={ok:false,error:String(err)};this.last=result;this.checks++;globalThis.__gravityHeistVisibility=result}if(result.ok){if(this.banner){this.banner.remove();this.banner=null}return result}this.failures++;const mode=document.documentElement.dataset.renderMode||'unknown';if(mode!=='canvas-safe'){this.forceCanvasSafe(result);return result}if(this.failures>=2)this.showFailure('RENDER RECOVERY ACTIVE · GAMEPLAY VISIBILITY CHECK FAILED');return result}
  getStats(){return{checks:this.checks,failures:this.failures,recoveries:this.recoveries,lastMode:document.documentElement.dataset.renderMode||this.lastMode,last:this.last}}
}
export function visibilityLogicSelfTest(){let n=0;const ok=(v)=>{if(!v)throw Error('VISIBILITY SELFTEST');n++};const p=projectWorldPoint({ox:10,oy:20,s:2},5,7);ok(p.x===20&&p.y===34);ok(evaluateVisibilityEvidence({canvasWidth:800,canvasHeight:400,playerInside:true,playerMaxLum:210,playerContrast:90,layerSafe:true}).ok);ok(!evaluateVisibilityEvidence({canvasWidth:800,canvasHeight:400,playerInside:true,playerMaxLum:40,playerContrast:10,layerSafe:true}).ok);ok(!evaluateVisibilityEvidence({canvasWidth:800,canvasHeight:400,playerInside:true,playerMaxLum:210,playerContrast:90,layerSafe:false}).ok);console.info(`GRAVITY HEIST visibility logic: ${n} checks passed`);return n}
