const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const normAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
const DEFAULT={lasers:[{x1:300,y1:80,x2:300,y2:245,phase:0},{x1:618,y1:210,x2:850,y2:210,phase:1.7},{x1:740,y1:300,x2:740,y2:485,phase:3.1}],guards:[{x:365,y:112,r:17,vx:36,vy:0,axis:'x',min:330,max:560,dir:1,seen:0,patrolSpeed:36},{x:845,y:458,r:17,vx:0,vy:-30,axis:'y',min:300,max:472,dir:-1,seen:0,patrolSpeed:30}]};
export function guardFacing(g){const speed=Math.hypot(g.vx||0,g.vy||0);if(speed>8)return Math.atan2(g.vy,g.vx);return g.axis==='x'?(g.dir>0?0:Math.PI):(g.dir>0?Math.PI/2:-Math.PI/2)}
export function lineBlocked(a,b,solids=[]){for(const s of solids)if(segmentHitsRect(a.x,a.y,b.x,b.y,s.x,s.y,s.w,s.h))return true;return false}
export function guardCanSee(g,p,solids=[],range=165,halfFov=.48){const dx=p.x-g.x,dy=p.y-g.y,d=Math.hypot(dx,dy);if(d>range||d<1)return false;const da=Math.abs(normAngle(Math.atan2(dy,dx)-guardFacing(g)));return da<=halfFov&&!lineBlocked(g,p,solids)}
export class SecuritySystem{
constructor(profile=DEFAULT){this.profile=profile||DEFAULT;this.reset()}
reset(){this.alert=0;this.state='STEALTH';this.lasers=(this.profile.lasers||DEFAULT.lasers).map(x=>({...x}));this.guards=(this.profile.guards||DEFAULT.guards).map(x=>({...x}));this.bound=false;this.solids=[]}
bindWorld(world){if(this.bound)return;this.solids=world.solids;this.guards=this.guards.map((g,i)=>world.add({...g,type:'guard',mass:1.25,restitution:.16,material:'armor',guardId:i,visible:false,occluded:false}));this.bound=true}
refreshSolids(solids){this.solids=solids}
trip(k,a=18){this.alert=clamp(this.alert+a,0,100)}
update(dt,p,h){this.alert=Math.max(0,this.alert-dt*(h>70?.7:1.45));for(const g of this.guards){const s=this.alert>65?1.65:1,target=g.patrolSpeed*g.dir*s,assist=1-Math.exp(-2.8*dt);if(g.axis==='x'){g.vx+=(target-g.vx)*assist;if(g.x<g.min){g.dir=1;g.vx=Math.max(g.vx,18)}else if(g.x>g.max){g.dir=-1;g.vx=Math.min(g.vx,-18)}}else{g.vy+=(target-g.vy)*assist;if(g.y<g.min){g.dir=1;g.vy=Math.max(g.vy,16)}else if(g.y>g.max){g.dir=-1;g.vy=Math.min(g.vy,-16)}}const d=Math.hypot(p.x-g.x,p.y-g.y),inRange=d<165,blocked=inRange&&lineBlocked(g,p,this.solids);g.occluded=blocked;g.visible=guardCanSee(g,p,this.solids);if(g.visible){g.seen=Math.min(1,g.seen+dt*(this.alert>50?2.5:1.9));if(g.seen>.72){this.trip('GUARD',dt*28);g.seen=.48}}else g.seen=Math.max(0,g.seen-dt*(blocked?2.4:1.65))}for(const l of this.lasers)if(pointSeg(p.x,p.y,l.x1,l.y1,l.x2,l.y2)<p.r+4&&Math.sin(performance.now()/480+l.phase)>.05)this.trip('LASER',dt*34);this.state=this.alert>82?'LOCKDOWN':this.alert>50?'ALERT':this.alert>20?'SUSPICIOUS':'STEALTH'}
impact(impact){const{a,b,strength}=impact,ga=a.type==='guard',gb=b.type==='guard';if(!ga&&!gb)return;const other=ga?b:a;if(other.type==='player'){this.trip('GUARD_IMPACT',Math.min(24,6+strength*.035));this.alert=Math.max(this.alert,34)}else if(strength>100)this.trip('CHAOS_IMPACT',Math.min(12,strength*.02))}
multiplier(){return 1+Math.min(.75,this.alert/135)}}
function pointSeg(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,c1=wx*vx+wy*vy,c2=vx*vx+vy*vy,t=c2?clamp(c1/c2,0,1):0;return Math.hypot(px-(x1+t*vx),py-(y1+t*vy))}
function segmentHitsRect(x1,y1,x2,y2,rx,ry,rw,rh){let t0=0,t1=1,dx=x2-x1,dy=y2-y1;for(const[p,q]of[[-dx,x1-rx],[dx,rx+rw-x1],[-dy,y1-ry],[dy,ry+rh-y1]]){if(Math.abs(p)<1e-9){if(q<0)return false;continue}const r=q/p;if(p<0){if(r>t1)return false;if(r>t0)t0=r}else{if(r<t0)return false;if(r<t1)t1=r}}return t0<1&&t1>0}
