import{buildSceneGeometry,GEOMETRY_STRIDE}from'./webgl-geometry.js';
export function qualityForFrame(ms,current=1){if(ms>24)return Math.max(.58,current-.08);if(ms<17)return Math.min(1,current+.025);return current}
export function qualityForMode(mode,adaptive=1){return mode==='performance'?.64:mode==='quality'?1:Math.max(.58,Math.min(1,adaptive))}
export function sceneProfile(level){return level?.id==='helix'?{mix:1,pulse:1}:{mix:0,pulse:.35}}
const VS=`attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const FS=`precision mediump float;varying vec2 uv;uniform float t;uniform float danger;uniform vec2 grav;uniform float aspect;uniform float helix;float line(float v,float w){return 1.-smoothstep(0.,w,abs(v));}void main(){vec2 q=uv*2.-1.;q.x*=aspect;float z=max(.08,q.y+.34);float persp=1./z;float gx=fract((q.x*persp+t*.004)*2.2)-.5;float gy=fract(persp*.55)-.5;float grid=(line(gx,.028)+line(gy,.022))*.09;float rings=line(fract(length(q)*3.2-t*.035)-.5,.035)*.12*helix;float wall=(1.-smoothstep(.2,.82,abs(q.x)))*smoothstep(-.95,.65,q.y);float beam=pow(max(0.,1.-abs(q.x+.32+.06*sin(t*.21))),10.)*.14;float edge=pow(max(0.,abs(q.x)-.72),2.)*1.7;vec3 museum=mix(vec3(.008,.025,.036),vec3(.025,.105,.14),wall);vec3 lab=mix(vec3(.016,.008,.035),vec3(.12,.045,.22),wall);vec3 base=mix(museum,lab,helix);base+=mix(vec3(.10,.58,.72),vec3(.63,.24,.95),helix)*(grid+beam+rings);base+=mix(vec3(.3,.72,.78),vec3(.25,.9,1.),helix)*pow(max(0.,1.-length(q-vec2(.18,-.18))),9.)*.12;float alert=danger*.01;base=mix(base,vec3(.18,.025,.045)+base*.65,alert*.45);float gdot=max(0.,dot(normalize(vec2(q.x,q.y+.15)+vec2(.0001)),normalize(grav+vec2(.0001))));base+=mix(vec3(.08,.55,.7),vec3(.56,.2,.92),helix)*gdot*.04;base*=1.-edge;base*=.72+.28*smoothstep(1.35,.18,length(q));gl_FragColor=vec4(base,1.);}`;
const GVS=`attribute vec3 position;attribute vec3 normal;attribute float shade;uniform vec2 cam;uniform float zoom;uniform float aspect;varying vec3 n;varying float s;varying float depth;void main(){float halfY=280.0/max(.72,zoom);float halfX=halfY*aspect;vec2 q=vec2((position.x-cam.x)/halfX,-(position.y-cam.y)/halfY);q+=vec2(position.z*.00145,-position.z*.00185);float dz=.58-position.z*.0042;gl_Position=vec4(q,clamp(dz,-.95,.95),1.);n=normal;s=shade;depth=position.z;}`;
const GFS=`precision mediump float;uniform float helix;uniform float danger;varying vec3 n;varying float s;varying float depth;void main(){vec3 museum=mix(vec3(.045,.13,.17),vec3(.18,.56,.65),step(.5,n.z));vec3 lab=mix(vec3(.09,.035,.16),vec3(.48,.20,.72),step(.5,n.z));vec3 base=mix(museum,lab,helix);vec3 light=normalize(vec3(-.35,-.65,.9));float nd=.42+.58*max(0.,dot(normalize(n),light));float edge=depth>1.?1.:.7;base*=nd*s*edge;base+=mix(vec3(.02,.18,.22),vec3(.22,.05,.34),helix)*(danger*.0022);gl_FragColor=vec4(base,.82);}`;
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader compile');return s}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'link');return p}
export class WebGLScene{constructor(canvas){this.c=canvas;this.gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});this.quality=1;this.adaptive=1;this.mode='auto';this.reducedMotion=false;this.avg=16.7;this.ok=false;this.geometryOk=false;this.profile={mix:0,pulse:.35};this.geometryVertices=0;this.geometryKey='';if(!this.gl)return;try{const gl=this.gl;this.p=program(gl,VS,FS);this.u={t:gl.getUniformLocation(this.p,'t'),danger:gl.getUniformLocation(this.p,'danger'),grav:gl.getUniformLocation(this.p,'grav'),aspect:gl.getUniformLocation(this.p,'aspect'),helix:gl.getUniformLocation(this.p,'helix')};const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);this.quad=b;this.a=gl.getAttribLocation(this.p,'p');this.gp=program(gl,GVS,GFS);this.gu={cam:gl.getUniformLocation(this.gp,'cam'),zoom:gl.getUniformLocation(this.gp,'zoom'),aspect:gl.getUniformLocation(this.gp,'aspect'),helix:gl.getUniformLocation(this.gp,'helix'),danger:gl.getUniformLocation(this.gp,'danger')};this.ga={position:gl.getAttribLocation(this.gp,'position'),normal:gl.getAttribLocation(this.gp,'normal'),shade:gl.getAttribLocation(this.gp,'shade')};this.gb=gl.createBuffer();this.geometryOk=true;this.ok=true;this.resize()}catch(e){console.warn('WebGL scene fallback',e);this.gl=null}}
setSettings(v={}){this.mode=v.quality||'auto';this.reducedMotion=!!v.reducedMotion;this.quality=qualityForMode(this.mode,this.adaptive);this.resize()}
resize(){if(!this.gl)return;const d=Math.min(devicePixelRatio||1,2)*this.quality,w=Math.max(1,Math.floor(innerWidth*d)),h=Math.max(1,Math.floor(innerHeight*d));if(this.c.width!==w||this.c.height!==h){this.c.width=w;this.c.height=h;this.gl.viewport(0,0,w,h)}}
updateGeometry(g){if(!this.gl||!this.geometryOk)return;const solids=g.world?.solids||g.level?.solids||[],key=`${g.level?.id||'none'}:${solids.length}`;if(key===this.geometryKey)return;const data=buildSceneGeometry(solids);this.geometryKey=key;this.geometryVertices=data.length/GEOMETRY_STRIDE;const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.gb);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW)}
renderGeometry(g,view){if(!this.geometryOk||!view||!this.geometryVertices)return;const gl=this.gl,stride=GEOMETRY_STRIDE*4;gl.useProgram(this.gp);gl.bindBuffer(gl.ARRAY_BUFFER,this.gb);gl.enableVertexAttribArray(this.ga.position);gl.vertexAttribPointer(this.ga.position,3,gl.FLOAT,false,stride,0);gl.enableVertexAttribArray(this.ga.normal);gl.vertexAttribPointer(this.ga.normal,3,gl.FLOAT,false,stride,12);gl.enableVertexAttribArray(this.ga.shade);gl.vertexAttribPointer(this.ga.shade,1,gl.FLOAT,false,stride,24);gl.uniform2f(this.gu.cam,view.cx??500,view.cy??280);gl.uniform1f(this.gu.zoom,view.zoom||1);gl.uniform1f(this.gu.aspect,this.c.width/Math.max(1,this.c.height));gl.uniform1f(this.gu.helix,this.profile.mix);gl.uniform1f(this.gu.danger,g.security?.alert||0);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,this.geometryVertices);gl.disable(gl.BLEND);gl.disable(gl.DEPTH_TEST)}
render(g,dt,view){if(!this.gl)return;this.profile=sceneProfile(g.level);this.updateGeometry(g);const ms=dt*1000;this.avg=this.avg*.94+ms*.06;if(this.mode==='auto'){this.adaptive=qualityForFrame(this.avg,this.adaptive);const nq=qualityForMode(this.mode,this.adaptive);if(Math.abs(nq-this.quality)>.035){this.quality=nq;this.resize()}}const gl=this.gl;gl.disable(gl.DEPTH_TEST);gl.useProgram(this.p);gl.bindBuffer(gl.ARRAY_BUFFER,this.quad);gl.enableVertexAttribArray(this.a);gl.vertexAttribPointer(this.a,2,gl.FLOAT,false,0,0);gl.uniform1f(this.u.t,this.reducedMotion?0:performance.now()/1000);gl.uniform1f(this.u.danger,g.security?.alert||0);gl.uniform2f(this.u.grav,g.world?.gravity?.x||0,g.world?.gravity?.y||1);gl.uniform1f(this.u.aspect,this.c.width/Math.max(1,this.c.height));gl.uniform1f(this.u.helix,this.profile.mix);gl.drawArrays(gl.TRIANGLES,0,6);gl.clearDepth(1);gl.clear(gl.DEPTH_BUFFER_BIT);this.renderGeometry(g,view)}
getStats(){return{webgl:this.ok,geometry:this.geometryOk,geometryVertices:this.geometryVertices,geometryTriangles:this.geometryVertices/3,quality:+this.quality.toFixed(2),qualityMode:this.mode,reducedMotion:this.reducedMotion,frameMs:+this.avg.toFixed(1),sceneMix:this.profile.mix}}}
